### ISSUE TITLE
最新版本好像有问题，格式疯狂错误

### ISSUE THREAD

**Issue by MoFan13** [NEKOparapa/AiNiee#101]
同样的文本换回4.62就正常
[新建文件夹.zip](https://github.com/NEKOparapa/AiNiee/files/14394874/default.zip)
这是需要汉化的文本

**Comment by NEKOparapa** [comment]
你截图一下你的翻译设置以及复制一下黑框里的运行日志

**Comment by MoFan13** [comment]
[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 13.19 秒
[INFO] 本次请求与回复花费的总tokens是： 2392
[INFO] AI回复的文本内容：
 {
        "0": "{t}*好了，让我们再试一次，用点力气……*{/t}",
        "1": "嗯...发生了什么？",
        "2": "你真的需要那样摇晃我吗？",
        "3": "是的...抱歉...你当时真的不太好。",
        "4": "这不是你的错，我只是有点疲惫。",
        "5": "我睡得不好，床比我习惯的硬多了。再加上公路的噪音。很难入睡。而且这个房间超级热。我整晚都在出汗。",
        "6": "抱歉。这个房间比公寓的其他地方要热一些。不过你会适应的。我保证。",
        "7": "希望如此。",
        "8": "{t}*我应该让她继续睡觉吧……*{/t}",
        "9": "{t}*哇...她的衬衫解开了扣子...*{/t}",
        "10": "{t}*我几乎能看到她的胸部了.*{/t}",
        "11": "{t}*也许我可以...她永远不会知道...*{/t}",
        "12": "{t}*我该怎么办？*{/t}",
        "13": "{t}*哎呀...我的背疼死了，我出汗得像只猪一样.*{/t}",
        "14": "{t}*这张床比我习惯的硬多了...房间就像桑拿房一样热...*{/t}",
        "15": "我有点想念家里的卧室...",
        "16": "我需要去洗手间...",
        "17": "呀呀呀。",
        "18": "克里斯汀走向洗手间。她不知道你在里面...",
        "19": "{t}*嗯...门是开着的...*{/t}",
        "20": "{t}*天啊...*{/t}",
        "21": "{t}*我觉得我能看到[玩家名]叔叔的...*{/t}",
        "22": "{t}*停下来，克里斯，你不应该盯着看...这是不对的.*{/t}",
        "23": "{t}*好了，没什么比排空旧水箱更爽的了...*{/t}",
        "24": "你听到门吱呀一声...",
        "25": "{t}*那是什么声音？*{/t}",
        "26": "{t}*是克里斯汀吗？*{/t}",
        "27": "{t}*天啊！他穿着内裤，我甚至觉得我能看到他的...*{/t}",
        "28": "你走向车库。",
        "29": "希望不会有交通堵塞...",
        "30": "终于...有点晚了...但至少我到了...",
        "31": "她不在走廊，她在我的办公室吗？",
        "32": "{t}*是的...我离开时忘记锁门了...*{/t}",
        "33": "早上好，我猜你是安德斯女士？",
        "34": "实际上是安德斯夫人...但你可以叫我索尼娅...很高兴见到你。",
        "35": "{t}*她已经结婚了，该死...*{/t}",
        "36": "彼此彼此...",
        "37": "首先，我要为迟到道歉。",
        "38": "没关系...",
        "39": "我猜你是布朗先生？"
}


Warning: AI回复内容存在问题: AI回复内容不符合要求的格式,将进行重新翻译

Warning: AI回复内容格式错误次数: 1 到达2次后将该段文本进行拆分翻译

[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 1686
[INFO] 当前发送的原文文本：
 {"0": "You were getting really close when...", "1": "What is happening?", "2": "FUCK!", "3": "Where am I? Shit that was just a dream. I gotta hurry to rub this one out in the bedroom while I remember what just happened.", "4": "Time to jerk it!", "5": "You finished the job and fell asleep.", "6": "Be romantic", "7": "Be direct[ho1]", "8": "No[frd2]", "9": "[smgr]Maybe next time", "10": "If you want to", "11": "[smgr]Tell a lie", "12": "[smgr]Peek", "13": "Go change", "14": "[smgr]Peek some more", "15": "Peek some more", "16": "[smgr]Go change", "17": "Agree and continue", "18": "Praise her and continue", "19": "[smgr]End it[fr3][ho3]", "20": "Let her continue", "21": "Spank", "22": "Don't spank", "23": "Go to her from behind", "24": "Go to her directly", "25": "Go to sleep", "26": "Touch her", "27": "Stop it", "28": "Yesterday sure was a busy night... but I hadn’t slept that well in ages, maybe I should try it again sometime...", "29": "{t}*So what are we going to do today?*{/t}", "30": "You were just changing when you received an SMS from Sonya...", "31": "I need to see you [player_name], it’s important... I don't know whether I can handle this...", "32": "{t}*That is weird, I've never heard Sonya talk like that...*{/t}", "33": "You answered...", "34": "Sonya are you alright? What do you need?", "35": "I don't know... I need to talk to you face to face...", "36": "Okay, we can do that. Where are you?", "37": "I’m near the office, do you mind if we meet there?", "38": "Okay, let’s do that, I’ll be there in 5 minutes.", "39": "I ’ll be waiting inside, bye."}



[INFO] 已发送请求,正在等待AI回复中-----------------------



[INFO] 请求与回复的tokens数预计值是： 2086
[INFO] 已成功接受到AI的回复-----------------------
[INFO] 已成功接受到AI的回复-----------------------
[INFO] 已成功接受到AI的回复-----------------------
[INFO] 当前发送的原文文本：
[INFO] 该次请求已消耗等待时间： 14.69 秒
[INFO] 该次请求已消耗等待时间： 15.04 秒
[INFO] 该次请求已消耗等待时间： 12.08 秒
 {"0": "Quick! I need to record this!", "1": "{t}*Oh fuck...*{/t}", "2": "Oh no, I'm getting error statement... I made mistake somewhere in the code, I have to correct it.", "3": "Hey Uncle [player_name], what are you doing?", "4": "Well, I was just... uhm... finishing this last bit of coding.", "5": "{t}*Phew, that was close*{/t}.", "6": "Oh... so you are already done? Because I might need your help with something...", "7": "So long as it doesn't invovle manual labor, I'm your man!", "8": "Hahaha. No, it’s not anything like that Uncle [player_name], I just have a little problem with my computer. And well, since you're good at that stuff...", "9": "You want me to go and fix it, huh?", "10": "Sure. Give me a minute to save my work and I will see what I can do. I’ll have it fixed in no time.", "11": "Thanks Uncle [player_name], you’re the best!", "12": "Oh and I almost forgot...", "13": "Have you seen my pyjamas?", "14": "Err... you know...", "15": "What? You took it again? What is wrong with you godfather?", "16": "Listen Christine...", "17": "Look, forget it. Can I have my PJs back please?", "18": "You give Christine her Pyjamas back, she shuts the door and runs to her room.", "19": "{t}*Yeah, taking her pyjamas again...\n [player_name],[player_name], [player_name]... what the hell were you thinking?*{/t}", "20": "{t}*I should go sleep already and deal with this later.*{/t}", "21": "You follow Christine into her room.", "22": "Ok, so what's the problem?", "23": "I was trying to download some music and movies, but the site had all these different download buttons. I didn't know which one to click...", "24": "So I clicked them all...", "25": "Oh no.", "26": "And now, every time I open a browser, these ads take over the entire screen.", "27": "You approach the computer and hit enter. Suddenly...", "28": "Oh my god Christine, what kind of movies were you downloading?", "29": "Christine turned towards the computer's screen in shock.", "30": "Just regular stuff? Not... you know...", "31": "Not \"Hot Black on Asian Porn\"? It's ok Christine. I believe you. This stuff happens.", "32": "This is so embarassing.", "33": "The good news is I can fix this. It's gonna take some time though.", "34": "Christine answers silently...", "35": "Thank you, Uncle [player_name]...", "36": "Christine leaves the room and you start fixing her computer.", "37": "Okay, let’s get to it...", "38": "First we need to do a scan... yep there's the adware. Wow, it's hidden pretty deep down.", "39": "Got it. That wasn't too tough."}
[INFO] 本次请求与回复花费的总tokens是： 2341
[INFO] 本次请求与回复花费的总tokens是： 2666
[INFO] AI回复的文本内容：
[INFO] AI回复的文本内容：
 {
    "0": "哦，我失礼了吗？",
    "1": "我是布朗先生，没错，[player_name] 布朗。",
    "2": "那么，布朗先生……",
    "3": "请叫我 [player_name]……",
    "4": "好的 [player_name]，我们开始吧？",
    "5": "好的，索尼娅，在我们开始之前，我先自我介绍一下。我是 [player_name] 布朗，也是这家公司的老板。",
    "6": "如果你准备好了，我们就开始面试吧。",
    "7": "首先，我只是想告诉你，门是开着的……我敲了门，但没有人回答，所以我就进来了。",
    "8": "我应该等一等，我想道歉……",
    "9": "{t}*她显然更担心悄悄溜进办公室的事情，而不是我迟到……*{/t}",
    "10": "没关系。天哪，如果普通的小偷长得像你这样，我也不介意偶尔被闯入。",
    "11": "嗯……",
    "12": "所以，我看了你的简历，你有社会学学士学位……",
    "13": "是吗？",
    "14": "是的……没错……",
    "15": "那么，有了这样的学位，你为什么想申请秘书职位？",
    "16": "嗯，这和其他任何工作一样……",
    "17": "你打断了她……",
    "18": "回答不太热情。",
    "19": "我在这里不是吗？来参加这次面试。我想要这份工作。",
    "20": "好的。现在这份工作不仅仅是基本的秘书工作。",
    "21": "比如？",
    "22": "你还将处理与潜在客户的沟通，并且需要参加各种会议、晚宴等等……",
    "23": "那绝对可以……",
    "24": "太好了。下一个问题。你能明天开始吗？我和一个客户有个会议，需要你在场。",
    "25": "这通知时间不够长。",
    "26": "是的，明天的会议将最终确定许可条款以及我将从他那里得到的我们的签名软件的价格。我需要你在那里……",
    "27": "索尼娅显然在仔细听每个字。你面带微笑地说：",
    "28": "……转移他的注意力。这样他就会对自己签署的文件少关注。",
    "29": "那我该如何做？",
    "30": "坦白说，我需要你用你的身体转移他的注意力……",
    "31": "索尼娅怀疑地看着你。",
    "32": "所以，你的意思是勾引他？",
    "33": "基本上是。",
    "34": "什么？这是在开玩笑吗？",
    "35": "不，一点也不。为什么？",
    "36": "哇，这个主意太糟糕了。拿着你的工作，{i}metelo por tu culo{/i}！",
    "37": "等等，索尼娅，我不是那个意思。",
    "38": "索尼娅怒气冲冲地离开了办公室。",
    "39": "{t}*该死……这本来可以处理得更好的……*{/t}"
} {
    "0": "那么讨论就到此为止。你需要看起来性感。",
    "1": "我知道，我们去问你的教父。他在这里。他是个男人。我们可以利用他。",
    "2": "杰斯，不要这样对我。",
    "3": "那么[玩家名]大叔，你觉得呢？是还是不是？",
    "4": "你被这个问题吓了一跳。你甚至不知道这个杰西卡在说些什么。",
    "5": "{t}*同意还是不同意，看起来我有一半的机会猜对*{/t}",
    "6": "嗯...肯定是。",
    "7": "克里斯汀，永远不要怀疑我...我了解男人。",
    "8": "{t}*我还是不知道我同意了什么。*{/t}",
    "9": "但我不知道...",
    "10": "我得说不。",
    "11": "看？他同意了。这完全不合适。我不想看起来像个廉价的荡妇。",
    "12": "{t}*我到底拒绝了什么？*{/t}",
    "13": "首先，这不是廉价的。你需要学会享受生活。如果你有的话，就炫耀吧。",
    "14": "对不起，但我分心了，问题是什么？...",
    "15": "克里斯汀想穿一些无聊和普通的衣服去面试。我觉得她需要一些更\"特别\"的东西，如果你懂我的意思。",
    "16": "那么\"[玩家名]大叔\"，你的判决是什么？",
    "17": "是的，听起来特别不错...",
    "18": "我不知道...有点...",
    "19": "我觉得穿标准西装去面试就好了。没必要太过了。",
    "20": "让我们去试衣间。一旦你看到你穿上我挑选的衣服有多性感，你就永远不会再穿无聊的西装了！",
    "21": "你跟着女孩们走到精品店后面。",
    "22": "看起来我们有试衣间全都给我们自己了。那我就选这个。",
    "23": "好的，我要给你挑一套衣服。",
    "24": "不要太疯狂，杰丝！",
    "25": "相信我！",
    "26": "杰西卡高兴地离开去给克里斯汀挑选衣服。你听到克里斯汀在更衣室里有些动静。她可能在换衣服。",
    "27": "{t}*我想看看她在里面。这不正常吧？而且我也可能被发现。但是...*{/t}",
    "28": "{t}*但你知道吗？去他的。不入虎穴焉得虎子。*{/t}",
    "29": "{t}*我能看到她的文胸...看起来她可能会脱掉短裤。*{/t}",
    "30": "{t}*我觉得我听到杰西卡来了。最好退后一点。*{/t}",
    "31": "你耐心地等在试衣间外。杰西卡拿着西装回来。",
    "32": "给你，克里斯。试试这件。相信我，你穿起来会性感得不得了！",
    "33": "我不知道，杰丝，这有点过了。你不觉得吗？",
    "34": "不会太过分。刚刚好。",
    "35": "你的教父也会喜欢的...",
    "36": "杰斯！这太紧了。我感觉随时都会跳出来...",
    "37": "{t}*她没有说谎。但她穿上那身衣服看起来性感得要命...*{/t}",
    "38": "这就是重点，克里斯。",
    "39": "我知道你不喜欢高跟鞋，但拿着吧。它们会让整套衣服更完美。"
}





[INFO] 本次请求与回复花费的总tokens是： 2172
[INFO] AI回复的文本内容：
Warning: AI回复内容存在问题: AI回复内容不符合要求的格式,将进行重新翻译
 {
        "0": "历史",
        "1": "Q.S",
        "2": "Q.L",
        "3": "女侍",
        "4": "秘书",
        "5": "库珀小姐",
        "6": "医生",
        "7": "状态",
        "8": "{t}*该死...*{/t}",
        "9": "{t}*哦，是我的手机。让我看看.*{/t}",
        "10": "{t}*该死，我应该真的设置一个带声音的闹钟。该死.*{/t}",
        "11": "{t}*今天我有秘书面试.*{/t}",
        "12": "{t}*我得快点准备好.*{/t}",
        "13": "{t}*克里斯汀还在睡觉。最好把她叫醒。这样她就不会在一个陌生的空公寓里醒来.*{/t}",
        "14": "我应该叫醒她吗？",
        "15": "克里斯汀？醒醒...",
        "16": "克里斯汀还在沉睡中...",
        "17": "{t}*我再试试还是用点力？*{/t}",
        "18": "{t}*再试试.*{/t}",
        "19": "{t}*克里斯汀，醒醒...*{/t}",
        "20": "嗯...",
        "21": "早安克里斯汀！抱歉打扰你，但我要走了...",
        "22": "当克里斯汀坐起来时，你让开了。",
        "23": "叔叔[player_name]...？发生了什么...？",
        "24": "没什么，我只是想告诉你我要去工作了...所以你一个人在家。",
        "25": "我不想让你醒来时周围没人感到害怕...",
        "26": "昨晚你一个人醒来时害怕了吗，叔叔[player_name]？",
        "27": "嗯...",
        "28": "你想起昨晚发生的事...",
        "29": "是的，就像昨晚一样。为什么你不叫醒我？",
        "30": "我不想...",
        "31": "...打扰你。你睡得那么香甜。而且我记得有人被吵醒后会发脾气。",
        "32": "来吧克里斯汀...我不是那么糟糕...对吧？",
        "33": "嘿，妈妈总是告诉我让你多睡会儿。“不值得麻烦”是她的原话。",
        "34": "好吧，我明白了。",
        "35": "无论如何，我得走了，需要什么就打电话给我。",
        "36": "叔叔[player_name]，你真好...",
        "37": "但我不再是小孩了。我不会在你的公寓里感到恐慌。",
        "38": "是的，我想是这样。说得对。",
        "39": "好的，我要出门了。需要什么就打我电话。"
}Warning: AI回复内容存在问题: AI回复内容不符合要求的格式,将进行重新翻译




Warning: AI回复内容格式错误次数: 1 到达2次后将该段文本进行拆分翻译


Warning: AI回复内容格式错误次数: 1 到达2次后将该段文本进行拆分翻译
Warning: AI回复内容存在问题: AI回复内容不符合要求的格式,将进行重新翻译


Warning: AI回复内容格式错误次数: 1 到达2次后将该段文本进行拆分翻译
频繁出现回复格式错误，4.62就正常，设置是一样的
![Uploading 屏幕截图 2024-02-25 193022.png…]()

**Comment by MoFan13** [comment]
<img width="922" alt="屏幕截图 2024-02-25 193040" src="https://github.com/NEKOparapa/AiNiee/assets/85187498/2dd0f5e1-2143-4d0e-8490-d1dfb3c73584">
<img width="922" alt="屏幕截图 2024-02-25 193022" src="https://github.com/NEKOparapa/AiNiee/assets/85187498/c71a117d-e4cf-4d18-97bf-393fce07044f">

**Comment by NEKOparapa** [comment]
已修复，因为文本中含有大括号，提取时出现了问题，下载4.63.3或者测试版
