### ISSUE TITLE
錯行檢查出現error

### ISSUE THREAD

**Issue by Julian083** [NEKOparapa/AiNiee#107]
[INFO] 已发送文本嵌入请求-------------------------------------
[INFO] 请求内容长度是： 422
[INFO] 已发送请求，请求内容是： ['下劣で淫猥な行為を真摯に行おうとしてしまう', 'なんれすかコレぇ！', 'お尻の穴いっぱいれぇ…キモひイイぃぃ', 'リエッタの危惧していた通り…いやそれ以上の', '快感が電流になってお尻から脳に走り抜けた', '（アナルオナニーより……', 'ずっとキモチイイですっ！', '『教え』に対して真摯なリエッタ、恥辱も快楽も受け入れ', '『ドスケベご奉仕』に真剣に取り組もうとする…', '深っ…', '…お腹まで…んぐ', '……またっ…', 'またっ…ケツ穴で…イッてしまいます…う˝ぅぅ！！！', '常 識改変で罪の意識はないはずだが', '本能か……リエッタは愛する人へ謝罪しながら……', '…わ…わらひ……', '……あひっ', '……ダメです……', 'イッたばかりで……頭が……まわりませんっ', '頭に浮かんだ疑問もケツ穴セックスの快楽と', '常識改変の魔力が籠もった教祖の言葉で押し流される', 'シスターとしての役目を全うしたと思いこんでいる', 'リエッタは、その言葉に少し誇らしさを見せるほど', '『ドスケベご奉仕』を完全に受け入れてしまう……', 'しようとしている行為がセイレーンを貶める', '醜態を晒すこととは思わず…リ エッタは腰を振り始める', '『教え』の通りにすると……なんでこんなに', 'ドキドキして……興奮してしまうのでしょうか', 'リエッタの…', 'け…ケツ穴にエッチなぁざ～めん…い～っぱい', 'くださぁ～～いっ', '『教え』の通りやっているのに…', '…恥ずかしくて死 にそうですっ！！）', '教祖の言う捻じ曲がった『ド変態の常識』を', 'どんどん刷り込まれていくリエッタ…', 'お尻の中に残って る精液が…', '……どんどん熱くなって…', '熱い…熱いですっ……はやくっ', '早く……ケツ穴にぃぃ…ソレをぉ！', '……こんな声も出されるんですね', 'いつも嫌味な喋り方なのに……必死に腰を振って…', 'ちょっと可愛いかもです', '『ドスケベご奉仕』で主導権を握られ 続けていたが', '前にシテしまったようなエッチな……ことよね…）', '「まずは約束を守ってもらおうかな～', '覚えてる？『お兄ち ゃんとセックス』してこい、って言ったの？」', '「あはは、じゃあすぐしようか', 'お兄ちゃんとボクのチンポを比べた『チン比べセックス』♥」', '………それをすれば……', '本当に……クルトを助けてくれるのね…」', '「もちろん！パパにも助けてもらうよう', '働 きかけてあげる、シテくれたらすぐに…', '急ぐなら通信石使ってあげるよ」', '（クルト………力のない姉を許して……', 'それでも貴方だけは必ず助けるから……）', '「任せてよ～……それじゃ早速', '『チン比べセックス』始めよう♥」', '「お兄ちゃんの猶予はないん だよ？', 'だったら早くシないと…ね♥」', '「ふふ♥それじゃあここで……', 'コレに着替えてヤろうか」', '渡されたのは布切れとハ ート型のニプレス…', '…そして卑猥なアクセサリー……', '「それはフンドシって言ってね、ピーニス教じゃ', 'よく使われるんだ……位の低い便器用信者の服だよ♥」', '（こんなものより卑猥な衣服を女性に着せているの？', '……ピーニス教……思った以上に最低な宗教 ね……）', '「ちょっとちょっと…', 'そんなとこで着替えないでよ」', '………わかったわ……」', '（うう…すごい……見られてるわ……', ' 乳首を……アソコを……うっ', '意識しちゃダメ…', 'さっき魔法を使ったせいで体が熱くなってるのに…）', 'なんて卑猥な恰好なの……', 'さっきまで意識しないようにしてた……股間の熱が……んっ', '服とも呼べない下品なモノをまとったことで', 'さっきまで抑えていた性欲と快感が頭と体をめぐり始めた…', '「…牛コスの時も思ったけど……下品でスケベな服が', 'よく似合うよね、お姉ちゃんは♥」', '「あはは、さっきの魔法のせいで体が敏感になってる？', 'お姉ちゃんの魔力が大きすぎるせいだね…普通の女なら', 'チンポにがっつくレベルの性欲増大と快感のはずだから…」', 'ぶるんぶるんっ…カティーブも服を脱いでいて', '大きすぎる肉棒を見せつけるように腰をふる', '「あはは、もうマン汁垂れてきてるね♥', '大丈夫、す～ぐキモチよくなれるからっ」', '（ま…またアレをいれられちゃうのね……', '前みたいなドスケベセックスを……クルト……貴方を救うためだから……', '…………でも……）', '「ああ、違う違う！寝転ぶんじゃなくて…', 'そこでお尻向けて立って……そうそう…そのまま腕を頭に組んで…」', '「ボクも興奮しまくってからセックスしたいか らさ♥', 'このままお尻を振って僕のチンポを元気にしてよ」', 'ドッドッ……自覚はないが…決意した', 'テレーナの心臓の鼓動は爆乳の上からでもわかるほど高鳴っていた', '…本当に…', 'え…エッチなことばかり……あぅんっ', 'どう…かしら…', '私の……先生の腰ふり……んっ', 'ふいに魔力を高めてしまうと体の中の蟲が', '魔力を快楽の電流に変え体と頭に流し込み……', 'テレーナの思考を焼き切っ てしまった', '…お………', 'オマンコっ！', '…感覚だけ……思い出してきた…', '……子宮をガンガンつかれたことだけは……体がっ…', 'オ マンコが覚えてる', 'このエロい形のドスケベオマンコに', '何をいれるんですか～？」', '本当におバカなドスケベ女みたいな', 'しゃべり方……で…でも……）', 'カティーブ君と本当におセックス', 'したくなってきてるのぉ', 'いい感じなのね……もっと…', 'もっと悦ばせないと！', 'パンパン！手拍子をするカティーブに合わせて', '腰を振るテレーナ…その姿はまさにセックス狂いの', '娼婦に しか見えなかった', 'この子！私のオマンコを玩具みたいにっ！', 'でも…でも……）', '意識が朦朧として言われるがままにガニ股姿 で', '前面の体を晒すテレーナ', 'この媚薬状態になれてきたのか……', 'チンポを口から離し名残惜しそうにしつつも', 'テレーナは誘いを断ったが……', 'カティーブ君の', 'デカチン大好き先生だからぁ！！', 'ん˝ちゅ……', 'カティーブくぅん…', 'イッた直後にキスハメでまたアクメをする…', 'もはやクルトへの想いは霧散し快楽だけを', '貪ることしか考えられなくなる……', 'ずい…快楽で半ば気絶していたテレーナの', '目の前に自分の精液まみれの肉棒をさらす……', 'それは未だに熱と硬さを失っていなかった', '…そう…ね…', 'んちゅっ', '…そう…だけど…', '…ゴムは…ないんじゃ……」', 'そんなクルトを裏切るような', '最低ドスケベ中だしセックスなんてぇ……）', '理性だけでなく倫理観まで快感で', '飛ばされたテレーナはクルトへの最低の裏切り行為を', '許可してしまう……性器をどろどろにしながら…', 'カティーブ君のオチンポも……', '形がしっかりわかって……あぅん', 'スクワットの姿勢で抱きつくカティー ブのチンポで', '子宮をうちつけ…その顔はスケベ親父のように', '鼻を伸ばしヨダレをたらす……いつもの才色兼備な', 'テレーナか らは想像もできないような姿だった', 'そうよぉ！', 'クルトのかわいいチンポじゃこんなコーフンしないしぃ', 'そう！', 'カティーブくんのチンポぴったりっ', '突かれるたびに', '軽イキするっ…お˝っ！', 'クルトじゃ…', 'こんな私好みのオゲレツなドスケベ セックスしてくれないのよぉ', 'ぜんぜんスケベじゃ', 'オチンポもカティーブ君のが', 'すきぃぃぃん', 'ちっちゃいチンポよりっ…', 'このチンポぉ…愛してますぅ', 'カティーブに伝えてしまった好きだという言葉…', 'その興奮が重なり、また深くイッてしまう', 'うそぉ…動かなくても', 'イキそ……んひっ', '……これで…きっと私……', 'もう本当にカティーブ君の……）', 'オゲレツドスケベでぇ…', '家畜先生のテレーナ…いぐぅ…もぉぉ', '……テレーナは白目をむきながら', '中だしを懇願する……そして牛のような声で……', 'クルトのザーメン…掻き出して………', '強くて…スケベなザーメンに満たされるぅ', 'その体勢のまま二人はベロチューをしながら', '交わ り…セックスを続け……', '淫紋の効果が切れ……正気を取り戻したテレーナ', '……だったが…以前と違っていたのは……', '妖しい笑みを浮かべ子宮のあたりのお腹を', '嬉しそうにさするテレーナ', '後悔の念はなく……カティーブの家畜になれたことに', '興奮を覚えてしまっていた………', '（久々に体を動かすか？', '…大分なまってきたし……）', '「いや…用って訳でもないんだけど……', 'ここって……」', '「闘っている……というか訓練中ってカンジね', 'とっても楽し～い訓練チュウ', '「…そうなのか……それにしちゃ……', 'なんだかスゴい野太い声が聞こえるけど……」', '（少しアリカの声に似てる気がするけど……', 'いや、アイツがあんな声出したのなんて一度も聞いたことないし', '……気のせいか…）', '（見えづらいけど……男と女……', '女はすごいおっぱい…かな？よく見えないけど……）', '（うっ……すごい声……', '何を言ってるか、ここだと聞き取りづらいけど……）', 'わかったかしら？', 'そういう訳だから……今日はごめんなさいね', '「…これは……本当に何考えてるのよ', 'あのスケベ領主……」', '自分の勃起クリを叩きつけるアリカ', '……突いた刺激だけ で……一瞬頭が真っ白に…', '前も感じたけど…このクリチンポ…こんなに感じるものなの？', '早くイケ…', 'いっちゃえ！この変態領主っ…あんっ！', 'なら…このおっぱい見ながら……', 'さっさとイキなさい…よぉ！このぉっ！！', '自分でシテるときは全然こなかった のに', '把屁股塞满……好恶心啊！', '', '', '正如莉艾塔所担心的那样……不，比那更强烈的', '快感像电流一样从屁股冲过大脑', '（比起肛门自慰……一直都很舒服！', '好舒服啊！', '莉艾塔真诚地接受了“教导”，无论是耻辱还是快感', '她都认真地致力于“淫荡服务”……', '好深……', '……到了……肚子里了……嗯', '……又……', '又……在屁眼里……又……又要……要出来了……呜˝啊啊！！！', '虽然没有罪恶感，但 她的本能……向爱的人道歉……', '……哇……', '……啊嗯', '……不行……', '刚刚才高潮了……头脑……还没清醒过来……', '即使有疑问浮现在脑海中，也被肛交的快感和', '常识改变的力量所淹没，教主的话语推翻了一切', '她认为自己已经完成了作为修女的职责', '莉艾塔听到这句话时，有点自豪地展现出来', '完全接受了“淫荡服务”……', '她试图做的行为贬低了塞壬', '但她并没有意识到这是在暴露丑态……开始扭动起腰来', '按照“教导”的指示……为什么会这么', '心跳加速……兴奋不已呢？', '莉艾塔的……', '肛门里……好……性感啊……请给我……', '更多的……快感……', '即使按照“教导”的指示……', '……我都觉得好害羞，好想死！！）', '莉艾塔被灌输着教主扭曲的“变态常识”……', '屁股里残留的精液……', '……越来越热……', '好热……好热啊……快点……', '快点……在肛门里……来吧！', '……原来还会发出这样的声音啊', '平时总是说话刻薄的她……现在却拼命地扭动着腰部……', '有点可爱呢', '虽然一直被“淫荡服务”掌控着主导权，但她……', '……好可爱啊', '……', '之前做过的那种淫荡的事情吧……）', '“首先，让你遵守承诺吧～', '还记得吗？我说过『和哥哥做爱』，对吧？”', '“啊哈哈，那么 现在就开始吧', '哥哥和我比较一下阴茎的大小的『阴茎比较性爱』♥”', '………如果这样的话……', '你真的……会帮助克尔特吗……”', '“当 然！如果你能说服爸爸帮忙的话，', '我会立刻……', '如果你着急的话，我会给你通信石的。”', '（克尔特……请原谅无力的姐姐……', ' 但是，我一定会帮助你的……）', '“交给我吧～……那么马上', '开始『阴茎比较性爱』吧♥”', '“哥哥没有时间拖延了哦？', '那么就快点吧……♥”', '“嘿嘿♥那么就在这里……', '穿上这个，然后开始吧”', '递过来的是一块布和心形的乳贴……', '……还有淫荡的配饰……', '“这个叫做褌，是皮尼斯教常用的', '衣服……是低等便器用信徒的服装♥”', '（他们不是给女性穿着更淫荡的衣服吗？', '……皮尼斯教……比我想象中更卑劣的宗教……）', '“等等等等……', '不要在那里换衣服啊”', '……我知道了……”', '（呜呜……好可怕……被看到了……', '乳头……下体……嗯', '不要意识到……', '因为刚才使用了魔法，身体已经变得很热了……）', '这样下流的打扮……', '虽然之前一直试图不去意识到……但 是下体的热度……嗯', '因为穿上了连衣裙都算不上的下流的东西，', '之前一直压抑着的性欲和快感开始在头脑和身体中蔓延……', '“…… 虽然穿着奶牛装时也有这种感觉……', '但是，下流而淫荡的衣服真的很适合姐姐呢♥”', '“啊哈哈，因为刚才的魔法，身体变得很敏感吗 ？', '这是因为姐姐的魔力太强了……普通的女孩子应该会', '对阴茎产生强烈的性欲和快感……”', '噗哧噗哧……凯蒂布也脱光了衣服', ' 晃动着臀部，献上巨大的肉棒', '“啊哈哈，已经开始流汁了♥', '没关系，很快就会感觉很舒服的。”', '（又要被那个东西插进来了……', '为了拯救库尔特……像以前那样的淫荡性爱……', '…………但是……）', '“啊啊，不对不对！不是躺下来……', '转过身来，朝这边……对对……然后把手放在头上……”', '“我也很兴奋，所以想要先做一些刺激的事情♥', '就这样晃动着屁股，让我的小弟弟变得更加硬朗吧。”', '嘭嘭……虽然没有意识到……但是已经下定决心了。', '泰蕾娜的心脏跳动得非常剧烈，即使在巨乳的上方也能感觉到。', '……真的……', '诶……全都是淫荡的事情……啊呜', '怎么样……', '我的……老师的臀部晃动……嗯', '突然提高魔力，身体内的虫子', '将魔力转化为快感电流，流入身体和头脑……', '泰蕾娜的思维被烧毁了。', '……噢………', '阴道！', '……只是感觉……想起来了……', '……只记得子宫被狠狠地撞击……身体……', '阴道还记得。', '这个淫荡形状的阴道里', '要塞什么东西呢～？', '真的像个傻傻的淫荡女一样说话……但是……）', '我真的想和 凯蒂布君做爱。', '感觉很好呢……再……', '再多让我享受一下吧！', '拍手声响起！泰蕾娜随着凯蒂布的节奏', '晃动着屁股……这个样子完全像是性瘾者。', '这孩子！把我的阴道当成了玩具！', '但是……但是……）', '意识有些模糊，但是还是张开双腿，露出前面的身体。', '与凯蒂布的手拍声相伴，泰蕾娜晃动着臀部……看起来就像是妓女一样。', '但是……但是……）', '意识有些模糊，但是还是张开双腿，露出前面的身体。', '与凯蒂布的手拍声相伴，泰蕾娜晃动着臀部……看起来就像是妓女一样。', '已经陷入这种媚药状态了吗……', '虽然舍不得从口中放开那根小弟弟', '特蕾娜还是拒绝了邀请……', '因为凯蒂布喜欢', '大鸡巴的老师！！', '嗯˝啾……', '凯蒂布……', '刚 刚高潮后再次用吻攻击，让自己再次达到高潮……', '对库尔特的感情已经消散，只剩下了享乐……', '只能考虑贪婪地追求快感……', '在半昏迷的快感中，特蕾娜看到了', '自己的肉棒沾满了自己的精液……', '它仍然保持着热度和硬度', '……是啊……', '啾……', '……是啊……但是……', '……没有避孕套……', '背叛库尔特的话', '最低下的淫乱中出性交……）', '不仅是理性，连道德观念也被快感所支配', '特蕾娜被快感冲昏了头脑，犯下了对库尔特最低下的背叛行为……', '她的性器已经变得黏糊糊的……', '凯蒂布的小弟弟……', '形状清晰可见……啊呜', '用深蹲的姿势紧紧抱住凯蒂布的小弟弟', '撞击着子宫……她的脸像个色情老头一样', '伸长鼻子流口水……这是特蕾娜从未想象过的样子', '是啊！', '如果是库尔特的可爱小弟弟，我不会这么兴奋的', '是啊！', '凯蒂布的小弟弟正好合适', '每次被顶到都会轻微高潮……哦˝！', '库尔特……', '不会给我这样的粗暴淫乱性爱', '一点都不淫乱，凯蒂布的小弟弟才是我喜欢的', '比那些小小的小弟弟好多了……', '比那些小小的小弟弟好多了……', '我喜欢凯蒂布的小弟弟', '比那些小小的小弟弟好多了……', '比那些小小的小弟弟好多了……', ' 我爱这根♂好棒棒……', '我告诉卡蒂布我喜欢他了……', '兴奋感叠加，又深深地高潮了。', '不要……动也不要动……', '要射了……嗯呀', '……这样下去……我一定……', '我已经完全属于卡蒂布君了……）', '真是个淫荡的家畜……', '家畜老师的训练……啊啊……', '……家畜老师翻白眼', '恳求内射……发出牛一样的声音……', '把克鲁特的精液……挤出来……', '被强壮而淫荡的精液充满了……', '两人保持这个姿势接吻着', ' 交合……继续性爱……', '淫纹的效果消失了……家畜老师恢复了理智', '……但是……与以前不同的是……', '她露出妖艳的笑容，抚摸着子宫的位置', '开心地摩擦着……', '没有后悔……成为卡蒂布的家畜', '感到了兴奋……', '（久违地动一下身体吗？', '……已经有点生疏了……）', '“不是有事要办……', '这里是……', '“正在战斗……或者说是在训练中呢', '非常有趣的训练中', '“……是这样吗……但是……', '好像听到了很 粗野的声音……', '（有点像阿丽卡的声音……', '不过，我从来没有听过他发出那样的声音', '……是我的错觉吗……）', '（虽然看不太清……男人和女人……', '女人有巨大的胸部……吧？虽然看不太清……）', '（呃……好大的声音……', '虽然在这里听不太清楚……）', '你明白了吗？', '所以……今天真的很抱歉', '“……这到底是在想些什么啊', '那个淫荡的领主……', '阿丽卡用手指敲打自己的勃起阴蒂', '……只是一下 子刺激到位……头脑瞬间变得空白……', '之前也有感觉过……这个阴蒂小鸡鸡……会这么有感觉吗？', '快点……要射了……', '射出来吧！这个变态领主……啊……', '那么……就看着这对胸部……', '快点射出来……啊！这个！', '自己弄的时候完全没有过这种感觉']

线程ID:  1656
Error: api请求出现问题！错误信息如下
Error: Error code: 400 - {'error': {'message': "'$.input' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference.", 'type': 'invalid_request_error', 'param': None, 'code': None}}

以下是出現錯誤的文本
[TrsData12.5.json](https://github.com/NEKOparapa/AiNiee/files/14452709/TrsData12.5.json)
[TrsData9.json](https://github.com/NEKOparapa/AiNiee/files/14452710/TrsData9.json)
[TrsData8.json](https://github.com/NEKOparapa/AiNiee/files/14452711/TrsData8.json)
[TrsData11.json](https://github.com/NEKOparapa/AiNiee/files/14452712/TrsData11.json)
[TrsData6.json](https://github.com/NEKOparapa/AiNiee/files/14452713/TrsData6.json)

**Comment by NEKOparapa** [comment]
是因为有些文本翻译错了，比如：    "気を付けます……」": "……」", 发送符号过去会错误的，你是用ainiee翻译的么
