### ISSUE TITLE
可能是流式传输导致的问题？

### ISSUE THREAD

**Issue by kureinaikai** [NEKOparapa/AiNiee#110]
![photo_2024-03-02_00-27-48](https://github.com/NEKOparapa/AiNiee/assets/107994368/1abf0270-ff96-4982-bb21-e6560c4e6440)
在没有收到完整回复后就进行判断存在问题

**Comment by kureinaikai** [comment]
使用的是第三方反代

**Comment by NEKOparapa** [comment]
是的

**Comment by kureinaikai** [comment]
> 是的，不能使用流输出

但是好像设置里没有相关的开关？

**Comment by NEKOparapa** [comment]
如果是反代，有可能是碰到审查，然后自动断了输出，网页反代是这样的

**Comment by kureinaikai** [comment]
> 如果是反代，有可能是碰到审查，然后自动断了输出，网页反代是这样的

可能并不是审查的问题，我在SillyTarven这个程序上关闭流式生成是能收到完整的回复的，应该是在收到第一次响应时就被当成完整回复了？

**Comment by NEKOparapa** [comment]
那我不清楚了，软件里是默认关闭流输出的
