### ISSUE TITLE
執行問題, 進度一直為零

### ISSUE THREAD

**Issue by Fagorz107** [NEKOparapa/AiNiee#115]
[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 7.47 秒
[INFO] 本次请求与回复花费的总tokens是： 1685
[INFO] AI回复的文本内容：
 {
        "0": "設定是「卡茲瑪」。",
        "1": "名字是二宮",
        "2": "。",
        "3": "陽依　　怎麼了？",
        "4": "等一下去運動場？",
        "5": "紗代　「嗯？什麼？",
        "6": "紗代　「這裡是女廁所喔？？？",
        "7": "紗代　「　　＠　　　　老師有點噁心，請出去一下！",
        "8": "一茂津「喔？",
        "9": "噁心是什麼意思後藤！",
        "10": "紗代　「　＠　　　　有點糟糕～～～！",
        "11": "別開玩笑了該死的小鬼！！！",
        "12": "紗代　「剛剛對不起陽依～，",
        "13": "陽依　「一點都不！反倒是，紗代的男朋友和運動場＠　　　　雙重約會吧？好期待～！",
        "14": "紗代　「對呀～，＠　　　　而且兩個人都不晚嗎？",
        "15": "創太　「喂！紗代～！",
        "16": "「尼崎小姐～！",
        "17": "「遲到了對不起！",
        "18": "創太　「對不起對不起，我有點肚子痛要去廁所ｗ",
        "19": "創太　「明明今天足球部下午沒課＠　　　　時間浪費了呢ｗ"
        }

Error: 子线程运行出现问题！错误信息如下
Error: local variable 'process_info_list' referenced before assignment

[INFO] 你开启了保留换行符功能，正在进行替换

[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 1754
[INFO] 当前发送的原文文本：
 {"0": "温くて旨い。", "1": "すっかり農家になった気分だった。", "2": "尼崎さんは後藤さんとカラオケ。", "3": "最近カラオ ケが多いのはストレスでもあるのか。", "4": "陽キャの尼崎さんの事だ、そういう心配は無いだろう。", "5": "尼崎さんと早く会いたいと思いながら＠トマトをほおばる", "6": "だった。", "7": "陽依　「こんばんはー！", "8": "おばさん「いらっしゃいませー ！＠　　　　　あら竿屋先生！", "9": "一茂津「どうも、お世話になっております。", "10": "おばさん「どうぞどうぞ！", "11": "一茂津「尼崎、隣いいか？", "12": "陽依　「あ…は、はい！", "13": "一茂津「尼崎、お前ラーメンが好きなのか？", "14": "陽 依　「え…", "15": "おばさん「陽依ちゃんラーメン大好きだよねー！＠　　　　　すっかりお得意様ですよー！", "16": "一茂津「そうか尼崎、ラーメン好きな女性はいいと思うぞ。", "17": "陽依　「竿屋先生……", "18": "一茂津「ようし尼崎、＠　　　　先生のオススメラーメンを奢ってやろう。", "19": "一茂津「トマトラーメン二つお願いします。"}
[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 1272
[INFO] 当前发送的原文文本：
 {"0": "駄菓子代用イベ４", "1": "日にち決定コマンド", "2": "乙葉掃除輪姦", "3": "エンド１", "4": "エンド２", "5": "エン ド３", "6": "選択７３０火１", "7": "選択７３１水１", "8": "乙葉掃除輪姦２", "9": "ピクチャボタン", "10": "ピクチャプラグイン", "11": "授業選択", "12": "日曜の竿屋８月４日", "13": "イベバックSA１セックス４", "14": "バックSアニメ通常１", "15": "バックSアニメ通常１速", "16": "イキ１", "17": "バックSアニメ通常２", "18": "バックSアニメ通常２速", "19": "イキ２"}

[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 7.11 秒
[INFO] 本次请求与回复花费的总tokens是： 1682
[INFO] AI回复的文本内容：
 {
        "0": "紗代　「創太，別這樣啦～！",
        "1": "陽依　（好羨慕…我也",
        "2": "紗代　「……",
        "3": "紗代　「最近我喜歡這個東西喔？",
        "4": "陽依　「啊～是糖果嗎～？",
        "5": "紗代　「欸～陽依討厭嗎～？",
        "6": "陽依　「我不喜歡那包裝紙啦～，",
        "7": "紗代　「啊～我懂～哈哈",
        "8": "創太　「那個像橡皮一樣不好吃啊！",
        "9": "紗代　「創太好噁心ｗｗｗ",
        "10": "創太　「我又沒說避孕套的事啊！",
        "11": "陽依　「哈哈哈ｗｗ",
        "12": "創太　「啊，糟糕…得趕快回去了！",
        "13": "紗代　「那麼，我們去街上逛逛吧～？",
        "14": "陽依　「好啊～！",
        "15": "一茂津「嘻嘻……和尼崎做愛了…",
        "16": "一茂津「只要想起尼崎的感覺，就停不下來勃起…",
        "17": "一茂津「……尼崎的陰道肉的味道……",
        "18": "一茂津「尼崎太棒了…。"
        }

Warning: AI回复内容存在问题: AI回复内容文本行数与原来数量不符合,将进行重新翻译

[DEBUG] 总行数： 8662 已翻译行数： 0 进度： 0.0 %
Warning: AI回复内容格式错误次数: 1 到达2次后将该段文本进行拆分翻译

Error: 子线程运行出现问题！错误信息如下
Error: local variable 'process_info_list' referenced before assignment

Error不斷出現, 完全零進度, 緩存也沒有任何東西
請問可以如何解決? 感謝

**Comment by NEKOparapa** [comment]
复制代码时，少了东西....最新版修了....
