### ISSUE TITLE
stevextraction翻译问题

### ISSUE THREAD

**Issue by MoFan13** [NEKOparapa/AiNiee#117]
好像把一些不该翻译的文件也翻译了?有办法解决吗?
![屏幕截图 2024-03-15 231128](https://github.com/NEKOparapa/AiNiee/assets/85187498/94683136-8938-42c0-b860-a92fa48ca73c)
![屏幕截图 2024-03-15 231848](https://github.com/NEKOparapa/AiNiee/assets/85187498/2c22bd6d-97d7-4185-a180-0cc9ef072790)

**Comment by NEKOparapa** [comment]
@stevetrs 英雄召唤

**Comment by stevetrs** [comment]
不好说，看起来像是翻译文件名的问题，但是文件名注入的时候会自动处理才对
把原版游戏和翻译文件都给我发过来看看吧，不确定能不能解决

**Comment by MoFan13** [comment]
> 不好说，看起来像是翻译文件名的问题，但是文件名注入的时候会自动处理才对 把原版游戏和翻译文件都给我发过来看看吧，不确定能不能解决

https://gofile.io/d/kRzZWr这是文件,感谢帮忙

**Comment by stevetrs** [comment]
[data.zip](https://github.com/NEKOparapa/AiNiee/files/14623187/data.zip)

至少能进游戏了，有没有其他问题我不确定

问题有两点：
1.注入游戏的时候要选到游戏根目录，你应该是选错了，导致处理文件名的函数没起作用。你截图的报错就是因为这个
2.处理掉上面的问题后又出现其他报错了，需要在config.yaml中的BlackDir里添加几个新的黑名单地址。这一点我不确定是所有非日语游戏共同的，还是这个游戏独有的。


@NEKOparapa 要不把日语游戏那个选项焊死吧。至少目前来看jtpp不适合用来处理非日语游戏，我也不玩这些游戏，懒得去一个个排除都哪些地址不能翻译了。非日语游戏用mtool和t++可能会更好点

**Comment by MoFan13** [comment]
> [data.zip](https://github.com/NEKOparapa/AiNiee/files/14623187/data.zip)
> 
> 至少能进游戏了，有没有其他问题我不确定
> 
> 问题有两点： 1.注入游戏的时候要选到游戏根目录，你应该是选错了，导致处理文件名的函数没起作用。你截图的报错就是因为这个 2.处理掉上面的问题后又出现其他报错了，需要在config.yaml中的BlackDir里添加几个新的黑名单地址。这一点我不确定是所有非日语游戏共同的，还是这个游戏独有的。
> 
> @NEKOparapa 要不把日语游戏那个选项焊死吧。至少目前来看jtpp不适合用来处理非日语游戏，我也不玩这些游戏，懒得去一个个排除都哪些地址不能翻译了。非日语游戏用mtool和t++可能会更好点

好的,感谢感谢

**Comment by NEKOparapa** [comment]
> [data.zip](https://github.com/NEKOparapa/AiNiee/files/14623187/data.zip)
> 
> 至少能进游戏了，有没有其他问题我不确定
> 
> 问题有两点： 1.注入游戏的时候要选到游戏根目录，你应该是选错了，导致处理文件名的函数没起作用。你截图的报错就是因为这个 2.处理掉上面的问题后又出现其他报错了，需要在config.yaml中的BlackDir里添加几个新的黑名单地址。这一点我不确定是所有非日语游戏共同的，还是这个游戏独有的。
> 
> @NEKOparapa 要不把日语游戏那个选项焊死吧。至少目前来看jtpp不适合用来处理非日语游戏，我也不玩这些游戏，懒得去一个个排除都哪些地址不能翻译了。非日语游戏用mtool和t++可能会更好点

可以
