### ISSUE TITLE
是否可以加入可选的开关高频词检测功能呢？

### ISSUE THREAD

**Issue by nekomiya-hinata** [NEKOparapa/AiNiee#121]
如题，有时候原文确实是有很多类似/相同的语气词，可否加入一个控制的开关呢？

**Comment by NEKOparapa** [comment]
这个功能是检查模型退化的，一般来说是不会检测到，你可以提供一下原文文件么

**Comment by nekomiya-hinata** [comment]
这个是其中的一小部分

[file.json](https://github.com/NEKOparapa/AiNiee/files/14640575/file.json)

**Comment by NEKOparapa** [comment]
我测试了一下，没有出现你的情况，也有可能因为线程多，日志显示混乱。如果出现这个问题，可以这样来解决，文本行数调到20左右，或者调高实时调教里的频率惩罚

**Comment by nekomiya-hinata** [comment]
好的，我之后有其他游戏了再试试
