### ISSUE TITLE
存在api key測試失敗

### ISSUE THREAD

**Issue by paul0728** [NEKOparapa/AiNiee#122]
如題,我創了好幾個api key  測試都失敗,請問該如何解決?

**Comment by NEKOparapa** [comment]
你可以看看黑框窗口显示什么，会有说明

**Comment by paul0728** [comment]
![螢幕擷取畫面 2024-03-20 001256](https://github.com/NEKOparapa/AiNiee/assets/44644609/46163fb5-1962-43ee-a99c-f93a5911123a)
但是這說明也看不出原因

**Comment by paul0728** [comment]
謝謝回覆,後來發現是credit balance不足,加值就測試成功。可是實際拿遊戲翻譯卻遇到此錯誤
![螢幕擷取畫面 2024-03-20 003700](https://github.com/NEKOparapa/AiNiee/assets/44644609/8ac2412a-f204-4f3d-b59f-e7832d10a486)

**Comment by NEKOparapa** [comment]
免费账号不支持gpt4

**Comment by paul0728** [comment]
了解,但是第二次執行時遇到此問題
![image](https://github.com/NEKOparapa/AiNiee/assets/44644609/63839e53-6e2a-4258-bb37-f3dcb92e625d)
同個資料夾下只有ManualTransFile 和 mtoolPathLogger
就算移除mtoolPathLogger還是解決不了

**Comment by NEKOparapa** [comment]
你看一下文字教程，再看一下视频教程
