### ISSUE TITLE
怎么使用SakuraLLM配置:  1.Kaggle云平台方法？

### ISSUE THREAD

**Issue by 123456ds** [NEKOparapa/AiNiee#126]
`点击后，log的第一行会出现一个address：xxxx，将后面的链接复制出来。`
请求地址填写的是这里的地址，但AiNiee测试失败。
使用轻小说机翻机器人网站的Sakura工作区却 可以通过测试.
![屏幕截图 2024-03-22 105000.png](https://sunky.top/i/2024/03/22/65fcf33ac2401.png)
`
[INFO] 模型通讯测试失败！！！！
[INFO] 模型地址是: https://1111.ngrok-free.app//v1

[INFO] 模型选择是: Sakura-13B-LNovel-v0.9

[INFO] 当前发送内容：
 [{'role': 'system', 'content': '你是一个轻小说翻译模型，可以流畅通顺地以日本轻小说的风格将日文翻译成简体中文，并联系上 下文正确使用人称代词，不擅自添加原文中没有的代词。'}, {'role': 'user', 'content': '将下面的日文文本翻译成中文：サポート キャスト'}]

Error: 请求出现问题！错误信息如下
Error: Connection error.

[INFO] 模型通讯测试失败！！！！`

**Comment by NEKOparapa** [comment]
把//v1去掉

**Comment by 123456ds** [comment]
> 把//v1去掉
谢谢提示，原来是多了给/啊..
