### ISSUE TITLE
希望增加对传统机器翻译的支持

### ISSUE THREAD

**Issue by safasfcdasfdc** [NEKOparapa/AiNiee#127]
AI翻译太慢了，得挂机好久，api额度也消耗得很快。希望增加对传统机器翻译的支持
Mtool与Translator++的免费版本只能使用bing翻译，翻译结果太差，且只能赞助作者才可以使用作者提供的API，想使用自己的api接口都做不到。

**Comment by nekomiya-hinata** [comment]
这样的话好像与这个项目的定义**AI翻译**有一些冲突

传统翻译的话让gpt帮你生成python代码调用也不是不行（

**Comment by NEKOparapa** [comment]
不会增加的，很多功能都是围绕AI设计的，而且质量也比不上AI

**Comment by 123456ds** [comment]
下面的AI输出的PY脚本：
使用的彩云小译https://platform.caiyunapp.com/api

`import json
import requests
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
from threading import Thread
from queue import Queue
import os
import time

# 彩云小译API的URL和Token
URL = "http://api.interpreter.caiyunai.com/v1/translator"
TOKEN = "YOUR_TOKEN"  # 请替换为你的token

# 翻译函数
def translate(text):
    payload = {
        "source": text,
        "trans_type": "ja2zh",  # 指定翻译类型，例如这里是日语到中文
        "request_id": "demo",
        "detect": True,
    }
    headers = {
        "content-type": "application/json",
        "x-authorization": "token " + TOKEN,
    }
    response = requests.post(URL, data=json.dumps(payload), headers=headers)
    result = response.json()
    if "target" in result:
        return result["target"]
    else:
        return None

# 进度更新函数
def update_progress(percentage):
    progress_bar.set(percentage)
    root.update()

# 日志记录函数
def log_message(message):
    with open('log.txt', 'a', encoding='utf-8') as f:
        f.write(message + '\n')

# 处理文件的函数
def process_file(file_path, queue):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        total_lines = len(data)
        translated_lines = 0
        for key, value in data.items():
            if value.startswith('\"'):
                # 发送到彩云小译API进行翻译
                translated_text = translate(value[1:-1])  # 去除双引号
                if translated_text:
                    data[key] = '\"' + translated_text + '\"'
                    translated_lines += 1
                    percentage = (translated_lines / total_lines) * 100
                    if percentage % 10 == 0:
                        update_progress(int(percentage))
                        log_message(f"Processed {translated_lines}/{total_lines} lines. Translation progress: {percentage:.2f}%")
        # 另存为json文件
        with open(file_path + '.translated.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        update_progress(100)
        log_message(f"File processed and saved as '{file_path}.translated.json'")

# 用户界面
root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename(title="选择需要处理的ManualTransFile.json文件", filetypes=[("JSON文件", "*.json")])
if file_path:
    log_message(f"Selected file: {file_path}")
    queue = Queue()
    queue.put(file_path)
    root.protocol("WM_DELETE_WINDOW", lambda: ask_exit(queue))
    root.mainloop()
else:
    print("没有选择文件。")

# 退出确认函数
def ask_exit(queue):
    if messagebox.askyesno("退出", "确定要退出吗？"):
        root.destroy()
    else:
        pass

# 主线程
def main():
    if not queue.empty():
        file_path = queue.get()
        process_file(file_path, queue)

if __name__ == "__main__":
    main()`


> AI翻译太慢了，得挂机好久，api额度也消耗得很快。希望增加对传统机器翻译的支持 Mtool与Translator++的免费版本只能使用bing翻译，翻译结果太差，且只能赞助作者才可以使用作者提供的API，想使用自己的api接口都做不到。

**Comment by 123456ds** [comment]
你可以搜索由AI生成的脚本：

import json
import requests
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
from threading import Thread
from queue import Queue
import os
import time

# 彩云小译API的URL和Token
URL = "http://api.interpreter.caiyunai.com/v1/translator"
TOKEN = "YOUR_TOKEN"  # 请替换为你的token

# 翻译函数
def translate(text):
    payload = {
        "source": text,
        "trans_type": "ja2zh",  # 指定翻译类型，例如这里是日语到中文
        "request_id": "demo",
        "detect": True,
    }
    headers = {
        "content-type": "application/json",
        "x-authorization": "token " + TOKEN,
    }
    response = requests.post(URL, data=json.dumps(payload), headers=headers)
    result = response.json()
    if "target" in result:
        return result["target"]
    else:
        return None

# 进度更新函数
def update_progress(percentage):
    progress_bar.set(percentage)
    root.update()

# 日志记录函数
def log_message(message):
    with open('log.txt', 'a', encoding='utf-8') as f:
        f.write(message + '\n')

# 处理文件的函数
def process_file(file_path, queue):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        total_lines = len(data)
        translated_lines = 0
        for key, value in data.items():
            if value.startswith('\"'):
                # 发送到彩云小译API进行翻译
                translated_text = translate(value[1:-1])  # 去除双引号
                if translated_text:
                    data[key] = '\"' + translated_text + '\"'
                    translated_lines += 1
                    percentage = (translated_lines / total_lines) * 100
                    if percentage % 10 == 0:
                        update_progress(int(percentage))
                        log_message(f"Processed {translated_lines}/{total_lines} lines. Translation progress: {percentage:.2f}%")
        # 另存为json文件
        with open(file_path + '.translated.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        update_progress(100)
        log_message(f"File processed and saved as '{file_path}.translated.json'")

# 用户界面
root = tk.Tk()
root.withdraw()
file_path = filedialog.askopenfilename(title="选择需要处理的ManualTransFile.json文件", filetypes=[("JSON文件", "*.json")])
if file_path:
    log_message(f"Selected file: {file_path}")
    queue = Queue()
    queue.put(file_path)
    root.protocol("WM_DELETE_WINDOW", lambda: ask_exit(queue))
    root.mainloop()
else:
    print("没有选择文件。")

# 退出确认函数
def ask_exit(queue):
    if messagebox.askyesno("退出", "确定要退出吗？"):
        root.destroy()
    else:
        pass

# 主线程
def main():
    if not queue.empty():
        file_path = queue.get()
        process_file(file_path, queue)

if __name__ == "__main__":
    main()
