### ISSUE TITLE
有个在翻译时的想法

### ISSUE THREAD

**Issue by nekomiya-hinata** [NEKOparapa/AiNiee#129]
是否可以改进一下现在的提示词，在翻译的时候在提示词中带上一部分的上文，这样翻译出来的上下文的连贯性或许会更好？
同时支持带入的上文行数也可以自己配置，不知道这样行不行呢？

**Comment by NEKOparapa** [comment]
额，如果希望连贯性更好，可以调高文本行数，没必要添加上下文

**Comment by nekomiya-hinata** [comment]
主要是调高行数的话，可能回复不了这么多文字吧，而且格式也容易出错，这样的话相当于是一个拓展？

**Comment by NEKOparapa** [comment]
实现其功能会影响现有功能的运行，暂不会考虑

**Comment by nekomiya-hinata** [comment]
了解了
