### ISSUE TITLE
使用Sakura模型進行翻譯出現數量錯誤是否可以直接拆分或提供設定開關

### ISSUE THREAD

**Issue by FishYu-htps** [NEKOparapa/AiNiee#131]
目前在使用Sakura模型時，當AI回覆的文本出現數量錯誤時，
第二次嘗試幾乎大概率還是錯誤的
是否可以提供開關，不重試直接進行拆分

**Comment by NEKOparapa** [comment]
用最新版的混合翻译功能，里面可以设置，首轮设置Sakura，其他不设置或者Sakura
