### ISSUE TITLE
缓存行号text_index太严格了，删了一行以后作为源文件任务无法停止

### ISSUE THREAD

**Issue by fatecyx** [NEKOparapa/AiNiee#132]
起因是有“禁|きん”这样的文本，放进翻译里会扰乱上下的翻译结果，又不知道怎么过滤掉
然后上个版本有bug导不出中间结果，跑了一大半又不想重跑
于是把缓存文件里里的这种文本的dict删掉之后作为任务了
结果发现翻译任务是无法停止的，会无限跑下去

举个例子，中间选了一行删掉，日志如下：

[INFO]  文本总行数为： 2   需要翻译的行数为： 2
[INFO]  每次发送行数为： 10   计划的翻译任务总数是： 1

[INFO]  五秒后开始进行翻译，请注意保持网络通畅，余额充足。

[INFO] 正在使用SakuraLLM，将替换换行符为特殊符号

[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 148
[INFO] 当前发送的原文文本：
 は先手を取った！
は戦いに敗れた。

[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 2.83 秒
[INFO] 本次请求与回复花费的总tokens是： 97
[INFO] AI回复的文本内容：
 先发制人！
败下阵来。

[DEBUG] 总行数： 2 已翻译行数： 2 进度： 100.0 %

--------------------------------------------------------------------------------------

Success: AI回复内容检查通过！！！已翻译完成100.0%

--------------------------------------------------------------------------------------

Warning: 仍然有部分未翻译，将进行拆分后重新翻译，-----------------------------------
[INFO] 当前拆分翻译轮次： 1  到达最大轮次：6 时，将停止翻译
[INFO] 未翻译文本总行数为： 1   每次发送行数修改为： 5

[INFO] 正在使用SakuraLLM，将替换换行符为特殊符号

[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 130
[INFO] 当前发送的原文文本：
 は戦いに敗れた。

[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 2.57 秒
[INFO] 本次请求与回复花费的总tokens是： 82
[INFO] AI回复的文本内容：
 败战了。

[DEBUG] 总行数： 2 已翻译行数： 3 进度： 150.0 %

--------------------------------------------------------------------------------------

Success: AI回复内容检查通过！！！已翻译完成150.0%

--------------------------------------------------------------------------------------

**Comment by NEKOparapa** [comment]
你把翻译状态改为7就行，程序就会忽略。你删了一行，序号会打乱，当然一堆bug

**Comment by NEKOparapa** [comment]
现在你得复原原来那个序号的缓存内容，然后翻译状态改为7，程序会忽略翻译，改为1，是表示已翻译成功，程序也会忽略

**Comment by fatecyx** [comment]
我知道这确实是我的疏忽，但要看代码我才知道改哪个状态码
这个读取的时候重新编号就行了
主要问题是全程完全不报错，最后跑了半天发现缓存都不变的

**Comment by NEKOparapa** [comment]
额，不会重新编号的，因为要保留关于原文本的全部信息，没有必要还是不要动翻译缓存

**Comment by fatecyx** [comment]
那考虑下缓存写失败的时候报个错？我觉得这个才是主要原因

**Comment by NEKOparapa** [comment]
可以考虑，不过得了解用户在哪种情况下出现问题

**Comment by fatecyx** [comment]
我这种应该是5390行  cache_data[text_index]['text_index'] == text_index:不等于的情况
不过似乎只要response_value 存在但没有对cache_data进行修改，都可以算出错了吧
