### ISSUE TITLE
谷歌官方平台调用错误

### ISSUE THREAD

**Issue by VFengChen** [NEKOparapa/AiNiee#134]
配置好API后点测试后台出现以下信息.
请求出现问题！错误信息如下
Error: Timeout of 60.0s exceeded, last exception: 503 failed to connect to all addresses;
后搜索了下网上说是以下原因:
![image](https://github.com/NEKOparapa/AiNiee/assets/77783848/684eb961-ae6d-4089-9a3e-a8a148ede807)
请问怎么解决

**Comment by NEKOparapa** [comment]
换台湾地区代理
