### ISSUE TITLE
关于暂停和继续的问题

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#136]
使用远程部署的SakuraLLM翻译mtool文件，大概3万多行，由于远程SakuraLLM服务经常挂掉，所以翻译只能暂停和继续。我发现暂停和继续功能存在问题
1、暂停和继续时很容易卡死
2、暂停看起来不像真的“暂停”，而是会从头开始翻译。例如：已翻译到1000行，中间第100-120行翻译失败了，此时远程SakuraLLM服务挂了，让翻译暂停，修复SakuraLLM服务，然后让翻译继续，发现会从100行那里继续翻译。期望从1000行那里继续。建议使用一种单独的状态标识已翻译但失败的文本，在第一次翻译时（或继续翻译）跳过这些文本
3、在翻译设置-> 混合翻译设置 -> 错误重翻最大次数限制，设置为0（SakuraLLM模型重试多次都会失败，所以没必要重试），但是在翻译时还是会重试1次

关于第2个问题，可能是继续时，使用的输入文件还是之前的文件。也就是说，缓存文件作为输入文件时，需要开启“自动备份缓存文件到输出文件夹”，在翻译时暂停翻译或取消后，如果想要继续翻译，需要将输出文件夹的缓存文件重新作为输入文件，比较麻烦。但是缓存文件作为一种中间状态的记录文件，在翻译时，将翻译结果实时更新到输入的缓存文件更合理一点
感觉还是缺少任务的状态记录文件，可以参考这个exe小工具，它有个简单的config文件记录上次翻译的行数：https://github.com/fkiliver/RPGMaker_LLM_Translator

**Comment by NEKOparapa** [comment]
暂停和继续时很容易卡死，如果不是电脑本身性能问题，那就是在暂停时，要等待每一个子线程退出，而子线程在等接口回应后才能退出，所以导致要等很久。我现在还不清楚怎么取消子线程的接口回应等待，也不能马上杀死所有的子线程，怕会出现bug，如果你清楚可以告诉我。

**Comment by NEKOparapa** [comment]
是的，不是真“暂停”，而是会从头开始翻译。你的建议我会考虑如何实现

**Comment by NEKOparapa** [comment]
错误重翻最大次数限制，需要开启混合翻译开关才能生效，你可以设置首轮为Sakura，其余不设置。我看看要不要把它放在进阶设置了吧
