### ISSUE TITLE
提建議: 在緩存文件中記錄該條翻譯使用的平台或模型，以及將最後沒有成功翻譯的項目紀錄產生另一個文件

### ISSUE THREAD

**Issue by FishYu-htps** [NEKOparapa/AiNiee#137]
在進行翻譯時，有時會用到多個平台多個模型
像是某個模型中間卡住時，有時會手動更換模型
不知道可不可以在緩存文件中，紀錄那條翻譯出自哪個模型，方便後續追蹤以及了解模型翻譯的特色
以及若最後在多輪重試完仍沒有完成翻譯，將這些翻譯失敗的項目單獨產生一個文件

**Comment by NEKOparapa** [comment]
“在多輪重試完仍沒有完成翻譯，將這些翻譯失敗的項目單獨產生一個文件 ”
这个是已经有的功能
“在緩存文件中，紀錄那條翻譯出自哪個模型”
最新版已经支持

**Comment by FishYu-htps** [comment]
@NEKOparapa 想請問紀錄翻譯失敗的文件會存放在哪個目錄，我好像沒有看到
是否可以給一個選項一併放到緩存資料夾中

**Comment by NEKOparapa** [comment]
输出文件夹，不支持
