### ISSUE TITLE
api測試正常但翻譯時時常顯示連線錯誤

### ISSUE THREAD

**Issue by zhainanyige8** [NEKOparapa/AiNiee#142]
如題，我用gemini進行翻譯，但途中總是顯示
Error: 进行请求时出现问题！！！错误信息如下
Error: Connection error.

**Comment by zhainanyige8** [comment]
就是台灣的，也沒掛vpn，之前出錯隔了幾天用也是一樣

**Comment by NEKOparapa** [comment]
不太清楚了，我这边可以正常使用

**Comment by zx3777** [comment]
设置里没有选择google作为服务商
