### ISSUE TITLE
Gemini 翻译报错

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#144]
版本4.66.3
1、使用Sakura翻译mtool导出文件，翻译了一部分
2、继续使用Gemini（API测试正常）翻译缓存文件，结果报错了
```
Error: 子线程运行出现问题！错误信息如下
Error: local variable 'glossary_prompt' referenced before assignment
```
3、测试使用Sakura翻译缓存文件是正常的。
缓存文件已上传
[AinieeCacheData.json](https://github.com/NEKOparapa/AiNiee/files/14957105/AinieeCacheData.json)

**Comment by NEKOparapa** [comment]
测试版已修
