### ISSUE TITLE
[请求增加功能]增加不同代理平台的切换功能

### ISSUE THREAD

**Issue by aioi50** [NEKOparapa/AiNiee#146]
请求在代理平台设置界面增加不同代理平台的保存切换功能，目前代理平台很多，有时候需要使用其他代理平台必须删除目前正在使用的，如果新的不好用又要重新填写旧代理平台，感觉有点麻烦，感谢

**Comment by wsndshx** [comment]
感觉可以在代理平台里面引入一个 TableWidget 控件，每一行就是一个代理，左边也能加上序号。

这样后面选择代理平台的时候可以用 `代理平台 0` `代理平台 1` `代理平台 2` ......

不过这样的话会缺乏下拉选项，对于一些项目（例如请求格式）可能需要引入内容检查，避免输入软件中不存在的平台。

（虽然目前我接触较多的代理平台都是兼容openai接口，模型选择里面再传入需要使用的模型）

~~或者是考虑支持启动时读取特定配置文件中的代理平台信息，这样就可以跳过UI设计了~~

**Comment by NEKOparapa** [comment]
> 感觉可以在代理平台里面引入一个 TableWidget 控件，每一行就是一个代理，左边也能加上序号。
> 
> 这样后面选择代理平台的时候可以用 `代理平台 0` `代理平台 1` `代理平台 2` ......
> 
> 不过这样的话会缺乏下拉选项，对于一些项目（例如请求格式）可能需要引入内容检查，避免输入软件中不存在的平台。
> 
> （虽然目前我接触较多的代理平台都是兼容openai接口，模型选择里面再传入需要使用的模型）
> 
> ~或者是考虑支持启动时读取特定配置文件中的代理平台信息，这样就可以跳过UI设计了~

其实受制比较大的一个原因是，这个风格化的UI库没有合适的控件，而且大概率不会更新更多控件了，因为作者搞收费闭源了，如果要用新控件，软件得闭源。只能在原有的控件进行组合编写，或者自己写一个新控件

**Comment by zx3777** [comment]
> > 感觉可以在代理平台里面引入一个 TableWidget 控件，每一行就是一个代理，左边也能加上序号。
> > 这样后面选择代理平台的时候可以用 `代理平台 0` `代理平台 1` `代理平台 2` ......
> > 不过这样的话会缺乏下拉选项，对于一些项目（例如请求格式）可能需要引入内容检查，避免输入软件中不存在的平台。
> > （虽然目前我接触较多的代理平台都是兼容openai接口，模型选择里面再传入需要使用的模型）
> > ~或者是考虑支持启动时读取特定配置文件中的代理平台信息，这样就可以跳过UI设计了~
> 
> 其实受制比较大的一个原因是，这个风格化的UI库没有合适的控件，而且大概率不会更新更多控件了，因为作者搞收费闭源了，如果要用新控件，软件得闭源。只能在原有的控件进行组合编写，或者自己写一个新控件

现在代理平台的温度不能设置吗？参数设置里的gpt和claude温度会影响相应请求格式代理平台的温度吗？

**Comment by NEKOparapa** [comment]
测试版已加

**Comment by aioi50** [comment]
> 测试版已加

辛苦了大佬
