### ISSUE TITLE
[Bug]有关转义字符翻译的问题

### ISSUE THREAD

**Issue by LuoTat** [NEKOparapa/AiNiee#147]
这个是原始的json文件
```
{
  "Hello": "Hello",
  "Hello\\V": "Hello\\V",
  "Hello\n": "Hello\n",
  "Hello\\": "Hello\\"
}
```
这个是Log
```
[INFO]  五秒后开始进行翻译，请注意保持网络通畅，余额充足。 

[INFO] 已发送请求,正在等待AI回复中-----------------------
[INFO] 请求与回复的tokens数预计值是： 633
[INFO] 当前发送的原文文本：
 {"0": "Hello", "1": "Hello\\V", "2": "Hello\n", "3": "Hello\\"}


[INFO] 已成功接受到AI的回复-----------------------
[INFO] 该次请求已消耗等待时间： 16.8 秒
[INFO] 本次请求与回复花费的总tokens是： 646
[INFO] AI回复的文本内容：
 {
"0": "你好",
"1": "你好\V",
"2": "你好\n",
"3": "你好\\"
} 
```
这里的
```
 {
"0": "你好",
"1": "你好\V",
"2": "你好\n",
"3": "你好\\"
}
```
回复格式就有一些问题
有一些字符串转义了有一些却没有
按理说JSON文件读取一次，输出一次转义字符应该保持不变才对

另外我看了一下Issues里面的其它的几个问题好像也是在提到格式的问题
不知道是不是我说的这个转义的问题，因为我也搞不懂GPT翻译有一些转义字符的字符串难道很困难吗
当然如果这个问题确实是GPT翻译本身导致的就当我没说

**Comment by NEKOparapa** [comment]
是的，AI对特殊字符，转义字符其实并不能很好的保留，经常吞

**Comment by LuoTat** [comment]
> 是的，AI对特殊字符，转义字符其实并不能很好的保留，经常吞。即使在prompt强调了，但依然没有太多作用，还得靠模型自身的能力

好的多谢回答，不过我有个想法，前面的许多讨论都集中于如何在翻译前处理好这些转义字符或者特殊字符。可不可以在翻译完后对翻译后的文本进行一次修正。
当然我也不清楚这些个特殊字符所带来的问题到底有哪些，有多严重。我也只是看到了转义字符这个问题而已，如果单单是这个问题的话，我估计应该还可以处理，就是不知道那些更复杂的情况还行不行了。

**Comment by NEKOparapa** [comment]
ai翻译的文本并不是严格按照之前的原文来分句，比如原文是：我吃了一个西瓜，在今天下午。AI可能会翻译成：在今天下午我吃了一个西瓜。
出现这种问题时，目前可行的方法就，在发送前分句，在逗号或者换行符处，将一句话分为几句话发送翻译，之后再组合回来。
又或者，在翻译后，按照字数进行强行插入换行符。

**Comment by jeshs** [comment]
可以考虑翻译前处理
假如原文是：我吃了ABC一个，\n[a1]大西瓜\\v
拆分成3段分别翻译：我吃了、一个、大西瓜
然后将翻译后的结果和特殊字符拼凑起来，虽然顺序可能不对，但还是值得一试，因为中文的顺序不影响阅读，但是特殊符号出问题往往是大问题，可以考虑做成设置项

**Comment by NEKOparapa** [comment]
> 可以考虑翻译前处理 假如原文是：我吃了ABC一个，\n[a1]大西瓜\v 拆分成3段分别翻译：我吃了、一个、大西瓜 然后将翻译后的结果和特殊字符拼凑起来，虽然顺序可能不对，但还是值得一试，因为中文的顺序不影响阅读，但是特殊符号出问题往往是大问题，可以考虑做成设置项

特殊字符怎么找，这是一个难题，/n/s这些还好，像[a1]，///F，///G这些，在英文语境下又该怎么找？又或者让用户自己填特殊字符？还需要一些想法与建议

**Comment by jeshs** [comment]
> > 可以考虑翻译前处理 假如原文是：我吃了ABC一个，\n[a1]大西瓜\v 拆分成3段分别翻译：我吃了、一个、大西瓜 然后将翻译后的结果和特殊字符拼凑起来，虽然顺序可能不对，但还是值得一试，因为中文的顺序不影响阅读，但是特殊符号出问题往往是大问题，可以考虑做成设置项
> 
> 特殊字符怎么找，这是一个难题，/n/s这些还好，像[a1]，///F，///G这些，在英文语境下又该怎么找？又或者让用户自己填特殊字符？还需要一些想法与建议

想了下，可以用白名单正则表达式，不同的语言使用不同的正则。需要较强的正则表达式编写能力
下面是借助GPT4的回答

日文:
1. 汉字（漢字 / かんじ）：采用中文汉字的日文写法，有时可能出现相同汉字在中日两种语言中意义不同的情况。
2. 平假名（ひらがな）：用于表示本来的日语词汇、语尾变化以及作为汉字读音（读み仮名）。
3. 片假名（カタカナ）：主要用于表示外来词、生物分类学术语、强调词语以及代替汉字和平假名书写的词语等。
4. 数字：包括阿拉伯数字（1, 2, 3...）和日文数字（一、二、三...）。
5. 标点符号：日文中的标点符号，如句号（。 - “丸点”或“まる”）、逗号（、 - “逗点”或“とうてん”）、引号（「」、“”）、冒号（：）、分号（；）、破折号（ー）等。
6. 特殊符号：日元符号（¥）、度号（°）、书名号（《 》）等。
7. 罗马字（ローマじ）：即拉丁字母，用于表达日文拼音、缩写以及引入的外来词汇。
8. 空格和换行：通常日文文本中使用的较少，但在计算机处理的文本中可能会出现空格（）和换行（n）等空白字符。
9. 拼音符号：日文字母可能会带有拼音符号，如长音符号（ー）、拗音符号（ゃ ゅ ょ）、促音符号（っ）。

英文：
1. 单词
2. 英文标点符号：逗号（,）、句号（.）、问号（?）、感叹号（!）、引号（' "）、括号（( )）、冒号（:）、分号（;）以及破折号（- 和 —）
3. 连字符和撇号：常用于复合词（mother-in-law）、缩写词和所有格（don't、it's、John's）

下面是GPT4的回答，不知道对不对

问题：我需要翻译英文游戏文本，但是文本中夹杂了各种特殊字符、转义字符、自定义字符，而且特殊字符、转义字符、自定义字符的分布是不规则的。我需要使用python提取英文部分，然后翻译成中文，最后将翻译后的内容和特殊字符按照原来的顺序拼接，以保证游戏正常运行，怎么做？提取的英文部分包含下列内容：
1. 单词
2. 英文标点符号：逗号（,）、句号（.）、问号（?）、感叹号（!）、引号（' "）、括号（( )）、冒号（:）、分号（;）以及破折号（- 和 —）
3. 连字符和撇号：常用于复合词（mother-in-law）、缩写词和所有格（don't、it's、John's）

回答：为了解决这个问题，我们可以在Python中使用正则表达式。正则表达式是一个非常强大的工具，能够识别和提取特定模式的字符串。在这个场景中，我们希望提取所有的英文单词、英文标点符号以及连字符和撇号。

以下是一个示例代码，它可能帮助你开始这项工作：

import re

def extract_and_translate(text):
    # 定义一个正则表达式来找寻单词，英语标点，连字符和撇号
    english_pattern = re.compile(r"[a-zA-Z0-9.,?!'"():;—-]+|s*(?:-s*)+")
    
    # 使用正则表达式提取所有英文部分，忽略特殊/转义/自定义字符
    english_parts = english_pattern.findall(text)
    
    # 按需翻译所提取的英文部分到中文。这里需要假设一个translate_to_chinese函数存在。
    translated_parts = [translate_to_chinese(part) for part in english_parts]
    
    # 将翻译后的中文部分和特殊字符按照原顺序拼接起来
    # 你需要有一个方法来插入原有的特殊字符到翻译后的文本中。
    # 这个地方可以是一个复杂的任务，取决于特殊字符和英文文本之间的原始关系。
    final_text = combine_translated_with_special_chars(translated_parts, text)
    
    return final_text

# 这个假设函数需要根据你的实际情况来实现翻译
def translate_to_chinese(english_text):
    # 实现翻译逻辑或调用翻译API
    chinese_text = '假设这里是翻译后的文本'
    return chinese_text

# 这个假设函数需要根据你的实际情况来组合翻译文本和特殊字符
def combine_translated_with_special_chars(translated_parts, original_text):
    # 实现组合逻辑
    final_text = original_text  # 这只是一个示例占位符
    return final_text

# 假设的游戏文本
game_text = "Here is some English text with special characters: n, t, [custom], etc."

# 进行提取、翻译和组合
translated_game_text = extract_and_translate(game_text)
print(translated_game_text)

需要注意的是，这个解决方案是概念性的，translate_to_chinese 和 combine_translated_with_special_chars 函数需要你根据具体需求来实现。如果你需要对特殊字符执行更复杂的处理，你可能需要更复杂的逻辑来确保它们被正确保留和插回翻译后的文本。此外，你可能需要调用一个实际的翻译服务API来获取准确的翻译。
