### ISSUE TITLE
使用说明里好像有一点歧义......

### ISSUE THREAD

**Issue by wusking** [NEKOparapa/AiNiee#148]
使用SakuraLLM的教程里写的是“部署好模型后，获取接口地址，如：[http://127.0.0.1:6006，填入请求地址栏中，注意，接口地址中不要包含`/v1`，否则会报错]”
不知道是不是我个人理解能力问题，总之我以为没/v1就行了但还是报错。后面发现是最后不能有斜杠‘/‘（捂脸）

**Comment by NEKOparapa** [comment]
都不能有
