### ISSUE TITLE
SakulaLLM能增加并行处理功能吗？同一个api的并行或者不同api的并行

### ISSUE THREAD

**Issue by lisna00z** [NEKOparapa/AiNiee#149]

**Comment by NEKOparapa** [comment]
本身是可以并行的，只不过一般情况都是单线程运行，所以锁了1线程。

**Comment by NEKOparapa** [comment]
你可以下载源码，我可以告诉你怎么删除这句锁定代码

**Comment by wsndshx** [comment]
> 本身是可以并行的，只不过一般情况都是单线程运行，所以锁了1线程。

那选项里面的“最大线程数”现在是无效的么

![image](https://github.com/NEKOparapa/AiNiee/assets/7829265/4cd8ae35-a8aa-4bf3-999d-acd5faff2fa2)

因为用Sakura这种本地模型推理的话，线程数少了吃不满，而如果增加行数的话（例如60~80行）容易超过最大token和导致返回的行数不匹配。

用低行数加并发查询的话应该能提高模型的系统资源利用率

**Comment by NEKOparapa** [comment]
> > 本身是可以并行的，只不过一般情况都是单线程运行，所以锁了1线程。
> 
> 那选项里面的“最大线程数”现在是无效的么
> 
> ![image](https://private-user-images.githubusercontent.com/7829265/325312861-4cd8ae35-a8aa-4bf3-999d-acd5faff2fa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDk4OTIsIm5iZiI6MTcxNDE0OTU5MiwicGF0aCI6Ii83ODI5MjY1LzMyNTMxMjg2MS00Y2Q4YWUzNS1hOGFhLTRiZjMtOTk5ZC1hY2Q1ZmFmZjJmYTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTYzOTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJkNGZmYjE5OWNjNmQ1NGFlNDA0NzkzMzE0YjU1NzMxMTdlNmUyMzA5ZTM2MmI0MDMxNDE3MWNkNGE2YmQ3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rekXC0NoGypN-uS83k9McXbdp6MPyonVLdE97ipkPb4)
> 
> 因为用Sakura这种本地模型推理的话，线程数少了吃不满，而如果增加行数的话（例如60~80行）容易超过最大token和导致返回的行数不匹配。
> 
> 用低行数加并发查询的话应该能提高模型的系统资源利用率

是的，对Sakura不起效。现在大部分人运行一个模型，显存都吃力，如果之后能够解决这个问题，会解锁的

**Comment by lisna00z** [comment]
主要是我有两张显卡 每张显卡跑一个模型 如果能解锁线程的话可以提高很多速度
能告诉我如何删除锁定代码吗

**Comment by NEKOparapa** [comment]
> 主要是我有两张显卡 每张显卡跑一个模型 如果能解锁线程的话可以提高很多速度 能告诉我如何删除锁定代码吗

            #更改部分参数，以适合Sakura模型
            self.openai_temperature = 0.1       
            self.openai_top_p = 0.3
            self.thread_counts = 1 # 线程数

大概在3409行，你把            self.thread_counts = 1 # 线程数       删了就行

**Comment by lisna00z** [comment]
好的好的，谢谢谢谢 麻烦了
