### ISSUE TITLE
翻译的时候提示以下错误Error: 'str' object has no attribute 'choices'

### ISSUE THREAD

**Issue by oldtian123** [NEKOparapa/AiNiee#151]
如题，用的是OpenAI代理中转，APIkey测试提示通过，我自己用Python测试也是能正常回复，就是点击开始翻译就会报错Error: 'str' object has no attribute 'choices'

**Comment by NEKOparapa** [comment]
你的翻译设置和代理平台是怎么设置的，截图一下

**Comment by NEKOparapa** [comment]
应该是中转回复什么消息，不按openai格式来，直接字符串回复了，然后提取不到位置上的文本就报错了。可以问一下中转，或者下载最新版看看返回了什么消息
