### ISSUE TITLE
尝试使用提示字典的功能进行人名统一时，完全没有生效

### ISSUE THREAD

**Issue by Huang-Yujie** [NEKOparapa/AiNiee#152]
[ManualTransFile.json](https://github.com/NEKOparapa/AiNiee/files/15165669/ManualTransFile.json)
[用户提示字典.json](https://github.com/NEKOparapa/AiNiee/files/15165680/default.json)
模型是本地运行的sakurallm 0.9
AiNiee是最新版本4.66.6

能尝试的办法全都尝试过了，但是替换效果一点都没有生效，ミカゲ被翻译成无数个版本

**Comment by NEKOparapa** [comment]
0.9Sakura并不支持提示字典，支持提示字典的版本作者还在炼

**Comment by NEKOparapa** [comment]
0.10pre支持提示字典，但效果一般，你应该细看Sakura的readme
