### ISSUE TITLE
关于prompt的改善

### ISSUE THREAD

**Issue by TXT2GAM** [NEKOparapa/AiNiee#153]
根据我的观察，很多claude的中转商的请求格式都是openai的。也就是说在ainiee中使用的是gpt的prompt。但是claude需要破限，所以在这种情况下容易出现拒绝翻译的情况，希望可以针对claude进行优化。毕竟在目前的版本，claude的价格和翻译质量都是优于gpt的。

顺带一提，由于目前gpt新号不再赠送5刀额度，很多商家也用微软azure代替openai的gpt，azure的破限难度也比gpt更高。

以下是我个人的建议：prompt可以参考GalTransl的gpt4的部分。

**Comment by NEKOparapa** [comment]
软件是按模型来破限的，使用openai请求格式来调用claude一样有效。如果azure家的gpt模型是经过微调的，那应该破限难度比官网高。

**Comment by TXT2GAM** [comment]
是的，目前的ainiee版本已经很完美了。
azure的审核貌似可以通过上游关闭。关闭后就和普通的openai3.5一样了。
