### ISSUE TITLE
翻译epub小说时遇到在汉字顶上标注假名的句子无法完成翻译

### ISSUE THREAD

**Issue by turtlejk** [NEKOparapa/AiNiee#154]
测试翻了一些epub的日语小说 发现所有出现了在汉字顶上注音假名的句子都会整句显示日文原文 无法成功翻译

![test](https://github.com/NEKOparapa/AiNiee/assets/6604899/6554bf97-7cf9-42a2-85e1-187be15eceac)

**Comment by NEKOparapa** [comment]
> 测试翻了一些epub的日语小说 发现所有出现了在汉字顶上注音假名的句子都会整句显示日文原文 无法成功翻译
> 
> ![test](https://private-user-images.githubusercontent.com/6604899/327369969-6554bf97-7cf9-42a2-85e1-187be15eceac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NTI5MDQsIm5iZiI6MTcxNDY1MjYwNCwicGF0aCI6Ii82NjA0ODk5LzMyNzM2OTk2OS02NTU0YmY5Ny03Y2Y5LTQyYTItODVlMS0xODdiZTE1ZWNlYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTIyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjBkM2NkNzkzMmJiZTdjYTM1NDhjNTk5YWE3OTZjYzM1MTU4ZjRkZDU1MDAxNmE2YTVhNmZkNGIyNjI3NTM4NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zaqizn_fsyhToHltWZJUKDf0YoLTGp35eMaLzisbu1c)

嗯，你把这些小说打包上传一下，之前测试的小说，没有这种情况，所以应该有问题

**Comment by turtlejk** [comment]
链接：https://pan.baidu.com/s/1HvlwRBrMB0oBs1GbJORtVg?pwd=j5qv 
提取码：j5qv 
原版小说的epub打包上传了 我用的翻译平台是本地部署的SakuraLLM 同样的epub我用SakuraLLM官方的https://books.fishhawk.top/workspace/sakura 这个翻译工作区来翻译是正常翻译的

**Comment by JackLudens** [comment]
是否可以尝试在翻以前批量将这些日本标注删除，先将epub文件转换为zip文件，编辑有着正文内容的html文件，html中假名标注通常在 <ruby> 标签中

例如：
![01](https://github.com/NEKOparapa/AiNiee/assets/128439757/8583f3ef-90de-4f99-ad8f-4c52445cfc9b)

在html文件中是
`<ruby><rb>浅</rb><rt>あさ</rt><rb>間</rb><rt>ま</rt><rb>玲</rb><rt>れい</rt><rb>司</rb><rt>じ</rt></ruby>`

那么只需要在文本编辑器中，搜索并删除<ruby> </ruby> <rb> </rb> 本身，然后使用正则表达式匹配<rt></rt>本身与其标签对中的内容并删除
比如 正则表达式
`<rt>.*?</rt>`
操作无误的话html中显示的内容应该是

浅間玲司

将html文件保存，替换刚才导出的zip文件，再打包成epub之后即可进行翻译

**Comment by NEKOparapa** [comment]
> 是否可以尝试在翻译前批量将这些日本标注删除，先将epub文件转换为zip文件，编辑有着正文内容的html文件，html中假名标注通常在` <ruby>` 标签中
> 
> 例如： ![01](https://private-user-images.githubusercontent.com/128439757/327946343-8583f3ef-90de-4f99-ad8f-4c52445cfc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjUwNTQsIm5iZiI6MTcxNDgyNDc1NCwicGF0aCI6Ii8xMjg0Mzk3NTcvMzI3OTQ2MzQzLTg1ODNmM2VmLTkwZGUtNGY5OS1hZDhmLTRjNTI0NDVjZmM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMjEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTllMTVhN2Y4YTU4ZGIwOGU2OWFmZTgyZmM4ODRhMzk0MGU0YmMzNDQ0NjNlOGYwZDA4NWNhYzI5ZDUxYWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UUXNRu70VIDHUeoi8D0TbUrTHnvbJ70tZwA9efmGr8E)
> 
> 在html文件中是 `<ruby><rb>浅</rb><rt>あさ</rt><rb>間</rb><rt>ま</rt><rb>玲</rb><rt>れい</rt><rb>司</rb><rt>じ</rt></ruby>`
> 
> 那么只需要在文本编辑器中，搜索并删除`<ruby> </ruby> <rb> </rb>` 本身，然后使用正则表达式匹配`<rt></rt>`本身与其标签对中的内容并删除 比如 正则表达式 `<rt>.*?</rt>` 操作无误的话html中显示的内容应该是
> 
> 浅間玲司
> 
> 将html文件保存，替换刚才导出的zip文件，再打包成epub之后即可进行翻译

很好的建议，我尝试一下

**Comment by JackLudens** [comment]
> > 是否可以尝试在翻译前批量将这些日本标注删除，先将epub文件转换为zip文件，编辑有着正文内容的html文件，html中假名标注通常在` <ruby>` 标签中
> > 例如： ![01](https://private-user-images.githubusercontent.com/128439757/327946343-8583f3ef-90de-4f99-ad8f-4c52445cfc9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjUwNTQsIm5iZiI6MTcxNDgyNDc1NCwicGF0aCI6Ii8xMjg0Mzk3NTcvMzI3OTQ2MzQzLTg1ODNmM2VmLTkwZGUtNGY5OS1hZDhmLTRjNTI0NDVjZmM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMjEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTllMTVhN2Y4YTU4ZGIwOGU2OWFmZTgyZmM4ODRhMzk0MGU0YmMzNDQ0NjNlOGYwZDA4NWNhYzI5ZDUxYWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UUXNRu70VIDHUeoi8D0TbUrTHnvbJ70tZwA9efmGr8E)
> > 在html文件中是 `<ruby><rb>浅</rb><rt>あさ</rt><rb>間</rb><rt>ま</rt><rb>玲</rb><rt>れい</rt><rb>司</rb><rt>じ</rt></ruby>`
> > 那么只需要在文本编辑器中，搜索并删除`<ruby> </ruby> <rb> </rb>` 本身，然后使用正则表达式匹配`<rt></rt>`本身与其标签对中的内容并删除 比如 正则表达式 `<rt>.*?</rt>` 操作无误的话html中显示的内容应该是
> > 浅間玲司
> > 将html文件保存，替换刚才导出的zip文件，再打包成epub之后即可进行翻译
> 
> 很好的建议，我尝试一下

我自己尝试了一下，删除后确实没有了日文假名标注，但是排版全乱了，使用calibre转换为htmlz文件，然后更改扩展名为zip，正文内容就在index.html文件里，删除标记后好像是因为缺少了标注，日文竖向排版全乱了，文字都叠在一起，不知道会不会影响翻译

**Comment by NEKOparapa** [comment]
> 链接：https://pan.baidu.com/s/1HvlwRBrMB0oBs1GbJORtVg?pwd=j5qv 提取码：j5qv 原版小说的epub打包上传了 我用的翻译平台是本地部署的SakuraLLM 同样的epub我用SakuraLLM官方的https://books.fishhawk.top/workspace/sakura 这个翻译工作区来翻译是正常翻译的

压缩包密码多少

**Comment by turtlejk** [comment]
> > 链接：https://pan.baidu.com/s/1HvlwRBrMB0oBs1GbJORtVg?pwd=j5qv 提取码：j5qv 原版小说的epub打包上传了 我用的翻译平台是本地部署的SakuraLLM 同样的epub我用SakuraLLM官方的https://books.fishhawk.top/workspace/sakura 这个翻译工作区来翻译是正常翻译的
> 
> 压缩包密码多少

哦 我忘记写了 密码是 ceshiepub

**Comment by NEKOparapa** [comment]
最新版已修
