### ISSUE TITLE
使用google gemini模型时出错

### ISSUE THREAD

**Issue by Moeary** [NEKOparapa/AiNiee#155]
最近正好在用gemini的api 毕竟免费,比openai注册账号要方便一点
谷歌给大模型加入了审查机制.在回复前会检查有无露骨暴力内容,如果有会停止回复
![image](https://github.com/NEKOparapa/AiNiee/assets/103913682/eb294383-c69e-4c73-8553-b756613c60a8)
![image](https://github.com/NEKOparapa/AiNiee/assets/103913682/fff02f4d-cc7f-4a1a-80b7-bcf38b340be3)
请求在google页面设置里面添加相关的参数设置:https://ai.google.dev/gemini-api/docs/safety-settings?hl=zh-cn

**Comment by NEKOparapa** [comment]
这个审查是独立的，与模型本身无关，而且也已经设置为none了
