### ISSUE TITLE
SRT檔純數字句子翻譯後格式跑掉

### ISSUE THREAD

**Issue by anyuexue77** [NEKOparapa/AiNiee#162]
翻譯純數字句子後SRT格式跑掉
例如142句的內容是30
變成是第30句內容空白
![image](https://github.com/NEKOparapa/AiNiee/assets/99235492/80dfd268-c34a-4116-a9dd-46d94b5539ed)

**Comment by anyuexue77** [comment]
[翻譯後.txt](https://github.com/NEKOparapa/AiNiee/files/15311582/default.txt)

這裡

**Comment by NEKOparapa** [comment]
是翻译前的字幕原文件

**Comment by anyuexue77** [comment]
[翻譯前.txt](https://github.com/NEKOparapa/AiNiee/files/15311593/default.txt)

**Comment by NEKOparapa** [comment]
你截图一下，翻译设置的基础设置页面

**Comment by anyuexue77** [comment]
![image](https://github.com/NEKOparapa/AiNiee/assets/99235492/ee12ae3c-2996-403c-89a3-245723392203)

**Comment by NEKOparapa** [comment]
测试版已修

**Comment by anyuexue77** [comment]
好像又有新的問題
一次翻多個文件時
第一個正常，從第二個開始SRT格式會跑掉
![image](https://github.com/NEKOparapa/AiNiee/assets/99235492/2122ae37-e922-49d7-98d0-de21159176d8)
![image](https://github.com/NEKOparapa/AiNiee/assets/99235492/575e2d7d-e416-45e0-81a1-a361741c13b8)

**Comment by NEKOparapa** [comment]
你这真是srt文件么，格式不一样，当然出错了

**Comment by NEKOparapa** [comment]
标注格式是：
1
00:00:35,050 --> 00:00:59,630
そろそろ吐いてる感覚に慣れてきたかな

2
00:00:59,630 --> 00:01:01,970
お尻の穴

3
00:01:01,970 --> 00:01:06,290
染みるたびに

4
00:01:06,310 --> 00:01:08,908
甘い感覚が

**Comment by anyuexue77** [comment]
對阿 我原文件的格式就是這樣，翻譯後就跑掉了
指翻譯1個文件時正常
翻譯多個時第一個正常後面全部都變那樣

**Comment by NEKOparapa** [comment]
> 對阿 我原文件的格式就是這樣，翻譯後就跑掉了 指翻譯第一個文件時正常 翻譯多個時第一個正常後面全部都變那樣

哦哦，我大概知道问题在哪里了
