### ISSUE TITLE
[BUG]用简中翻译到英语没有用，无法翻译

### ISSUE THREAD

**Issue by bbc117** [NEKOparapa/AiNiee#165]
控制台：
![4](https://github.com/NEKOparapa/AiNiee/assets/82558159/83c7af25-0f73-488a-add0-262fb4afc98d)
原文：
![5](https://github.com/NEKOparapa/AiNiee/assets/82558159/269b308c-7ebe-4335-ab56-275836701bc6)
输出：
![6](https://github.com/NEKOparapa/AiNiee/assets/82558159/3f41df62-4695-4d62-894e-8157c59eccec)
设置：
![7](https://github.com/NEKOparapa/AiNiee/assets/82558159/f5f0f02f-d84b-4d19-99a9-045e267213a8)

**Comment by bbc117** [comment]
无论设置怎么改，都是日语翻译成中文

**Comment by NEKOparapa** [comment]
Sakura只支持日语到中文。。。

**Comment by bbc117** [comment]
请问源语言和目标语言的切换是没有实现的功能吗，未来会做吗？

**Comment by NEKOparapa** [comment]
是人家模型专门训练为日中翻译的模型，你应该看一下Sakura的GitHub介绍

**Comment by bbc117** [comment]
我用的是千问的模型他可以翻译其他语言

**Comment by NEKOparapa** [comment]
为了适配Sakura，prompt是写死的，除非你自己下载源码更改
