### ISSUE TITLE
哥，咱要不把程序分割一下吧。

### ISSUE THREAD

**Issue by daiaji** [NEKOparapa/AiNiee#172]
现在一大坨，塞gemini都直接报错。
分割成小文件，再格式化一下。
然后用gemini做重构都快一些吧。

**Comment by NEKOparapa** [comment]
是有计划的，但排后面，等再写几个新功能后

**Comment by daiaji** [comment]
感觉是能够大量模块化
我当时想试试看能不能找到什么请求文本会触发gemni的关键词检测。
但看了一下，也没返回请求文本。
print本身也不记录到日志文件就难崩。

**Comment by NEKOparapa** [comment]
如果触发了他家的审查，只会返回错误码。根据我的经验，瑟瑟文本是很容易触发的

**Comment by daiaji** [comment]
> 如果触发了他家的审查，只会返回错误码。根据我的经验，瑟瑟文本是很容易触发的

有时候他不触发😭

**Comment by NEKOparapa** [comment]
你不要发太多了，30左右就行了，你7，80的，很容易缺行的
