### ISSUE TITLE
StevExtraction能增加plugins.js的提取吗

### ISSUE THREAD

**Issue by fatecyx** [NEKOparapa/AiNiee#173]
就这一个文件
很多rpg在这里面放菜单、奖杯、游戏说明之类的文本

**Comment by NEKOparapa** [comment]
这个文件如果翻译了，经常出现问题，所以才忽略的

**Comment by fatecyx** [comment]
可以提取翻译了之后再看报错的事嘛，基本上还是挺好排查的，现在想翻译要再人工提取一次

**Comment by NEKOparapa** [comment]
需要你与该工具作者交流一下，主要维护工作也是由他贡献

**Comment by NEKOparapa** [comment]
是[stevetrs](https://github.com/stevetrs)
