### ISSUE TITLE
似乎是html对calibre有错误的未能支持，导致已经翻译了没有写入HTML

### ISSUE THREAD

**Issue by laulguo** [NEKOparapa/AiNiee#175]
[反馈BUG.zip](https://github.com/user-attachments/files/15543211/BUG.zip)
[反馈BUG.zip](https://github.com/user-attachments/files/15543211/BUG.zip)
[反馈BUG.zip](https://github.com/user-attachments/files/15543211/BUG.zip)
内部包含原文件，缓存以及输出

**Comment by laulguo** [comment]
典型案例：
"text_index": 144,
        "translation_status": 1,
        "source_text": "Yet for both Americans and Japanese, the overriding aspect of the Japanese navy is its ultimate defeat. Indeed, it was not just beaten by the U.S. Navy; it was annihilated. To Americans of an older generation, particularly those who fought against Japan’s navy, that defeat has been a cause of considerable satisfaction and pride. To older Japanese, particularly those who served in their navy, it is a source of humiliation and regret. For those scholars on both sides of the Pacific who study the Japanese navy, its ultimate defeat is the ineluctable fact in the assessment of its capabilities, its combat performance, even its victories.1",
        "translated_text": "然而，对于美国人和日本人来说，日本海军的最终失败是最重要的方面。事实上，它不仅被美国海军击败，而且被歼灭。对于那些曾与日本海军作战的老一辈美国人来说，这一失败是一种相当大的满足和骄傲。对于那些曾在日本海军服役的日本老一辈人来说，这是一种耻辱和遗憾。对于太平洋两岸研究日本海军的学者来说，它的最终失败是评估其能力、战斗表现甚至胜利的不可避免的事实。",
        "html": "Yet for both Americans and Japanese, the overriding aspect of the Japanese navy is its ultimate defeat. Indeed, it was not just beaten by the U.S. Navy; it was annihilated. To Americans of an older generation, particularly those who fought against Japan’s navy, that defeat has been a cause of considerable satisfaction and <a id=\"pxxi\" class=\"calibre7\"/>pride. To older Japanese, particularly those who served in their navy, it is a source of humiliation and regret. For those scholars on both sides of the Pacific who study the Japanese navy, its ultimate defeat is the ineluctable fact in the assessment of its capabilities, its combat performance, even its victories.<sup class=\"fn-num\"><a id=\"intro-r_fn1\" href=\"part0025_split_000.html#intro-fn1\" class=\"calibre7\">1</a></sup>",

**Comment by NEKOparapa** [comment]
[Kaigun Strategy, Tactics, and Technology in the Imperial Japanese Navy, 1887–1941_translated.zip](https://github.com/user-attachments/files/15568117/Kaigun.Strategy.Tactics.and.Technology.in.the.Imperial.Japanese.Navy.1887.1941_translated.zip)
修好了，我真是服了，ebooklib库读取到的内容，会将成对的原生标签变成自适应标签，所以导致文本对不上，就替换不了原文。之后推一版测试版，以后你翻译到2，30进度时，可以在备份功能，导出已翻译内容，先看看前面的翻译对了没，有没有问题。以免浪费过多钱
