### ISSUE TITLE
建议去除头尾字符时保留前面的数字

### ISSUE THREAD

**Issue by fatecyx** [NEKOparapa/AiNiee#176]
句末的数字确实没什么用
但句首数字去掉以后意思立刻就变了
目前逻辑似乎是判断第一个中日文字符然后分割？那么应该可以判断一下前面的末尾，把数字加回来

**Comment by NEKOparapa** [comment]
可以给些例子么？

**Comment by fatecyx** [comment]
嗯，是说数字影响意思的例子吗？
比如：3回に1度程度の割合で拘束を解除する。->解除拘束的频率大约为三分之一。
去数字后会变成
回に1度程度の割合で拘束を解除する。->大约每隔一次解除一次拘束。

就算好点的，因为数字在前面，而单位往往会翻译到后面去，也很影响效果

**Comment by NEKOparapa** [comment]
很好的建议，之后会忽略前后纯数字的文本

**Comment by NEKOparapa** [comment]
测试版已修
