### ISSUE TITLE
希望下个版本加入翻译完成后删除原文件的功能

### ISSUE THREAD

**Issue by sqsq37** [NEKOparapa/AiNiee#178]
不然次次弄完都要去导入文件夹手动删除挺累的+

**Comment by laulguo** [comment]
这玩意顶天做个默认开关，否则好多缓存你还要检查一遍有没有啥问题然后补救呢，你给全删了。。

**Comment by NEKOparapa** [comment]
虽然只是简单的功能，但是因为增加这功能需要联动到UI，需要增加不少界面的代码，且考虑到不是大多数人用，就暂时不加入了。建议你一次性把多个同类型的原文文件，放到输入文件夹一起翻译了。
