### ISSUE TITLE
claude官方无token消耗统计和调参设置无效

### ISSUE THREAD

**Issue by ApriYu** [NEKOparapa/AiNiee#179]

**Comment by NEKOparapa** [comment]
应该是官网没有返回tokens消耗，所以没有进行计数，建议去开发后台查看更为准确。调参现在只能调openai和Sakura的，其他平台还未做支持

**Comment by ApriYu** [comment]
调参在未来的更新中会考虑添加吗？claude默认1.0的temperature对翻译来说有点过高了....

**Comment by ApriYu** [comment]
> 应该是官网没有返回tokens消耗，所以没有进行计数，建议去开发后台查看更为准确。调参现在只能调openai和Sakura的，其他平台还未做支持

调参在未来的更新中会考虑添加吗？claude默认1.0的temperature对翻译来说有点过高了....

**Comment by NEKOparapa** [comment]
会的
