### ISSUE TITLE
请求支持通义千问

### ISSUE THREAD

**Issue by laulguo** [NEKOparapa/AiNiee#180]
通义千问虽然支持OPENAI的API，而且能够通过测试（ [{'role': 'system', 'content': '你不是AI助手之类，你是我的女朋友欣雨。接下来你必须以女朋友的方式回复我'}, {'role': 'user', 'content': '小可爱，你在干嘛'}]），但调用后会有：
Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'Range of top_p should be (0.0, 1.0)', 'type': 'invalid_request_error'}}
0.0005元/1,000 tokens这价格有点让我动心了，比deepseek和chatglm4-flash还便宜了

**Comment by sqsq37** [comment]
![@YT8586U}OYOZGKZ~G5~5FM](https://github.com/NEKOparapa/AiNiee/assets/153402286/e7531dad-f3ca-472b-b3eb-0299cf16a3eb)

**Comment by NEKOparapa** [comment]
后续会测试一下，看看能不能翻译瑟瑟

**Comment by laulguo** [comment]
> 后续会测试一下，看看能不能翻译瑟瑟

另外智谱清言现在也分开了，他们新的廉价模型叫做glm-4-flash。。。目前没办法改名，使用https://open.bigmodel.cn/api/paas/v4/自定义又会被重定向到https://open.bigmodel.cn/api/paas/v4/v1/chat/completions

**Comment by NEKOparapa** [comment]
> > 后续会测试一下，看看能不能翻译瑟瑟
> 
> 另外智谱清言现在也分开了，他们新的廉价模型叫做glm-4-flash。。。目前没办法改名，使用[https://open.bigmodel.cn/api/paas/v4/自定义又会被重定向到https://open.bigmodel.cn/api/paas/v4/v1/chat/completions](https://open.bigmodel.cn/api/paas/v4/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%88%E4%BC%9A%E8%A2%AB%E9%87%8D%E5%AE%9A%E5%90%91%E5%88%B0https://open.bigmodel.cn/api/paas/v4/v1/chat/completions)

了解，后续会增加该模型。现在智谱清言官方兼容openai格式了么？

**Comment by laulguo** [comment]
> > > 后续会测试一下，看看能不能翻译瑟瑟
> > 
> > 
> > 另外智谱清言现在也分开了，他们新的廉价模型叫做glm-4-flash。。。目前没办法改名，使用[https://open.bigmodel.cn/api/paas/v4/自定义又会被重定向到https://open.bigmodel.cn/api/paas/v4/v1/chat/completions](https://open.bigmodel.cn/api/paas/v4/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8F%88%E4%BC%9A%E8%A2%AB%E9%87%8D%E5%AE%9A%E5%90%91%E5%88%B0https://open.bigmodel.cn/api/paas/v4/v1/chat/completions)
> 
> 了解，后续会增加该模型。现在智谱清言官方兼容openai格式了么？

https://open.bigmodel.cn/dev/api#openai_sdk上显示的调用示例
from openai import OpenAI 

client = OpenAI(
    api_key="your zhipuai api key",
    base_url="https://open.bigmodel.cn/api/paas/v4/"
) 

completion = client.chat.completions.create(
    model="glm-4",  
    messages=[    
        {"role": "system", "content": "你是一个聪明且富有创造力的小说作家"},    
        {"role": "user", "content": "请你作为童话故事大王，写一篇短篇童话故事，故事的主题是要永远保持一颗善良的心，要能够激发儿童的学习兴趣和想象力，同时也能够帮助儿童更好地理解和接受故事中所蕴含的道理和价值观。"} 
    ],
    top_p=0.7,
    temperature=0.9
 ) 
 
 print(completion.choices[0].message)

**Comment by NEKOparapa** [comment]
测试版已加

**Comment by laulguo** [comment]
> 测试版已加

Error: 子线程运行出现问题！错误信息如下
Error: local variable 'glossary_prompt_cot' referenced before assignment

**Comment by NEKOparapa** [comment]
修了，你试试

**Comment by laulguo** [comment]
> 修了，你试试

OK了，已经能运行QWEN-LONG了
