### ISSUE TITLE
是否可新增繁简转换字典功能

### ISSUE THREAD

**Issue by gamania31610** [NEKOparapa/AiNiee#182]
部分用语用字在繁简上有不同

因为不确定繁简转换的方式是透过什么

想问是否可新增字典功能来自定转换后的词/字呢

举个例子:现行版本刚才会转换成剛纔(但繁体也通常是用"剛才")，吃会转换成喫(但繁体也通常是用"吃")

有试过译后修正功能，但似乎繁简转换是在最后才执行，这功能不起作用

**Comment by NEKOparapa** [comment]
对的，繁简转换是在最后才执行的。简繁转换是调用其他开源库实现的，所以无法自定义转换的词，还是建议使用专业的文档或者表格编辑器来处理。
