### ISSUE TITLE
建议增加：忽略AI回复内容与原文相同的开关

### ISSUE THREAD

**Issue by nightkings7** [NEKOparapa/AiNiee#184]
有些原文已经汉化过一半了，与原文一致，不用再次拆分翻译。保留原文即可，建议增加相关的按钮。

`Warning: AI回复内容存在问题: AI回复内容与原文相同，未进行翻译，将重新翻译

Warning: 错误重新翻译最大次数限制: 1 剩余可重试次数: 0 到达次数限制后，该段文本将进行拆分翻译

Warning: 错误回复重翻次数已经达限制,将该段文本进行拆分翻译！`

**Comment by NEKOparapa** [comment]
你是把已经翻译过的文本也发过去了？

**Comment by nightkings7** [comment]
> 你是把翻译过的文本也发过去了？

是的，通过MTool提取的json文件，游戏本身已经有部分汉化了，但还有部分没有汉化。所以想要个开关能忽略掉“AI回复内容与原文相同”

**Comment by NEKOparapa** [comment]
暂时不会考虑加，情况比较特殊，不过我可以告诉你以更改源码方式来关掉这个功能：删除以下代码即可：：        # 检查是否回复了原文
        if Response_Parser.check_dicts_equal(self,source_text_dict,response_dict):
            pass
        else:
            check_result = False
            # 存储错误内容
            error_content = "AI回复内容与原文相同，未进行翻译，将重新翻译"
            return check_result,error_content

**Comment by nightkings7** [comment]
> 暂时不会考虑加，情况比较特殊，不过我可以告诉你以更改源码方式来关掉这个功能：删除以下代码即可： # 检查是否回复了原文 if Response_Parser.check_dicts_equal(self,source_text_dict,response_dict): pass else: check_result = False # 存储错误内容 error_content = "AI回复内容与原文相同，未进行翻译，将重新翻译" return check_result,error_content

好的，谢谢
