### ISSUE TITLE
最新版本4.70.1-子线程运行出现问题

### ISSUE THREAD

**Issue by snowandrain** [NEKOparapa/AiNiee#186]
![image](https://github.com/NEKOparapa/AiNiee/assets/22421823/0b1ca2ae-cdf1-42ac-9e84-a4708dabc136)

**Comment by NEKOparapa** [comment]
你把原文文件打包上传一下

**Comment by NEKOparapa** [comment]
这是开了 处理首尾非文本字符 功能么？

**Comment by snowandrain** [comment]
> 这是开了 处理首尾非文本字符 功能么？

对的，开了这个

**Comment by NEKOparapa** [comment]
那你先关了，后面会修这个bug

**Comment by snowandrain** [comment]
> 那你先关了，后面会修这个bug

好

**Comment by NEKOparapa** [comment]
最新版修了，重下即可
