### ISSUE TITLE
Incorrect prompt: AI回复内容中存在大量相同的译文

### ISSUE THREAD

**Issue by chou18194766xx** [NEKOparapa/AiNiee#187]
I use it to translate comic text, but it often prompts:

`Warning: AI回复内容存在问题: AI回复内容中存在大量相同的译文,将进行重新翻译

Warning: 错误重新翻译最大次数限制: 1 剩余可重试次数: 0 到达次数限制后，该段文本将进行拆分翻译

Warning: 错误回复重翻次数已经达限制,将该段文本进行拆分翻译！`

In fact, some of the lines in the comic do repeat themselves

**Comment by NEKOparapa** [comment]
It’s possible that the text contains a large number of identical modal particles. Please zip the original document and upload it, and I will run it to check.

**Comment by NEKOparapa** [comment]
You can send them to this email address：n17687297753@gmail.com. I have relaxed the restrictions on this feature in the latest version, you can try redownloading version 4.70.1 and see if you can translate normally.

**Comment by chou18194766xx** [comment]
> You can send them to this email address: n17687297753@gmail.com. I have relaxed the restrictions on this feature in the latest version, so you can try re-downloading version 4.70.1 and see if you can translate normally.

I have sent it, please check your emails.

**Comment by NEKOparapa** [comment]
[tttttttt.zip](https://github.com/user-attachments/files/15871470/tttttttt.zip)
The latest version can translate normally, but I haven’t carefully reviewed the translation results, so there might be issues.
