### ISSUE TITLE
[Bug] 大括号中的字符异常改变

### ISSUE THREAD

**Issue by zx3777** [NEKOparapa/AiNiee#196]
[AiNiee4.70.1] 翻译平台 gemini flash

对话中有控制字体大小和颜色的代码。

我看了翻译时的log，AI返回的是正常的，但翻译完转换为文本文件结果就变了。

{i}{size=-6} 变成 {"}{size=-"}

{w=0.4} 变成 {w=0.\"}

{size=+10}{color=#82C200} 变成  {size=+1\"}{color=#82C20\"}

{/color}{/size} 变成  {/colo\"}{/siz\"}

等等

**Comment by NEKOparapa** [comment]
应该是修复算法的问题，有些ai回复会缺少双引号或者逗号，后面会进行修复，如果你着急就先去源码把            # 对格式进行修复       
            input_str = Response_Parser.repair_double_quotes(self,input_str)
            input_str = Response_Parser.repair_double_quotes_2(self,input_str)  
            input_str = Response_Parser.repair_double_quotes_3(self,input_str)        改为pass

**Comment by NEKOparapa** [comment]
对了，顺便上传一份原文文件给我

**Comment by zx3777** [comment]
> 对了，顺便上传一份原文文件给我

[test.json](https://github.com/user-attachments/files/15936622/test.json)

原文文本有些大，这个测试文本里差不多包含了原文中所有形式的中括号。

**Comment by NEKOparapa** [comment]
测试版已修，虽然只是把这个修改功能注释掉，但影响不大。

**Comment by zx3777** [comment]
> 测试版已修，虽然只是把这个修改功能注释掉，但影响不大。gemini也加了

非常感谢
