### ISSUE TITLE
关于中转平台的地址问题

### ISSUE THREAD

**Issue by qw1642190428** [NEKOparapa/AiNiee#199]
希望可以添加要不要加/v1的功能 我用的就不带v1 带了反而连不上

**Comment by NEKOparapa** [comment]
是不是你输入地址时带空格了，现在一般来说中转都是openai格式

**Comment by qw1642190428** [comment]
我确定不是 我用的chary 不知道你知不知道 这个接口是免费的

**Comment by qw1642190428** [comment]
他没有v1的 这一点我确定

**Comment by qw1642190428** [comment]
那个应该不能算是中转？

**Comment by Billionn** [comment]
SakuraLLM的请求地址同样会自动加上/v1后缀  ![image](https://github.com/NEKOparapa/AiNiee/assets/24206248/dea14c21-672e-4434-8b13-c19363dee980)

**Comment by NEKOparapa** [comment]
> SakuraLLM的请求地址同样会自动加上/v1后缀 ![image](https://private-user-images.githubusercontent.com/24206248/344384656-dea14c21-672e-4434-8b13-c19363dee980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzQ3MjgsIm5iZiI6MTcxOTY3NDQyOCwicGF0aCI6Ii8yNDIwNjI0OC8zNDQzODQ2NTYtZGVhMTRjMjEtNjcyZS00NDM0LThiMTMtYzE5MzYzZGVlOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDE1MjAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMzk4ZTYxYzg3ZjNiNTgzNzM1YzYyMWY4ZjIwMjA3OGVmNTczZWMwYTZmMTY2YmMzNTYwYzQxOGQxMTcwMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nS8G5z7mSsTxNlPBY_Vb5gIHBaCwap1EjdiDYCz-nA4)

你好好看一下GitHub教程怎么写的

**Comment by NEKOparapa** [comment]
> 希望可以添加要不要加/v1的功能 我用的就不带v1 带了反而连不上

后面可能会加，但不会很快加入，还要考量一下ui怎么安排

**Comment by popcion** [comment]
![image](https://github.com/NEKOparapa/AiNiee/assets/170460140/9768c02e-8b42-4791-807a-9527d6b3c901)
期待一下自定义API PATH

**Comment by NEKOparapa** [comment]
测试版已加
