### ISSUE TITLE
开启思维链翻译后，部分译文后出现翻译解释 ExplanationofTranslationChoices

### ISSUE THREAD

**Issue by jeshs** [NEKOparapa/AiNiee#203]
设置：模型Gemini 1.5 pro，每次10行，携带上文90行，线程数0，使用思维链，保留换行符，处理首尾非文字字符，使用人名字典

结果：翻译后，部分文本后面出现多余的解释 ExplanationofTranslationChoices，如下图所示：
<img width="1202" alt="屏幕截图 2024-06-25 220305" src="https://github.com/NEKOparapa/AiNiee/assets/43285002/5085f01c-3a47-4dac-88a1-047a234f5e3c">

原文文件：[ManualTransFile已处理.json](https://github.com/user-attachments/files/15972392/ManualTransFile.json)
译文文件：[ManualTransFile已处理_translated.json](https://github.com/user-attachments/files/15972401/ManualTransFile._translated.json)

**Comment by NEKOparapa** [comment]
使用的版本呢

**Comment by jeshs** [comment]
版本4.71

**Comment by NEKOparapa** [comment]
模型抽风了，你可以尝试减少上文行数与翻译行数相同，或者修改系统提示词，系统提示词在开始翻译前日志里有。以后再有类似问题，再考虑加个回复检测

**Comment by jeshs** [comment]
如果修改系统提示词，那思维链是不是就被覆盖了

**Comment by NEKOparapa** [comment]
在原有的cot版系统提示词上进行修改

**Comment by jeshs** [comment]
OK，感谢
