### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by zx3777** [NEKOparapa/AiNiee#204]
1. 如果待翻译文件夹里有若干个文件，能不能给个选项不合并这些文件一起发给AI，而是每个文件分开发送。特别是对于字幕来说，不同的字幕合并在一起，上下文就乱了，可能影响翻译效果。

2. 希望能增加代理平台的温度设置。或者跟随参数调整里相应请求格式平台的温度参数。

3. 参数调整里，实时改变AI参数选项，选中之后重启软件，就会撤销选中。不知道是BUG还是故意的，如果是有意的希望能给个记忆选项。

4. 还有就是希望能支持文件拖放，输出文件输出到原文件所在文件夹。

**Comment by NEKOparapa** [comment]
你分开翻译就行，而且上文携带不会超过单个文件。你代理平台用什么格式发送就用对应的格式的参数调整。故意没加的，就是防止有人忘记关了。文件拖放还没有计划，输入输出文件夹不同是为了减少用户不必要的问题的出现，虽然现在也可以是了。

**Comment by zx3777** [comment]
> 你分开翻译就行，而且上文携带不会超过单个文件。你代理平台用什么格式发送就用对应的格式的参数调整。故意没加的，就是防止有人忘记关了。文件拖放还没有计划，输入输出文件夹不同是为了减少用户不必要的问题的出现，虽然现在也可以是了。

我用这个软件主要就是想批量翻译字幕。有的字幕可能行数很少，几个字幕主题也可能完全不同，合并发送会干扰ai理解。不像游戏翻译，一个游戏的待翻译文件大都是同一主题，合并影响也不大。

**Comment by NEKOparapa** [comment]
其实没有多少影响，你拿几个字幕文件测试一下就知道了，不过后面会考虑加入选取文本时限制单文件内的

**Comment by zx3777** [comment]
> 其实没有多少影响，你拿几个字幕文件测试一下就知道了，不过后面会考虑加入选取文本时限制单文件内的

使用中又发现个问题，有时候字幕中本来就是有大量重复词的，特别是使用whisper这种文字转语音得到的字幕。现在检测翻译结果有重复词会误伤：Warning: AI回复内容存在问题: AI回复内容中存在大量相同的译文,将进行重新翻译。重新翻译失败又分段，浪费调用次数。我现在一次给喂100段甚至200段字幕，因为有的AI每天有调用限制。

**希望能给个检测重复译文的关闭选项**。

**Comment by NEKOparapa** [comment]
测试版，改变了这个检查算法，应该不会出现这个问题了
