### ISSUE TITLE
SakuraLLMScript里的common.bat换行格式是LF.在Windows下运行会报错

### ISSUE THREAD

**Issue by LANPAST** [NEKOparapa/AiNiee#206]
手动改成CRLF之后可以运行

**Comment by NEKOparapa** [comment]
@neavo

**Comment by neavo** [comment]
> 手动改成CRLF之后可以运行

奇怪，我这儿拉到本地以后确实是CRLF，不管是用git拉的，还是直接下文件的，还是发布版本压缩包里的，都是正确的

你是怎么下载脚本的，能把你那个会报错的版本打包发上来看一下嘛？

**Comment by LANPAST** [comment]
> > 手动改成CRLF之后可以运行
> 
> 奇怪，我这儿拉到本地以后确实是CRLF，不管是用git拉的，还是直接下文件的，还是发布版本压缩包里的，都是正确的
> 
> 你是怎么下载脚本的，能把你那个会报错的版本打包发上来看一下嘛？ @LANPAST

是在这个页面直接下载的
![图片](https://github.com/NEKOparapa/AiNiee/assets/29109822/e42436a3-c433-4705-b597-6782399e5b47)

用VSCODE打开以后就是LF
![图片](https://github.com/NEKOparapa/AiNiee/assets/29109822/cf9a66ec-b5c2-42fa-a786-3727ba4e846e)

这是文件
[common.zip](https://github.com/user-attachments/files/16011483/common.zip)

**Comment by neavo** [comment]
推了pr，合一下 @NEKOparapa 
测了一下，只有在单个文件页面直接点下载才会下载到LF的版本
其他的方式，比如打包下载源码、git clone 或者应用包里的都是 CRLF 版本

但是很诡异的是：我从本地git上怎么推，推上去都是LF的版本，最后通过github网页上传覆盖文件才成功把 CRLF 版本推上去 ... 🤣
