### ISSUE TITLE
[BUG] 双行字幕换行符错误

### ISSUE THREAD

**Issue by zx3777** [NEKOparapa/AiNiee#211]
程序版本是昨天的测试版。

srt原字幕
1
00:00:26,059 --> 00:00:31,157
hurry up or I won't be able to catch
the 8:04 commuter express.

2
00:00:49,316 --> 00:00:54,345
Cool, Seiko.
Wear a nice outfit today.

翻译后的字幕
1
00:00:26,059 --> 00:00:31,157
快点，否则我就赶不上\n8:04的通勤快车了。

2
00:00:49,316 --> 00:00:54,345
酷，圣子。\n今天穿件漂亮的衣服。

另一个bug，发送时文本内容把序号也加上了，翻译的文本也带序号。这个bug比较罕见。十几个字幕文件有一个会出现，那一个字幕里也不全这样，正常的占多数。
"48": "48\nWhat bad luck...", "49": "49\nFirst, let's take attendance.", "50": "50\nI want to be able to recognize you quickly.", "51": "51\nOn your name, please answer \"Yes\" in a loud voice.", "52": "52\n-Shibuki Asahina\n- Present !", "53": "53\n- Yuko Ana.\n- Yes.", "54": "54\n- Noboro Otori.\n- Yes ?",

**Comment by NEKOparapa** [comment]
你把双行字幕文件和出现带序号的字幕文本，打包上传一下

**Comment by zx3777** [comment]
专项设置都是关的。

**Comment by zx3777** [comment]
还有翻译完字幕中的空格被消失了，日语 韩语 这种语言，翻译完一大段话没空格。

**Comment by NEKOparapa** [comment]
我看了一下你上传的压缩包，里面是示例字幕文件，我需要实际字幕文件来测试
