### ISSUE TITLE
使用Sakura0.10pre1进行翻译时无法按照术语表进行翻译

### ISSUE THREAD

**Issue by starP-W** [NEKOparapa/AiNiee#215]
使用版本：
4.71

使用的模型：
sakura-32b-qwen2beta-v0.10pre1-iq4xs.gguf

启动命令：
```
./llama-server -c 2880 -sm none --no-mmap -cb -ngl 999 -m ../LLMs/sakura-32b-qwen2beta-v0.10pre1-iq4xs.gguf -np 3
```

AiNiee设置：
- 模型选择：Sakura-0.10pre
- 使用模式：token，每次翻译360
- 最大线程数1
- 保留换行符并处理首尾非文本字符

观察到的现象：
启动翻译后，术语表检测到对应的关键字存在并打印在命令行中，但实际翻译未使用写入的术语，通过抓包发现术语表是空的
![image](https://github.com/NEKOparapa/AiNiee/assets/22597802/060bc550-a71d-4568-806a-288a8717363c)
![image](https://github.com/NEKOparapa/AiNiee/assets/22597802/85f8e4e3-e8d9-4566-bbfc-135bd2960482)

期待的现象：
发送待翻译文本时将术语一起打包发送到模型中，模型参考术语进行翻译

**Comment by NEKOparapa** [comment]
恩，是因为写错变量了，所以没有添加进去，测试版已经修了
