### ISSUE TITLE
[请求功能]支持vtt格式文件和xlxs的术语文件导入导出

### ISSUE THREAD

**Issue by yihuishou** [NEKOparapa/AiNiee#217]
vtt ASMR 音声字幕希望能得到支持
json 格式的术语表在需要编辑大量术语时非常费力

**Comment by NEKOparapa** [comment]
json 格式的术语表，你在ui里编辑不就行了么

**Comment by NEKOparapa** [comment]
vtt 应该很多工具可以转srt或者lrc的吧

**Comment by yihuishou** [comment]
> json 格式的术语表，你在ui里编辑不就行了么

当物品或者道具、人物很多的时候 编辑起来可就....

**Comment by NEKOparapa** [comment]
测试版已加xlxs的术语文件导入导出
