### ISSUE TITLE
用StevExtraction翻译并注入译文后，游戏运行中报错等问题

### ISSUE THREAD

**Issue by 98abwt** [NEKOparapa/AiNiee#221]
用StevExtraction翻译游戏（RJ01179787），注入译文后，
游戏在运行中报错，
![QQ截图20240712153409](https://github.com/user-attachments/assets/0e235927-58db-484c-9f9a-e54ac002687f)
且文章显示有点问题。如图。
![QQ截图20240712154044](https://github.com/user-attachments/assets/9dffe1fc-bbc6-47a7-ab68-573e32167f81)
还有就是文本提取不全。我又用mtool试了下，如图开始游戏片头部分都能翻译，但是用StevExtraction的话，这里就还是日文。
![QQ截图20240712160252](https://github.com/user-attachments/assets/f193297d-bcd1-4fb6-9c2c-2501efda8c13)

翻译过程中使用到的文件
[[なぎや本舗] メイドイン!～新人メイドと坊ちゃまの、エッチなお屋敷箱庭性活～ [v2][RJ01179787].zip](https://github.com/user-attachments/files/16190377/v2.RJ01179787.zip)

**Comment by NEKOparapa** [comment]
第一个问题是，你翻译到了代码文本，所以运行出错了，可以在翻译后文件中搜索并改正。第二个问题是，工具默认的提取范围没有覆盖到这些文本，可能需要你学习深入了解一下这个工具，并添加新的规则。mtool是外挂式软件，不会影响到游戏原文件，所以啥都敢翻译，还有问题，可以问问工具的作者@stevetrs

**Comment by stevetrs** [comment]
你这个报错是因为文件名存在映射，一键处理处理不了，所以导致文件名被翻译了。

你这个我猜应该是在system.json里，你可以去找找

\c显示问题有点麻烦，不好解决。我个人体感是Sakura出现的概率要比gpt大

最后一个问题，楼上说的对

**Comment by nosgk** [comment]
确实, RPG游戏的资源文件名被提取到并被翻译了, 可以将StevExtraction提取到的"name.json"全部加进禁翻表, 就是不知道开发能否抽空加个提取文件名的功能 不然手动排除几千份文件名着实麻烦
