### ISSUE TITLE
软件”暂停”功能和“缓存文件继续翻译”存在的问题

### ISSUE THREAD

**Issue by mingxueyu** [NEKOparapa/AiNiee#222]
![是](https://github.com/user-attachments/assets/b81375ba-595d-4df1-ace4-41cdb33ab319)
软件在暂停恢复后，或者是翻译缓存文件开始时，会一次性将之前所有错误的翻译内容输出。结果就会导致服务器返送回来的文本与正处于软件期望翻译的文本不同，使得后续文本全部都会错位，软件会一直报错
希望作者能修复，将错误文本统一最后翻译之类的
谢谢作者大大

**Comment by NEKOparapa** [comment]
暂停后再重新翻译，底层逻辑是重新开始新的翻译。所以之前的出错的文本也会再一次翻译，一般来说用Sakura结果基本不变，也会再出错一次，只有等到拆分，情况才会好点。放在前面或者后面区别不大，你应该把出错翻译次数设置为0，才最效率，或者使用混合翻译。

**Comment by lzkgbld** [comment]
> 暂停后再重新翻译，底层逻辑是重新开始新的翻译。所以之前的出错的文本也会再一次翻译，一般来说用Sakura结果基本不变，也会再出错一次，只有等到拆分，情况才会好点。放在前面或者后面区别不大，你应该把出错翻译次数设置为0，才最效率，或者使用混合翻译。

反馈一下，就是如果中间终止翻译切引擎，会一直卡在正在进行任务，日志显示
Warning: 翻译任务已被暂停-----------------------

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
只能重新打开软件重新翻译

**Comment by NEKOparapa** [comment]
你要等全部线程取消完
