### ISSUE TITLE
[bug] html转译出现BUG

### ISSUE THREAD

**Issue by laulguo** [NEKOparapa/AiNiee#224]
{
        "text_index": 878,
        "translation_status": 1,
        "source_text": "Despite these serious shortcomings, early on 21 July, Zhukov issued two additional directives designed to strengthen Timoshenkoâ€™s counteroffensive. The first required the chief of Red Army Cavalry, General Gorodovikov, to reinforce a cavalry group already conducting operations toward Bobruisk on Army Group Centerâ€™s southern flank under the control of Kuznetsovâ€™s 21st Army. Specifically, Zhukov directed this group, which already consisted of 43rd and 47th Cavalry Divisions, to be reinforced by 32nd Cavalry Division.3 The second order required Groups Khomenko (30th Army), Kalinin (24th Army), and Kachalov (28th Army) to form tank groups consisting of 21 tanks each (ten T-34â€™s and 11 BTâ€™s or T-26â€™s) to support the riflemen as they advanced.4 At the time, Rokossovskyâ€™s group fielded a force of roughly 40 tanks, a far cry from the strong but unwieldy mechanized corps Red Army front commanders had at their disposal in previous operations.",
        "translated_text": "尽管存在这些严重缺陷，7月21日凌晨，朱可夫还是发布了两个额外的指令，旨在加强季莫申科的反攻。第一个指令要求红军骑兵总司令戈罗多维科夫将军加强一个已经在向鲍布鲁伊斯克方向进行作战的骑兵群，该骑兵群位于中央集团军的南翼，受库兹涅佐夫的第21集团军控制。具体来说，朱可夫指示这个已经由第43和第47骑兵师组成的集团，再加强第32骑兵师。3第二个命令要求科门科集团（第30集团军）、卡利宁集团（第24集团军）和卡恰洛夫集团（第28集团军）组建坦克集团，每个集团由21辆坦克组成（10辆T-34和11辆BT或T-26），以支持步兵前进。4当时，罗科索夫斯基的集团拥有大约40辆坦克，这与红军前线指挥官在前几次作战中拥有的强大但笨重的机械化军团相去甚远。",
        "html": "Despite these serious shortcomings, early on 21 July, Zhukov issued two additional directives designed to strengthen Timoshenkoâ€™s counteroffensive. The first required the chief of Red Army Cavalry, General Gorodovikov, to reinforce a cavalry group already conducting operations toward Bobruisk on Army Group Centerâ€™s southern flank under the control of Kuznetsovâ€™s 21st Army. Specifically, Zhukov directed this group, which already consisted of 43rd and 47th Cavalry Divisions, to be reinforced by 32nd Cavalry Division.<sup class=\"calibre41\"><a href=\"../Text/dummy_split_234.html#filepos2128155\" id=\"filepos660236\"><span><span class=\"calibre43\">3</span></span></a></sup> The second order required Groups Khomenko (30th Army), Kalinin (24th Army), and Kachalov (28th Army) to form tank groups consisting of 21 tanks each (ten T-34â€™s and 11 BTâ€™s or T-26â€™s) to support the riflemen as they advanced.<sup class=\"calibre41\"><a href=\"../Text/dummy_split_234.html#filepos2128532\" id=\"filepos660571\"><span><span class=\"calibre43\">4</span></span></a></sup> At the time, Rokossovskyâ€™s group fielded a force of roughly 40 tanks, a far cry from the strong but unwieldy mechanized corps Red Army <span><span class=\"italic\">front</span></span> commanders had at their disposal in previous operations.",
        "model": "deepseek-coder",
        "item_id": "id1244",
        "storage_path": "Barbarossa Derailed The German Advanve, Encirclement Battle, and the First and Second Soviet Counteroffensives, 10 July-24... (David Glantz) (Z-Library).epub",
        "file_name": "Barbarossa Derailed The German Advanve, Encirclement Battle, and the First and Second Soviet Counteroffensives, 10 July-24... (David Glantz) (Z-Library).epub"
    },
html出现问题
[输入.zip](https://github.com/user-attachments/files/16234983/default.zip)

**Comment by NEKOparapa** [comment]
哪里？

**Comment by laulguo** [comment]
> 哪里？什么问题？

看起来看是我的EPUB阅读器把注释拉上来了，应该是没问题的
