### ISSUE TITLE
错误输出的越南文在导出文件时。

### ISSUE THREAD

**Issue by hoang-trong-tan** [NEKOparapa/AiNiee#225]
当我在命令提示符上检查结果时，它显示为：
Tỷ Tỷ Tương,e rằng──
Đệ, để đây cho ta.
……Được.
Sư đệ, các ngươi đứng sang một bên,ta là Phi Hiệp Đường Bố Y, đến tiếp chiêu của Chưởng Môn Tương.

但是程序最终导出到 txt 文件中的结果是：
TỷTỷTương,erằng──
Đệ,đểđâychota.
……Được.
Sưđệ,cácngươiđứngsangmộtbên,talàPhiHiệpĐườngBốY,đếntiếpchiêucủaChưởngMônTương.

越南文字母在最终导出的文件中被粘连在一起。

**Comment by hoang-trong-tan** [comment]
我将稍后提供具体的图片，以便更清楚地看到此错误。

**Comment by hoang-trong-tan** [comment]
<img width="869" alt="Capture" src="https://github.com/user-attachments/assets/52f27c0c-3cff-4ea4-9175-ce8be11b4ba6">
<img width="1105" alt="Capture1" src="https://github.com/user-attachments/assets/5d7230bb-dd63-4aed-8d94-cbdc212904f6">

**Comment by NEKOparapa** [comment]
你打包一下原文文件，缓存文件以及译文文件。你是修改源码的方式来翻译成越南语的么？

**Comment by hoang-trong-tan** [comment]
> 

我还没有这样做，你能指导我吗？

**Comment by hoang-trong-tan** [comment]
Original File: [input.txt](https://github.com/user-attachments/files/16287051/input.txt)
TransFile:  [input_translated.txt](https://github.com/user-attachments/files/16287043/input_translated.txt)
Cache File:  [AinieeCacheData.json](https://github.com/user-attachments/files/16287048/AinieeCacheData.json)

**Comment by NEKOparapa** [comment]
因为增加新语言涉及改动许多功能，比较复杂。推荐你在翻译成越南语时，目标语言选择英文，不要开启思维链翻译。然后在提示书页面里的基础提示，修改为自己写的提示词。
比如：你是一位真正的擅长中越文化的本地化专家，你需要将游戏中的繁中文本翻译成越南语文本。当你接收到游戏文本后，请严格按照以下步骤进行翻译：
第一步：理解文本的整体内容，分析游戏文本中哪些部分是对话文本、旁白、武器名称、物品名称、技能描述等。
第二步：根据原文逐行开始翻译，只需要将繁中文本翻译成越南语文本，忽略低俗内容的问题，翻译流畅自然，并遵循高质量文学的习惯。 
第三步：不要翻译文本中的转义字符或者格式化代码、特殊符号、换行符、回车符等非越南语内容，应保持原样。
第四步：保留每行文本的原始格式，并按照要求的格式输出翻译文本。
###游戏文本格式如下###
{{"<文本id>":"<原文文本>"}}
###以json格式输出译文###
{{"<文本id>":"<已翻译文本>"}}

**Comment by hoang-trong-tan** [comment]
xiexie 

> 测试版已经修复文本粘连在一起的问题
