### ISSUE TITLE
请求地址完全自定义

### ISSUE THREAD

**Issue by OMEHAND** [NEKOparapa/AiNiee#227]
当前的代理平台那里的地址能否修改成完全自定义，现在还会在地址上作出补充，导致有些模型比如豆包的api地址无法使用

**Comment by NEKOparapa** [comment]
你本来打算填入的地址是？

**Comment by OMEHAND** [comment]
> 你本来打算填入的地址是？

https://ark.cn-beijing.volces.com/api/v3/chat/completions

**Comment by NEKOparapa** [comment]
首先，你填入https://ark.cn-beijing.volces.com/api就可以调用豆包的模型。其次，官方接口页面里就有接入豆包的页面？

**Comment by OMEHAND** [comment]
> 首先，你填入https://ark.cn-beijing.volces.com/api 就可以调用豆包的模型。其次，官方接口页面里就有接入豆包的页面？

好的感谢，原来是那个vol的，qwen那些也看到了
