### ISSUE TITLE
可以整合 mem0 到程序中吗？

### ISSUE THREAD

**Issue by yihuishou** [NEKOparapa/AiNiee#228]
[https://github.com/mem0ai/mem0](url) 看起来可以对关键词进行更好的补充的样子

**Comment by NEKOparapa** [comment]
额。它能干嘛

**Comment by yihuishou** [comment]
Mem0 为大型语言模型提供了一个智能、自我改进的内存层，主要是更好的记忆上下文吧

**Comment by NEKOparapa** [comment]
需要再了解一下这个项目，看看适不适合添加进ainiee

**Comment by daiaji** [comment]
类似RAG,但项目似乎是打算给LLM添加一个使用向量数据库的记忆装置，或许能缓解日语环境下的人称代词混乱问题。
