### ISSUE TITLE
[请求] 混合翻译设置能否提供多个代理平台选项

### ISSUE THREAD

**Issue by IMBAepsilon** [NEKOparapa/AiNiee#231]
在代理平台中，能不能同时存在多份配置
比如不同第三方代理，或者不同模型的配置方案

然后再混合翻译中可以设置依次调用

（因为众所周知的原因，不同的模型翻译效果、审查强度、价格，都有所区别，那么如果第一个模型效果不好，可以直接换下一个模型，而无需直接使用其他平台）

具体实现方案的话，一个简单的想法是做成，共用一个“代理平台”的入口，但是里面通过下拉菜单加载不同json配置，进而进行区分，同时标定序号（是否支持单独命名等等也可以考虑一下？）。然后在“混合翻译设置”中选择代理平台的话提供个二级选项选择具体配置之类的（提供个思路）

**Comment by NEKOparapa** [comment]
会加的，只不过不会很快

**Comment by NEKOparapa** [comment]
测试版已加
