### ISSUE TITLE
是否考虑支持Groq平台

### ISSUE THREAD

**Issue by Zebartin** [NEKOparapa/AiNiee#234]
[Groq](https://groq.com/)

注册登录后免费账号可白嫖，可用模型以及额度如下（llama-3.1-405b-reasoning目前不可用）：
![image](https://github.com/user-attachments/assets/92230b37-9799-4a63-ab2f-0b399a67820c)

**Comment by NEKOparapa** [comment]
代理平台填 https://api.groq.com/openai/v1 即可

**Comment by daiaji** [comment]
翻译质量咋样呢？
上次记得是llama3 RP不太行的程度。
