### ISSUE TITLE
[请求]能否为“角色介绍”添加和“提示字典”一样的导入/导出功能呢？

### ISSUE THREAD

**Issue by SakuraI-Nagakaze** [NEKOparapa/AiNiee#235]
如题，有时候在不同的作品中会采取不同的翻译，但是现在（在人名比较多的时候）进行逐个修改似乎比较困难，如果能够导入导出的话修改起来会比较方便（逃），既然提示字典已经实现了导入导出功能，那这边应该实现起来也不会很难吧（）

**Comment by NEKOparapa** [comment]
会加的，应该是json与xlsx格式，不过不会很快

**Comment by NEKOparapa** [comment]
测试版已加
