### ISSUE TITLE
使用中转api无法用使用claude模型？

### ISSUE THREAD

**Issue by Fujiwarz** [NEKOparapa/AiNiee#239]
[](url)
![QQ截图20240807193727](https://github.com/user-attachments/assets/c08f1c6d-f033-4c0d-a16d-7e4a2c6c88b6)
更换了几家中转网站都不行，但是gpt都可以

**Comment by ccjjyyy** [comment]
同问 傻卵官网用了十个虚拟号绑定不了 气死了 中转搞了半天
