### ISSUE TITLE
[请求]能否新增翻译Time Out的时间设置呢？

### ISSUE THREAD

**Issue by Zorz4** [NEKOparapa/AiNiee#247]
翻译使用本地SakuraLLM，出现过因为当次请求还未翻译完成時，程序已经判定请求Time Out重试，但因前次的翻译尚未处理完，导致后续每次请求皆逐步累积，每次都Time Out

**Comment by NEKOparapa** [comment]
这个可能是因为你行数或者tokens数太大了，你可以尝试调小一点，没多大影响，甚至准确率会更高
