### ISSUE TITLE
VN text提取文件使用AI翻译的时候会持续提醒有重复文本。

### ISSUE THREAD

**Issue by tidesz** [NEKOparapa/AiNiee#251]
![屏幕截图 2024-09-09 163616](https://github.com/user-attachments/assets/47f2a36d-ae13-43c7-bc19-d12805dd84ab)
![屏幕截图 2024-09-09 163728](https://github.com/user-attachments/assets/4c682ced-6a9f-48dc-91cb-dc6d9e0ec9a7)
如图所示。但是实际上提取出来的JSON文件里面就有固定的语句。
AI会持续翻译这个重复的语句，然后认定他是重复文本。

**Comment by NEKOparapa** [comment]
你用的是什么版本

**Comment by tidesz** [comment]
> 你用的是什么版本

4.66.7

**Comment by NEKOparapa** [comment]
新版没有这个检查了

**Comment by tidesz** [comment]
> 新版没有这个检查了

非常感谢
