### ISSUE TITLE
希望替换词典能导入xlsx文件

### ISSUE THREAD

**Issue by xf1223061663** [NEKOparapa/AiNiee#252]
如题，希望替换词典能导入xlsx文件。这对于需要替换上百个单词的萌新来说，相对更简单一些。处理json文件确实对萌新有难度。
希望大佬能照顾一下我们这些小萌新，导入xlsx功能真的很有价值！
万分感谢！如果能有的话，狠狠的打赏！

**Comment by NEKOparapa** [comment]
真的么，一会光速更新给你

**Comment by NEKOparapa** [comment]
[AiNiee4.74.2](https://github.com/NEKOparapa/AiNiee/releases/tag/AiNiee4.74.2) 更新了，导入的xlsx表格，第一行做表头不导入，导入第二行开始的第一列与第二列

**Comment by NEKOparapa** [comment]
让我小吃一惊，非常感谢你的赞助（爱心）
