### ISSUE TITLE
翻譯完后打不開

### ISSUE THREAD

**Issue by Raiter123** [NEKOparapa/AiNiee#255]
翻譯完后文件打不開
![image](https://github.com/user-attachments/assets/2b4eae7d-b78d-4fb5-b3b0-1b2f77b532d0)
[[OCR]_[Highland Denki] Dagon-chu! ~Cthulhu Fuumi (Gokubiryou) Shokushu Wakan Harenchi E Monogatari~_20240914_2000_translated.txt](https://github.com/user-attachments/files/17004931/OCR._.Highland.Denki.Dagon-chu.Cthulhu.Fuumi.Gokubiryou.Shokushu.Wakan.Harenchi.E.Monogatari._20240914_2000_translated.txt)

**Comment by NEKOparapa** [comment]
你在翻译什么

**Comment by Raiter123** [comment]
翻译umi-ocr 出來的小説

**Comment by NEKOparapa** [comment]
你ocr出来的小说能够正常打开么，以及你选对了翻译项目没

**Comment by Raiter123** [comment]
可以

**Comment by NEKOparapa** [comment]
你把原文件上传一下

**Comment by Raiter123** [comment]
[[OCR]_[Highland Denki] Dagon-chu! ~Cthulhu Fuumi (Gokubiryou) Shokushu Wakan Harenchi E Monogatari~_20240914_2000.zip](https://github.com/user-attachments/files/17009843/OCR._.Highland.Denki.Dagon-chu.Cthulhu.Fuumi.Gokubiryou.Shokushu.Wakan.Harenchi.E.Monogatari._20240914_2000.zip)

**Comment by NEKOparapa** [comment]
[o.zip](https://github.com/user-attachments/files/17010201/o.zip)
我翻完没看见这个问题
