### ISSUE TITLE
4.74.2 版本使用Sakura模型 top p参数问题

### ISSUE THREAD

**Issue by lolssjg** [NEKOparapa/AiNiee#256]
版本 4.74.2 翻译模型sakura-14b-qwen2beta-v0.9.2-iq4xs

最近感觉4.74.2 版本翻译出来的风格怪怪的

分别用4.74与4.74.2翻译相同的文本做对比发现确实有问题

查看日志发现

top_p的默认参数由以前版本的0.3变成了0.9

![PixPin_2024-09-16_07-09-58](https://github.com/user-attachments/assets/a55bf237-30fe-4446-94e4-9c8a32ad662c)

这个是4.74的版本，top_p默认为0.3

![PixPin_2024-09-16_07-10-19](https://github.com/user-attachments/assets/bce02c22-a0e1-418a-8279-fe459a1f9f51)

后面使用参数调整功能，勾选实时改变AI参数把top_p的参数改回0.3时日志输出的是0勾选实时改变AI参数把top_p的参数改回0.3时发现日志输出的是0.30000000000000004

![PixPin_2024-09-16_07-10-52](https://github.com/user-attachments/assets/f90b6f9f-c6a0-477b-9198-042939e5a389)

调整到0.2或者其他任意数值时都可以输出为0.X，只有调整到0.3时为0.30000000000000004

**Comment by NEKOparapa** [comment]
恩，确实，变量写错了，测试版已修
