### ISSUE TITLE
启用混合平台翻译

### ISSUE THREAD

**Issue by zero8524** [NEKOparapa/AiNiee#257]
麻烦作者了想咨询一下我的问题该如何解决，比如我想要好的翻译质量同时也能翻译敏感信息，那么我是否可以设定为首轮Gemin （有限制），次轮deepseek（无限制）翻译敏感信息，末轮Gemin。还是首轮Gemin （有限制），次轮deepseek（无限制）翻译敏感信息，就可以了。

**Comment by NEKOparapa** [comment]
首轮Gemin （有限制），次轮deepseek（无限制），后面随意了。一般活到第三轮都是·一些容易格式出错的文本，包含大量语气词之类

**Comment by zero8524** [comment]
感谢
