### ISSUE TITLE
MTool导出的Json相较于Translator++导出的Excel在翻译时会出现很多行数不一致的情况

### ISSUE THREAD

**Issue by OMEHAND** [NEKOparapa/AiNiee#258]
在使用MTool导出的JSON文件进行翻译时，会出现很多行数不符合的情况，即使增加重新次数、开启混合翻译，最终未翻译的行数也比较多。但是使用Translator++导出的Excel进行翻译，很少出现行数不符合的情况，大部分原文都能一次翻译成功。
在观察了MTool的导出文件后，发现MTool行数不符的原文中，大多是以下情况：

1. 包含特殊符号。原文中包含特殊符号，比如“\”、“（”等符号
![image](https://github.com/user-attachments/assets/e8fde54c-9e2f-4be3-b840-e94b10f26c0a)
![image](https://github.com/user-attachments/assets/0b70c8f2-cf2f-416e-bf9c-7f25689702b7)
2. 包含被截断的文本
![image](https://github.com/user-attachments/assets/cf734016-5bae-434a-8a3f-bde7901e0130)

请问大佬有针对这种情况的优化计划或者使用建议吗

**Comment by OMEHAND** [comment]
刚刚将翻译行数调整成了1行，对之前多次翻译后仍然有行数不一致问题的JSON片段进行了翻译，没有出现行数不符的问题。
大佬可否添加一项功能，在重试指定次数后，可以指定行数或者使用单行发送请求进行翻译。但是由于单行发送Prompt消耗的Token会成倍增加，所以希望再进行单行翻译的时候可以指定模型，这样相对于DeepSeek这种使用了缓存技术的模型来说，Token的消耗差距不会很大。
![image](https://github.com/user-attachments/assets/d603efb0-59f9-46ba-820d-de6eea49dfa9)

**Comment by NEKOparapa** [comment]
是这样的，两块软件提取规则不同，mtool会拆得很碎，所以容易出现合并，缺行。你不手动调，最后翻译行数也会自动变为1

**Comment by NEKOparapa** [comment]
你可以用混合翻译，末轮设置个ds

**Comment by OMEHAND** [comment]
好的感谢，我试一下

**Comment by OMEHAND** [comment]
> 是这样的，两块软件提取规则不同，mtool会拆得很碎，所以容易出现合并，缺行。你不手动调，最后翻译行数也会自动变为1

大佬能再问一下最后翻译行数为1的请求这块是单线程还是多线程的。我看ainiee界面上还是显示的原来的线程数，但是看终端请求的响应速度好像是单线程在执行。目前情况就是绝大部分的原文在很短时间内就翻译完成了，但是剩下的文本在很长时间内都没有翻译完成，已翻译行数也是在按照一个固定的时间间隔+1。
