### ISSUE TITLE
混合翻译能否翻译完带敏感信息的小说

### ISSUE THREAD

**Issue by zero8524** [NEKOparapa/AiNiee#259]
作者，您好还是老问题，初衷还是想使用翻译质量好的模型翻译的同时也使用不审计模型翻译敏感信息。现在碰到的情况如下：当使用单模型（qwen_有审计）针对带有敏感信息的小说翻译，模型返回会报错不翻译（这里用的是qwen模型）导致总是有几千行不会被翻译（占总进度大概只有1%左右）；添加混合翻译后，首轮（qwen）次轮以后使用deepseek作为翻译模型，但是剩余未翻译的进度更多了（4%）。我试了好几本带敏感信息的书都出现了这种情况，当前我的相关设置为：翻译轮次最大限制设置的为6，次论翻译平台deepseek设置里勾选了对半拆分。

**Comment by NEKOparapa** [comment]
剩余未翻译的文本不全是敏感信息的文本。你应该关注翻译结束了，最后是否能够全部翻译完成不，不行就加大轮次限制，和末轮改为强大且没有限制的模型更为妥当

**Comment by zero8524** [comment]
作者你说的这个能否翻译全部完成，要跟加大轮次限制可能跟翻译的文本量有关系，当文本量越少基本不会出现不会翻译完的情况。我现在在保证质量和时间效率（轮次限制低）的情况下都是显示翻译完成后，输出一个缓存文件将剩下的未翻译和敏感信息全交给新模型，感觉作者可以在这后面加个新的分支选项，类似像监测到有未翻译的文本是否交给新模型？

**Comment by NEKOparapa** [comment]
有这个功能，除了epub文件，其他没能成功翻译的会输出一个未翻译的文件

**Comment by zero8524** [comment]
好的，谢谢
