### ISSUE TITLE
Gemini API似乎能配置反代了。

### ISSUE THREAD

**Issue by daiaji** [NEKOparapa/AiNiee#260]
https://github.com/google-gemini/generative-ai-python/issues/188#issuecomment-2342355676

大哥支持一下吧，能搭建反代的平台很多，但能搭建代理的就少些。
实际上让API与形成绑定关系再使用的话，貌似能绕过日请求限制和分钟请求限制。

**Comment by NEKOparapa** [comment]
工作量有点多，而且没几个人用，先暂时不加了

**Comment by daiaji** [comment]
有空再加也行。

**Comment by Alexmalab** [comment]
反代没有卵用，只对generate_content函数生效，不对upload_file函数生效。你若像附带文件。则无效

**Comment by Hoshino-Yumetsuki** [comment]
> 反代没有卵用，只对generate_content函数生效，不对upload_file函数生效。你若像附带文件。则无效

直接通过 workers 或者其他方式反代整个 api 域名，这样也是可以的，反代的函数有效性主要取决于反代方式

**Comment by daiaji** [comment]
> 反代没有卵用，只对generate_content函数生效，不对upload_file函数生效。你若像附带文件。则无效

https://github.com/google-gemini/generative-ai-python/issues/610#issuecomment-2553355628
说是配置grpc代理就能全局代理，包括upload_file。

**Comment by Alexmalab** [comment]
> > 反代没有卵用，只对generate_content函数生效，不对upload_file函数生效。你若像附带文件。则无效
> 
> [google-gemini/generative-ai-python#610 (comment)](https://github.com/google-gemini/generative-ai-python/issues/610#issuecomment-2553355628) 说是配置grpc代理就能全局代理，包括upload_file。

有用是有用，但是我的应用场景是作为一个项目的模块扩展，全局代理让我的项目也走代理了不好；若他原生不支持代理，那就只能以独立服务的形式部署了
