### ISSUE TITLE
可以支持max_tokens和max_completion_tokens参数吗？

### ISSUE THREAD

**Issue by SaigyoujiYusora** [NEKOparapa/AiNiee#268]
如果使用本地llm的话会被默认token数量截断，找了好久也没找到koboldcpp有什么办法修改默认的（
但是openai文档里这个参数手动加进去就可以调整
https://platform.openai.com/docs/api-reference/chat/create#chat-create-max_tokens

**Comment by NEKOparapa** [comment]
这个参数能够对本地llm起作用么？虽然兼容了openai接口格式，但不一定支持所有参数。本地llm是能够设置推理的相关参数吧，而且ainiee发送的tokens是可以设置的

**Comment by SaigyoujiYusora** [comment]
> 这个参数能够对本地llm起作用么？虽然兼容了openai接口格式，但不一定支持所有参数。本地llm是能够设置推理的相关参数吧，而且ainiee发送的tokens是可以设置的

光修改设置里的tokens在请求的时候似乎不会带参数，要在concurrent_request_openai里手动加上max_tokens 才会变。
例如：
```
# 发送对话请求
                    try:
                        response = openaiclient.chat.completions.create(
                            model= configurator.model_type,
                            messages = messages ,
                            temperature=temperature,
                            top_p = top_p,                        
                            presence_penalty=presence_penalty,
                            frequency_penalty=frequency_penalty,
                            max_tokens = 1000,
                            )
```

**Comment by NEKOparapa** [comment]
max_tokens参数已经被弃用了，max_completion_tokens参数能够生效么

**Comment by SaigyoujiYusora** [comment]
目前来看ollama和koboldcpp好像都不支持max_completion_tokens，只支持max_tokens

**Comment by NEKOparapa** [comment]
接口版本不一致，暂时应该不会加了，你可以调小点行数，这样就不会被截断了
