### ISSUE TITLE
翻译问题，当我在翻译这本小说的时候，只会消耗token，翻译进度却一直为0

### ISSUE THREAD

**Issue by zero8524** [NEKOparapa/AiNiee#269]
[君临绝代.txt](https://github.com/user-attachments/files/17227669/default.txt)

**Comment by zero8524** [comment]
但实际上已经完成了翻译是吗

**Comment by zero8524** [comment]
尝试了一下，就是无法翻译，消耗了正常行数对应的token好几倍都不会显示翻译完，并切输出缓存文件和txt文件都只能看到进度只有一点点，请问，作者能解决这种情况吗？

**Comment by NEKOparapa** [comment]
消耗了正常行数对应的token好几倍是正常现象。我试了翻译你这个文本，是能够正常翻译的，只不过因为文本量巨大，你翻译速度慢，所以看起来翻译进度却一直为0
