### ISSUE TITLE
作者你好还是翻译问题

### ISSUE THREAD

**Issue by zero8524** [NEKOparapa/AiNiee#273]
作者你好，还是之前消耗token不翻译的问题，后续我又实验了一下，显示消耗了700w token，但是导出缓存文件和txt都没有显示翻译多少（消耗token这么多却只显示翻译了几百行），针对这段生肉文字我通过从两个不同网站爬取下来都会遇到这种问题，目前只有这本小说出现了这种情况。

**Comment by NEKOparapa** [comment]
你先截取一个小文本测试翻译一下。
