### ISSUE TITLE
建議提示字典功能預設是啟用的

### ISSUE THREAD

**Issue by trungXz** [NEKOparapa/AiNiee#278]
作者您好，因為輸入一堆字典後開翻，跑發現好像人名都沒按照字典設定，點查才發現這裡忘了勾。
建議這裡預設就是勾的…即使留白也不影響使用。

**Comment by NEKOparapa** [comment]
保存字典

**Comment by neavo** [comment]
> 作者您好，因為輸入一堆字典後開翻，跑發現好像人名都沒按照字典設定，點查才發現這裡忘了勾。 建議這裡預設就是勾的…即使留白也不影響使用。

最新测试版已默认开启
