### ISSUE TITLE
[BUG] Token 模式下，拆分重试时，有时候不会拆分到单行，导致翻译流程始终不能完成

### ISSUE THREAD

**Issue by neavo** [NEKOparapa/AiNiee#280]
目前观察到当剩余的句子比较短的时候，任务并不会拆分到单行

这样在翻译的最后阶段，有时候会有 `多个单行短句构成的任务` 反复重试然后反复失败

导致翻译流程始终不能完成，直到重试轮次耗尽，有时候在这个反复重试中花费的时间可能有数十分钟

总体来说不影响使用，但是体验比较差，会让用户觉得翻译卡死了

我大概看了一下代码，在进行拆分判断时，会保留一个token的固定值，这是否是为了兼容 -90 Token 的逻辑才导致的问题？

如果是的话，目前 Sakura 1.0 版本上下文长度已经比较宽裕了，不再需要对token进行严格的限制了，可以考虑在新版中移除固定 Token 数减值这个逻辑了

**Comment by NEKOparapa** [comment]
多个单句没有被拆分，应该是我把保底tokens设置太大，是20，应该调低的。最近添加针对sakura的计算代码，确实因为之前-90，每轮预计的任务数不准确，导致有一些没有被发送出去翻译，就直接进拆分了。

**Comment by NEKOparapa** [comment]
如果移除-90，那每次发送的tokens预计是512+90，服务端会不会爆阿

**Comment by neavo** [comment]
> 如果移除-90，那每次发送的tokens预计是512+90，服务端会不会爆阿

按 v1.0 版本的配置的话应该还好

之前需要比较严格的限制主要是因为启用了上下文量化，启用以后只要超了哪怕一个token应用就直接崩溃了

v1.0 版本以后显存比较宽裕了，现在已经没有使用上下文量化了，偶尔超一点也就卡一下，问题不大

我觉得可以先移除，然后再观察是否需要调整一键包的推荐配置

**Comment by NEKOparapa** [comment]
行
