### ISSUE TITLE
deepseek-chat的并发怎么开，我听别人说能开高并发快速翻译，我已经两个号四十个API填写进去了，但是好像不是一回事

### ISSUE THREAD

**Issue by sqsq37** [NEKOparapa/AiNiee#302]
deepseek-chat的并发怎么开，我听别人说能开高并发快速翻译，
我已经两个号四十个API填写进去了，速度和二十个的时候没有太大差别，好像和我理解的不是一回事
我看别人说是一个号一个API就能无上限并发了，请问是在哪里设置对应的参数

**Comment by sqsq37** [comment]
试了一下，是最大线程数吗，手动填写之后好像确实快了一大截

**Comment by NEKOparapa** [comment]
是的
