### ISSUE TITLE
[Q&A] 大量发送给那个种对话是否会触发OpenAI的内容安全限制

### ISSUE THREAD

**Issue by sean1832** [NEKOparapa/AiNiee#306]
你好，

首先这是一个非常非常牛逼的软件，但我很好奇 (担心) 如果我进行翻译的过程中，如果翻译的内容含有大量少儿不宜的信息，是否会触发OpenAI或其他公司的安全限制，导致封号？

**Comment by NEKOparapa** [comment]
少部分公司会，大部分不会

**Comment by nekomiya-hinata** [comment]
如果是逆向接口会经常触发
调用API基本上没什么事，但是4o-mini会经常拒绝翻译色色的内容

**Comment by sean1832** [comment]
好的好的，感谢🙏

我试试就用deepseek吧，openai的账号对我来说还蛮重要的😂。

**Comment by neavo** [comment]
> 好的好的，感谢🙏
> 
> 我试试就用deepseek吧，openai的账号对我来说还蛮重要的😂。

记得先充钱，充钱就不会被封，纯白嫖封号概率大

**Comment by sean1832** [comment]
> > 好的好的，感谢🙏
> 
> > 
> 
> > 我试试就用deepseek吧，openai的账号对我来说还蛮重要的😂。
> 
> 
> 
> 记得先充钱，充钱就不会被封，纯白嫖封号概率大

好的好的。我所有的账号都是充了的。正因如此才会担心封号。😂
