### ISSUE TITLE
請問目前有方法可以使用在自己的OpenAI帳號弄好的 Fine-tuned Model 嗎

### ISSUE THREAD

**Issue by oao0623** [NEKOparapa/AiNiee#332]

**Comment by neavo** [comment]
> _No description provided._

我没有实际使用过 OpenAI 的在线微调
不过我看了一下文档，根据我对文档的理解，使用微调模型和标准模型的区别只是模型的名称
那应该通过自定义接口就可以实现

**Comment by NEKOparapa** [comment]
就是把官方的接口地址填入就行

**Comment by oao0623** [comment]
感謝兩位大大回復。

我想應該是指5.0版的左側的 [接口管理] 中的 [自定義接口] 然後新增Fine-tuned完成的model ID，
像是：ft:gpt-3.5-turbo:your-model-name-yyyy-mm-dd

**Comment by NEKOparapa** [comment]
可以的
