### ISSUE TITLE
[Feature] 将模型列表从硬编码更改为从 api 的 models 接口获取

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [NEKOparapa/AiNiee#345]
api 提供商的模型有时会有更新，如果直接将模型名称使用 json 来直接写死在软件内的话会导致有其他模型需求的情况难以实现，比如使用高达 4000 rpm 的 gemini-1.5-flash-8b 或者其他模型的 latest 版本。并且 rpm 也不需要写死，由用户来决定即可

关于 api 可以根据提供商拆分模块，然后抽象出统一接口给翻译用。这样就可以针对性的更改某一个提供商的代码和 prompt 等，而不需要在一个文件内写死所有的提供商，文件路径如

```
platforms
├─authropic
├─gemini
├─openai
└─ ···
```

**Comment by NEKOparapa** [comment]
你是理解并知道rpm这些参数的，但我想考虑到的是小白用户。账号等级要保留，但为了照顾高级用户，可以增加速率设定界面，加个开关，可以覆盖账号等级的预设。
