### ISSUE TITLE
翻译文本与游戏内容不符，存在重复现象

### ISSUE THREAD

**Issue by xwxYa** [NEKOparapa/AiNiee#353]
![image](https://github.com/user-attachments/assets/92bc4ec3-31de-4cec-ad4b-cf7eaad8a0fa)
如图，再翻译文件中是正常的，但再游戏中经常会出现少少女、最最近、当当然等重复的词语，一开始我以为是角色口癖，但检查了翻译文件发现其与游戏内容不符，这是mtool的问题吗？

**Comment by neavo** [comment]
翻译器只能管到翻译文件，翻译文件是正常的那翻译器就正常的工作了，大概是 MTool 的问题

**Comment by NEKOparapa** [comment]
去mtool的dis群反馈给作者
