### ISSUE TITLE
请教一个关于译前和译后替换的问题

### ISSUE THREAD

**Issue by RRTX4090TI** [NEKOparapa/AiNiee#369]
用Sakura模型翻译主角名字为自定义的游戏文本里，比如翻译“\N[0001]の催眠にかかったビッチなフィオに触発されて、周囲にも二次的に広がる催眠で性に解放的になる”这句话，开启译前和以后替换，先把\N[0001]先替换为张三，整句翻译完成后用译后把张三替换回\N[0001]，这种情况下最后输出的正确翻译应该是“被\N[0001]催眠的婊子菲欧影响，周围的人也因为二次传播的催眠而对性变得开放”才对，而实际翻译结果却是“\N[0001]被中了催眠的婊子菲欧刺激到，周围的人也因为二次传播的催眠而变得性解放”，这明显是替换没生效才导致的翻译失误，请问这种情况属于bug吗？

**Comment by neavo** [comment]
> 用Sakura模型翻译主角名字为自定义的游戏文本里，比如翻译“\N[0001]の催眠にかかったビッチなフィオに触発されて、周囲にも二次的に広がる催眠で性に解放的になる”这句话，开启译前和以后替换，先把\N[0001]先替换为张三，整句翻译完成后用译后把张三替换回\N[0001]，这种情况下最后输出的正确翻译应该是“被\N[0001]催眠的婊子菲欧影响，周围的人也因为二次传播的催眠而对性变得开放”才对，而实际翻译结果却是“\N[0001]被中了催眠的婊子菲欧刺激到，周围的人也因为二次传播的催眠而变得性解放”，这明显是替换没生效才导致的翻译失误，请问这种情况属于bug吗？

可以先试试只译前替换，看看结果是否符合预期

**Comment by RRTX4090TI** [comment]
![QQ20241130-222113](https://github.com/user-attachments/assets/a7d363d9-0167-45ec-9e26-a4db5371ac76)

只开译前替换之后也不行，一开始我还以为是跟开着指令词典有冲突的原因，把指令词典关了也还是不行，我发现翻译的时候是直接忽略掉了\N[0001]这个代码

**Comment by RRTX4090TI** [comment]
![QQ20241130-224038](https://github.com/user-attachments/assets/00ed4cc4-0106-4b5c-a822-b388cd609c53)
还是不行，句首和句尾的是被直接忽略掉了，句种的则是被替换成了↓↓

**Comment by NEKOparapa** [comment]
是不是你开了代码拯救者

**Comment by neavo** [comment]
> ![QQ20241130-224038](https://private-user-images.githubusercontent.com/117467764/391243641-00ed4cc4-0106-4b5c-a822-b388cd609c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzgzNTAsIm5iZiI6MTczMjk3ODA1MCwicGF0aCI6Ii8xMTc0Njc3NjQvMzkxMjQzNjQxLTAwZWQ0Y2M0LTAxMDYtNGI1Yy1hODIyLWIzODhjZDYwOWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmE2ZmYwOTdiNjlkM2M2NTg2NmNjYjlkOTFhNDBjOGRkMGM5NDI4OGVkMzFiNDMyNGJiM2MxMGYyMTA2OTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BlR__EDVlWI2RveigFwZoHqdYtw64zmNxwViswEkaLc) 还是不行，句首和句尾的是被直接忽略掉了，句中的则是被替换成了↓↓

开了代码救星插件就不要自己处理代码了
你可以提供一个Actors.json文件放在输入目录内
代码救星插件会根据文件里的数据自动还原角色代码，具体参考 [这里](https://github.com/neavo/KeywordGacha/wiki/%E8%A7%92%E8%89%B2%E4%BB%A3%E7%A0%81%E8%BF%98%E5%8E%9F)

**Comment by RRTX4090TI** [comment]
> > ![QQ20241130-224038](https://private-user-images.githubusercontent.com/117467764/391243641-00ed4cc4-0106-4b5c-a822-b388cd609c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzgzNTAsIm5iZiI6MTczMjk3ODA1MCwicGF0aCI6Ii8xMTc0Njc3NjQvMzkxMjQzNjQxLTAwZWQ0Y2M0LTAxMDYtNGI1Yy1hODIyLWIzODhjZDYwOWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmE2ZmYwOTdiNjlkM2M2NTg2NmNjYjlkOTFhNDBjOGRkMGM5NDI4OGVkMzFiNDMyNGJiM2MxMGYyMTA2OTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BlR__EDVlWI2RveigFwZoHqdYtw64zmNxwViswEkaLc)还是不行，句首和句尾的是被直接忽略掉了，句中的则是被替换成了↓↓
> 
> 开了代码救星插件就不要自己处理代码了 你可以提供一个Actors.json文件放在输入目录内 代码救星插件会根据文件里的数据自动还原角色代码，具体参考 [这里](https://github.com/neavo/KeywordGacha/wiki/%E8%A7%92%E8%89%B2%E4%BB%A3%E7%A0%81%E8%BF%98%E5%8E%9F) 在开始翻译的时候控制台应该相关的有提示
> 
> 或者你也可以选择把代码救星也关了，完全由自己手动来处理文本内的代码

还真是开了这个，那如果要实现我一楼说的那种翻译效果的话，用你提供的这方法，代码这样写对吗
[
  {
    "id": 0001,
    "name": "张三", 
    "nickname": ""
  }
]

**Comment by neavo** [comment]
> > > ![QQ20241130-224038](https://private-user-images.githubusercontent.com/117467764/391243641-00ed4cc4-0106-4b5c-a822-b388cd609c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzgzNTAsIm5iZiI6MTczMjk3ODA1MCwicGF0aCI6Ii8xMTc0Njc3NjQvMzkxMjQzNjQxLTAwZWQ0Y2M0LTAxMDYtNGI1Yy1hODIyLWIzODhjZDYwOWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmE2ZmYwOTdiNjlkM2M2NTg2NmNjYjlkOTFhNDBjOGRkMGM5NDI4OGVkMzFiNDMyNGJiM2MxMGYyMTA2OTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BlR__EDVlWI2RveigFwZoHqdYtw64zmNxwViswEkaLc)还是不行，句首和句尾的是被直接忽略掉了，句中的则是被替换成了↓↓
> > 
> > 
> > 开了代码救星插件就不要自己处理代码了 你可以提供一个Actors.json文件放在输入目录内 代码救星插件会根据文件里的数据自动还原角色代码，具体参考 [这里](https://github.com/neavo/KeywordGacha/wiki/%E8%A7%92%E8%89%B2%E4%BB%A3%E7%A0%81%E8%BF%98%E5%8E%9F) 在开始翻译的时候控制台应该相关的有提示
> > 或者你也可以选择把代码救星也关了，完全由自己手动来处理文本内的代码
> 
> 还真是开了这个，那如果要实现我一楼说的那种翻译效果的话，用你提供的这方法，代码这样写对吗 [ { "id": "0001", "name": "张三", "nickname": "" } ]

标准的数据结果里 id 应该是个整型，所以不应该会有 \N[0001]，只应该有 \N[1] 才对，我不太确定你这个文本是什么情况

**Comment by RRTX4090TI** [comment]
> > > > ![QQ20241130-224038](https://private-user-images.githubusercontent.com/117467764/391243641-00ed4cc4-0106-4b5c-a822-b388cd609c53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NzgzNTAsIm5iZiI6MTczMjk3ODA1MCwicGF0aCI6Ii8xMTc0Njc3NjQvMzkxMjQzNjQxLTAwZWQ0Y2M0LTAxMDYtNGI1Yy1hODIyLWIzODhjZDYwOWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEzMFQxNDQ3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmE2ZmYwOTdiNjlkM2M2NTg2NmNjYjlkOTFhNDBjOGRkMGM5NDI4OGVkMzFiNDMyNGJiM2MxMGYyMTA2OTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BlR__EDVlWI2RveigFwZoHqdYtw64zmNxwViswEkaLc)还是不行，句首和句尾的是被直接忽略掉了，句中的则是被替换成了↓↓
> > > 
> > > 
> > > 开了代码救星插件就不要自己处理代码了 你可以提供一个Actors.json文件放在输入目录内 代码救星插件会根据文件里的数据自动还原角色代码，具体参考 [这里](https://github.com/neavo/KeywordGacha/wiki/%E8%A7%92%E8%89%B2%E4%BB%A3%E7%A0%81%E8%BF%98%E5%8E%9F) 在开始翻译的时候控制台应该相关的有提示
> > > 或者你也可以选择把代码救星也关了，完全由自己手动来处理文本内的代码
> > 
> > 
> > 还真是开了这个，那如果要实现我一楼说的那种翻译效果的话，用你提供的这方法，代码这样写对吗 [ { “id”： “0001”， “name”： “张三”， “nickname”： “” } ]
> 
> 标准的数据结果里 id 应该是个整型，所以不应该会有 \N[0001]，只应该有 \N[1] 才对，我不太确定你这个文本是什么情况
我在游戏文件夹里找到现成的Actors.json了，不用自己写了，感谢大佬花费时间帮我解决了问题
