### ISSUE TITLE
`CodeSaver`插件优化建议，经测试有效。

### ISSUE THREAD

**Issue by energyc99** [NEKOparapa/AiNiee#377]
问题：

```
{placeholder1}【{placeholder2}】{placeholder3} それから･･･{placeholder4}が死んだ後、{placeholder5}に抵抗する{placeholder6}ノルヴァーナのレジスタンス達を{placeholder7}が助けて欲しい。

翻译这段日文，占位符不翻译。
```

回答：

```
`{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的诺尔瓦纳抵抗者们。`
```

问题：

```
缺少`placeholder6`
```

回答：

```
抱歉，我之前的回答中遗漏了`{placeholder6}`。以下是完整翻译：

`{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的{placeholder6}诺尔瓦纳的抵抗者们。`
```

上面的模型提示词中，原文中的占位符从原来的`↓↓`替换为了`{placeholder123}`，这样大模型更容易识别到占位符，而且占位符间有序号标识。

可以在检查翻译结果时，如果缺少占位符，就在提示词中携带缺少的占位符名称，以此来获取正确的译文。

**Comment by neavo** [comment]
> 问题：
> 
> ```
> {placeholder1}【{placeholder2}】{placeholder3} それから･･･{placeholder4}が死んだ後、{placeholder5}に抵抗する{placeholder6}ノルヴァーナのレジスタンス達を{placeholder7}が助けて欲しい。
> 
> 翻译这段日文，占位符不翻译。
> ```
> 
> 回答：
> 
> ```
> `{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的诺尔瓦纳抵抗者们。`
> ```
> 
> 问题：
> 
> ```
> 缺少`placeholder6`
> ```
> 
> 回答：
> 
> ```
> 抱歉，我之前的回答中遗漏了`{placeholder6}`。以下是完整翻译：
> 
> `{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的{placeholder6}诺尔瓦纳的抵抗者们。`
> ```
> 
> 上面的模型提示词中，原文中的占位符从原来的`↓↓`替换为了`{placeholder123}`，这样大模型更容易识别到占位符，而且占位符间有序号标识。
> 
> 可以在检查翻译结果时，如果缺少占位符，就在提示词中携带缺少的占位符名称，以此来获取正确的译文。

现在用的 ↓↓ 也是多番测试以后得到的相对优解，晚点我也测一下{placeholder*}

**Comment by neavo** [comment]
> 问题：
> 
> ```
> {placeholder1}【{placeholder2}】{placeholder3} それから･･･{placeholder4}が死んだ後、{placeholder5}に抵抗する{placeholder6}ノルヴァーナのレジスタンス達を{placeholder7}が助けて欲しい。
> 
> 翻译这段日文，占位符不翻译。
> ```
> 
> 回答：
> 
> ```
> `{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的诺尔瓦纳抵抗者们。`
> ```
> 
> 问题：
> 
> ```
> 缺少`placeholder6`
> ```
> 
> 回答：
> 
> ```
> 抱歉，我之前的回答中遗漏了`{placeholder6}`。以下是完整翻译：
> 
> `{placeholder1}【{placeholder2}】{placeholder3} 然后……在{placeholder4}死后，希望{placeholder7}能帮助抵抗{placeholder5}的{placeholder6}诺尔瓦纳的抵抗者们。`
> ```
> 
> 上面的模型提示词中，原文中的占位符从原来的`↓↓`替换为了`{placeholder123}`，这样大模型更容易识别到占位符，而且占位符间有序号标识。
> 
> 可以在检查翻译结果时，如果缺少占位符，就在提示词中携带缺少的占位符名称，以此来获取正确的译文。

测下来Sakura是不行的，基本上全都丢了

**Comment by NEKOparapa** [comment]
可以分开场景，分Sakura和其他

**Comment by neavo** [comment]
> 可以分开场景，分Sakura和其他

关键其他模型我也不怎么用，那就没人维护

**Comment by paul0728** [comment]
不好意思是否能請問一下CodeSaver作用到底為何?一般而言翻譯的時候不都應該要避開翻譯到程式碼的部分嗎?而看敘述CodeSaver會保留程式碼的部分(不知道有沒有理解錯誤)。

**Comment by neavo** [comment]
> 不好意思是否能請問一下CodeSaver作用到底為何?一般而言翻譯的時候不都應該要避開翻譯到程式碼的部分嗎?而看敘述CodeSaver會保留程式碼的部分(不知道有沒有理解錯誤)。

以内嵌模式翻译的时候，要保留文本中混杂的代码，要不然有可能会影响游戏本身的代码逻辑，让游戏出错或者干脆跑不起来

**Comment by paul0728** [comment]
> > 不好意思是否能請問一下CodeSaver作用到底為何?一般而言翻譯的時候不都應該要避開翻譯到程式碼的部分嗎?而看敘述CodeSaver會保留程式碼的部分(不知道有沒有理解錯誤)。
> 
> 以内嵌模式翻译的时候，要保留文本中混杂的代码，要不然有可能会影响游戏本身的代码逻辑，让游戏出错或者干脆跑不起来

可是舉例來說像是mtool取出來的文本好了，保留原文程式碼然後在譯文當中跟原文一模一樣，與直接從檔案中刪除掉的意義不是相同嗎?反正都是要避開翻譯，留著不是反而增加風險?

**Comment by neavo** [comment]
> > > 不好意思是否能請問一下CodeSaver作用到底為何?一般而言翻譯的時候不都應該要避開翻譯到程式碼的部分嗎?而看敘述CodeSaver會保留程式碼的部分(不知道有沒有理解錯誤)。
> > 
> > 
> > 以内嵌模式翻译的时候，要保留文本中混杂的代码，要不然有可能会影响游戏本身的代码逻辑，让游戏出错或者干脆跑不起来
> 
> 可是舉例來說像是mtool取出來的文本好了，保留原文程式碼然後在譯文當中跟原文一模一樣，與直接從檔案中刪除掉的意義不是相同嗎?反正都是要避開翻譯，留著不是反而增加風險?

你错误的理解了 `代码段` 这个词的含义
`代码段` 指的并不是单独的一条全是代码的文本，而是混杂在普通文本内的代码。

举个例子：

```python
火、水、風、土属性攻撃で受けるダメージを半減する。\c[3]※氷は半減しない
->
火、水、风、土属性攻击所受伤害减半。\c[3]※冰属性伤害不减半。
```

这里的 `\c[3]` 就是颜色代码，在翻译的时候也需要正确的保留，要不然就丢失了颜色信息
mtool 里理论上不会出现包含 `代码段`，因为它会从代码处将其切分为多段文本，比如上面的例子：

```python
火、水、風、土属性攻撃で受けるダメージを半減する。\c[3]※氷は半減しない
->
火、水、風、土属性攻撃で受けるダメージを半減する。
+
※氷は半減しない
```

所以 mtool 不需要处理这类问题，代价就是因为句子被切的很零碎，翻译质量会相对较低
这个插件是只对 T++ 项目生效的

**Comment by paul0728** [comment]
> > > > 不好意思是否能請問一下CodeSaver作用到底為何?一般而言翻譯的時候不都應該要避開翻譯到程式碼的部分嗎?而看敘述CodeSaver會保留程式碼的部分(不知道有沒有理解錯誤)。
> > > 
> > > 
> > > 以内嵌模式翻译的时候，要保留文本中混杂的代码，要不然有可能会影响游戏本身的代码逻辑，让游戏出错或者干脆跑不起来
> > 
> > 
> > 可是舉例來說像是mtool取出來的文本好了，保留原文程式碼然後在譯文當中跟原文一模一樣，與直接從檔案中刪除掉的意義不是相同嗎?反正都是要避開翻譯，留著不是反而增加風險?
> 
> 你错误的理解了 `代码段` 这个词的含义 `代码段` 指的并不是单独的一条全是代码的文本，而是混杂在普通文本内的代码。
> 
> 举个例子：
> 
> ```python
> 火、水、風、土属性攻撃で受けるダメージを半減する。\c[3]※氷は半減しない
> ->
> 火、水、风、土属性攻击所受伤害减半。\c[3]※冰属性伤害不减半。
> ```
> 
> 这里的 `\c[3]` 就是颜色代码，在翻译的时候也需要正确的保留，要不然就丢失了颜色信息 mtool 里理论上不会出现包含 `代码段`，因为它会从代码处将其切分为多段文本，比如上面的例子：
> 
> ```python
> 火、水、風、土属性攻撃で受けるダメージを半減する。\c[3]※氷は半減しない
> ->
> 火、水、風、土属性攻撃で受けるダメージを半減する。
> +
> ※氷は半減しない
> ```
> 
> 所以 mtool 自然不需要处理这类问题，代价就是因为句子被切的很零碎，翻译质量会相对较低
> 
> 这个插件是只对 T++ 项目生效的 T++ 会将这些文本内的 `代码段` 按原文保留下来，在翻译的时候也就需要正确的保留这些 `代码段`
> 
> 具体工作原理可以看 wiki https://github.com/NEKOparapa/AiNiee/wiki/CodeSaver

懂了，感謝詳細解釋!
