### ISSUE TITLE
新版codesaver会导致速度变慢

### ISSUE THREAD

**Issue by alan42521** [NEKOparapa/AiNiee#384]
在5.2.1版本，打开codesaver相较5.2版本速度变慢了许多，几乎降到了原来的一半

**Comment by alan42521** [comment]
# SPACE_PATTERN + r"\r\n" + SPACE_PATTERN,                                    # 换行符 \r\n，因为 SPACE_PATTERN 中已包含换行符，所以不需要再次匹配
        # SPACE_PATTERN + r"\n" + SPACE_PATTERN,                                      # 换行符 \n，因为 SPACE_PATTERN 中已包含换行符，所以不需要再次匹配
        我实验了一下，好像是这两行注释掉的影响

**Comment by neavo** [comment]
> 在5.2.1版本，打开codesaver相较5.2版本速度变慢了许多，几乎降到了原来的一半

是指翻译速度慢还是预处理文本时生成任务的速度慢

**Comment by alan42521** [comment]
翻译速度，不开能到240t/s,开了以后不到100t/s了

**Comment by neavo** [comment]
> 翻译速度，不开能到240t/s,开了以后不到100t/s了

理论上这里只影响预处理，不会影响翻译本身的流程，留个样本吧，晚点我测试一下

**Comment by alan42521** [comment]
[data.zip](https://github.com/user-attachments/files/18134934/data.zip)

**Comment by alan42521** [comment]
[data.zip](https://github.com/user-attachments/files/18134936/data.zip)

**Comment by neavo** [comment]
> ```
>     # SPACE_PATTERN + r"\r\n" + SPACE_PATTERN,                                    # 换行符 \r\n，因为 SPACE_PATTERN 中已包含换行符，所以不需要再次匹配
>     # SPACE_PATTERN + r"\n" + SPACE_PATTERN,                                      # 换行符 \n，因为 SPACE_PATTERN 中已包含换行符，所以不需要再次匹配
> 
>     我实验了一下，好像是这两行注释掉的影响
> ```

这两行改成这样再试试看：

```python
"" + r"\r" + "",
"" + r"\n" + "",
```

**Comment by alan42521** [comment]
也可以，其实把注释去掉速度都能回复

**Comment by neavo** [comment]
> 也可以，其实把注释去掉速度都能回复

ok
修正代码已经提交上去了，请评估一下是否需要再发一版 @NEKOparapa

**Comment by NEKOparapa** [comment]
> > 也可以，其实把注释去掉速度都能回复
> 
> ok
> 
> 修正代码已经提交了
> 
> 请评估一下是否需要再发一版 #385 @NEKOparapa
> 
> ![QQ截图20241214193216](https://private-user-images.githubusercontent.com/998676/395776027-a96c2be9-dd51-4c65-b95e-8db9820b2cbb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxODEzMTAsIm5iZiI6MTczNDE4MTAxMCwicGF0aCI6Ii85OTg2NzYvMzk1Nzc2MDI3LWE5NmMyYmU5LWRkNTEtNGM2NS1iOTVlLThkYjk4MjBiMmNiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNFQxMjU2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTA0OWFhYzg2YTM0Mjk3NWQ5NzI4MWU2ZWVkYjkxMjJjNDFmZTEyNmE3YmMwM2MwZDEzZjQ2YWM5ZmUxNDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LLI61f14qOYL7d9-LICPvJBT0f2ggliSNeoKpuAXI_0)

嗯
