### ISSUE TITLE
codesaver将还原失败的代码进行单独重翻

### ISSUE THREAD

**Issue by alan42521** [NEKOparapa/AiNiee#390]
不少代码会在还原的时候没还原成功变成↓↓，这些代码量还挺大的，希望可以自动重翻

**Comment by NEKOparapa** [comment]
@neavo  建议考虑一下没能全部回复↓↓的，按顺序还原了，但错误列表仍然输出

**Comment by neavo** [comment]
> @neavo 建议考虑一下没能全部回复↓↓的，按顺序还原了，但错误列表仍然输出

这反而会让错误难以检索：

本来直接在 T++ 里全局搜索 ↓↓ 即可，变成了要在错误列表反复复制粘贴搜索

**Comment by NEKOparapa** [comment]
额，确实

**Comment by neavo** [comment]
> 不少代码会在还原的时候没还原成功变成↓↓，这些代码量还挺大的，希望可以自动重翻

可以手动重翻，T++里批量搜索一下占位符，然后把这些错误的条目都清了，然后重新导出，只翻这些，记得换个模型

自动重翻意义不大，因为同样的设置下，重翻大概率还是错的
