### ISSUE TITLE
请求添加模拟上下文功能，以达到对在线大模型的破限能力提升

### ISSUE THREAD

**Issue by FFei-Zhou** [NEKOparapa/AiNiee#395]
大佬您好，感谢您的开源，软件**非常非常好用**。
但是在我使用Gemini时遇到一些问题，我在**酒馆-SillyTavern**中，这些问题通常是可以解决的，因此提出功能更新建议。

请求添加类似于SillyTavern预设（下方有截图）那样可以模拟上下文，更高自由的提示词自定义，酒馆中可以模拟上下文，不限于系统提示，可以模拟用户发送及AI回复，可以让AI模拟回复一些破限词防止AI委婉或是输出截断的问题，这种不仅对Gemini有效，其他在线模型均可使用。

另外，Gemini的审核还有输入和输出审核，输出审核可以通过提示词解决，输入审核（审核模型会审核用户发送的最后一条消息是否有敏感词汇）有一种解决方案，就是让发送的上下文，最后一条是AI的回复，我们可以拟造一条超短的，不影响AI输出质量的文本，让系统认为没有用户输入，用户是直接点击的RUN，这样可以百分百跳过输入审核。

酒馆上下文排序功能参考，这是可以拖动，进行提示词排序，通常越重要的文本，深度越深，位置越低。
![image](https://github.com/user-attachments/assets/5f5bc14c-bf2c-44d0-a867-e9af8e284941)
同时还可以设置消息归属和深度判断方法（相对就是纯按排序来，还可以选择聊天中，设置深度来强制文本位置，一般来说有相对就够了）
![image](https://github.com/user-attachments/assets/acc29be6-adac-450f-a574-695c9b45c0e4)

**感谢大佬开源，希望得到大佬的回复！**

**Comment by NEKOparapa** [comment]
没必要做第二个酒馆，翻译工具和聊天工具的需求不一样

**Comment by NEKOparapa** [comment]
破限能力是重要的考虑因素，但在批量翻译场景下，要优先做好翻译能力，再考虑破限方式。

**Comment by NEKOparapa** [comment]
不过最重要一点是，写这个自由组合prompt的ui与功能。工作量巨大且使用人少，光现在的提示词优化，大家没什么需求都不很常用

**Comment by FFei-Zhou** [comment]
> 没必要做第二个酒馆，翻译工具和聊天工具的需求不一样

大佬可能是我没有讲到重点，重点是Gemini的**输入审核**

大佬，Gemini不是本体进行审核，它有一个**输入审核**的机制，这个机制可以通过模拟聊天记录中最后一句的回复方为AI，这样就可以绕开输入审核进行破限，不然的话，很多游戏文本是还没送到模型那里就会有一个"OTHER"报错过来。

如果可以的话，只需要一个**最后一句是AI回复的小功能就行**这个功能算是输入破限的核心了。

**Comment by NEKOparapa** [comment]
就是预输入模型回复，这个方法很早就用了，当时Google都还没支持，后面更新会给Google补一个

**Comment by FFei-Zhou** [comment]
> > 只需要一个**最后一句是AI回复的小功能就行**这个功能算是Gemini输入破限的核心了
> 
> "只需要一个最后一句是AI回复的小功能就行这个功能算是Gemini输入破限的核心了"你这句话有其他项目的成功案例作为依据吗？

Gemini的API是免费使用的，少侠自己尝试一下就知道了，可以输入一大段小黄文，百分百爆OTHER错误
然后你再调整最后一句为AI的回复，tokens随便有一个都行，这段小黄文就被传入上下文了，可以正常生成...

**Comment by FFei-Zhou** [comment]
> 就是预输入模型回复，这个方法很早就用了，当时Google都还没支持，后面更新会给Google补一个

**感谢大佬！期待您的更新！**

**Comment by FFei-Zhou** [comment]
> > Gemini的API
> 
> Gemini的API免费额度太少，而且审查严重。但如果能用预输入模型回复hack审查那将是极好的

还好吧，并不少，**一个模型**每天大概是**100-150次**，基本上使用**2.0flash**和**exp1206**这两个模型，也就差不多一个API每天可以使用200轮。
我有4个API，写个脚本轮询，每次翻译的文本行数拉高，根本用不完。
我之前都是在写脚本和预设，使用酒馆半自动翻译，还没遇到过4个API全部用完的情况。

**输入**审核通过预输入模型回复，可以百分百避免。
**输出**审核才是比较难应付的，没有上下文模拟的话，只能通过系统提示词分割输出tokens降低截断概率，拉高温度和topK，提高文本随机性然后roll回复过审核（**简单来说就是时间换过审**），目前确实是没有百分百通过审核的办法...

**Comment by FFei-Zhou** [comment]
> > > > Gemini的API
> > > 
> > > 
> > > Gemini的API免费额度太少，而且审查严重。但如果能用预输入模型回复hack审查那将是极好的
> > 
> > 
> > 还好吧，并不少，**一个模型**每天大概是**100-150次**，基本上使用**2.0flash**和**exp1206**这两个模型，也就差不多一个API每天可以使用200轮。 我有4个API，写个脚本轮询，每次翻译的文本行数拉高，根本用不完。 我之前都是在写脚本和预设，使用酒馆半自动翻译，还没遇到过4个API全部用完的情况。
> > **输入**审核通过预输入模型回复，可以百分百避免。 **输出**审核才是比较难应付的，没有上下文模拟的话，只能通过系统提示词分割输出tokens降低截断概率，拉高温度和topK，提高文本随机性然后roll回复过审核（**简单来说就是时间换过审**），目前确实是没有百分百通过审核的办法...
> 
> 我之前的vertex-ai的Gemini的api直接被强行关掉了。必须添加外国信用卡防止滥用
> 
> `Billing account for project '21464XXXX' is not found. Billing must be enabled for activation of service(s)`
> 
> 最近有三个月的免费试用google cloud 包含2.0flash，也是需要强行外国信用卡验证身份的。
> 
> 所以说现在国内Gemini用的人极少，相关需求也很少，“不做恶”的google时不时恶心下被地区歧视的用户。
> 
> 以前用google Bard的时候还得套洋葱头

vertex-ai我不清楚，我是直接在**google ai studio**申请的API，第四个新号封了我一次项目，但是写了篇小作文表明自己个人使用，一个小时就给我解封了。
我也**没绑卡**，至于地区限制，在huggingface借用免费的服务器部署一个反代就好了，没有魔法一样用.

**Comment by NEKOparapa** [comment]
看了一下代码，发现已经加了，现在就是带有预输入的

**Comment by FFei-Zhou** [comment]
> 看了一下代码，发现已经加了，现在就是带有预输入的

这样吗😂，我没看到这个功能，就以为没有，所以一直用的本地模型，谢谢大佬，给您添麻烦了，抱歉。
