### ISSUE TITLE
deepseek翻译失效

### ISSUE THREAD

**Issue by GuGuMao8698** [NEKOparapa/AiNiee#396]
deepseek无法翻译，返回全部为空。
<img width="278" alt="屏幕截图 2024-12-31 213048" src="https://github.com/user-attachments/assets/33d0bf0a-8ebb-4d48-a6cc-acd90daeba06" />

**Comment by GuGuMao8698** [comment]
deepseek—V3更新后发现的问题。

**Comment by philipzha** [comment]
我也遇到了
![image](https://github.com/user-attachments/assets/8fff64ed-d5b5-4dfe-b1e5-2638fd108902)

**Comment by NEKOparapa** [comment]
已经恢复正常了
