### ISSUE TITLE
要不要把项目的名字给正式改成 AiNiee？

### ISSUE THREAD

**Issue by AkiraChisaka** [NEKOparapa/AiNiee#70]
咱在想，要不要去掉 chatgpt，把这个项目的名字给改成 AiNiee？

因为，现在已经有了新的使用 Gemini Pro 以及 SakuraLLM 的功能。而且，似乎其实 AiNiee 从一开始就没有在用 ChatGPT，而是在直接连接 GPT 的 API。因此，貌似 AiNiee 从一开始就跟 ChatGPT 这个项目的关系不大。

所以感觉把项目的名字就使用 **AiNiee** 最合适。而且，像 MTool 什么的一样，感觉名字只有一个词看起来很专业的样子。

题外话，如果 AiNiee 这个名字是个缩写的话，全称可以是 **Artificial Intelligence Narrative Interpretation and Exploration Engine** 的样子呢！酷炫！

**Comment by NEKOparapa** [comment]
主页的logo不知道换成啥样好，暂时舍不得这个充满生产力的logo，你有什么想法么

**Comment by AkiraChisaka** [comment]
> 主页的logo不知道换成啥样好，暂时舍不得这个充满生产力的logo，你有什么想法么

换成 Ai 在前面 Niee 在后面怎么样？

这种感觉：

![logo](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/47231500/d07e8646-a2e6-4efc-97c4-7a5c0d318fa6)

![logo (1)](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/47231500/fb418b2c-f33d-49ad-b3db-3bb0a2aca62f)

或者 Aiiiii 长一点？

![logo (2)](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/47231500/581deeae-d803-4c87-aa5a-4a10df4f31af)

**Comment by NEKOparapa** [comment]
不错不错，就用第二张吧

**Comment by AkiraChisaka** [comment]
好耶！

**Comment by AkiraChisaka** [comment]
名字升级啦~！

有时间把这里也改一下吧

![image](https://github.com/NEKOparapa/AiNiee-chatgpt/assets/47231500/5ba7749a-e7d3-41d4-87ec-5f234dd58e60)

应该在 Repo 的设置里就可以改，理论上不会影响任何东西。因为旧的链接还是会自动导航到新的名字上。

**Comment by NEKOparapa** [comment]
后面发布下一个新版本再全部改了

**Comment by AkiraChisaka** [comment]
好耶！

**Comment by AkiraChisaka** [comment]
正式改名成 AiNiee 了呢！

好耶！
