### ISSUE TITLE
Error: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.163.42:443: socket is null

### ISSUE THREAD

**Issue by as176590811** [NEKOparapa/AiNiee#78]
📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.

[INFO] 当前工作目录是: E:\Translate\AiNiee-chatgpt4.61

[INFO] 模型选择是: gemini-pro

[INFO] 正在测试第1个API KEY：**********

[INFO] 当前发送内容：
 ['你是我的女朋友欣雨。接下来你必须以女朋友的方式向我问好']

Error: key： ********* 请求出现问题！错误信息如下
Error: Deadline of 60.0s exceeded while calling target function, last exception: 503 failed to connect to all addresses; last error: UNKNOWN: ipv4:172.217.163.42:443: socket is null

[INFO] 全部API KEY测试结果--------------
第1个 API KEY：********** 测试结果：失败
[INFO] 存在API KEY测试失败！！！！
libpng warning: iCCP: cHRM chunk does not match sRGB

**Comment by NEKOparapa** [comment]
尝试开一下代理

**Comment by as176590811** [comment]
> 尝试开一下代理

试过了，还是一样。
我已经找到临时解决方案，就是将代码 genai.configure(api_key=apikey) 修改为genai.configure(api_key=apikey, transport='rest')
genai.configure(api_key= API_key_list[i])修改为 genai.configure(api_key= API_key_list[i], transport='rest')

**Comment by NEKOparapa** [comment]
哦，这样，厉害。你是直接编译运行源文件出现的问题么？

**Comment by as176590811** [comment]
> 哦，这样，厉害。你是直接编译运行源文件出现的问题么？

不是，我用的是你编译好的，但显示这错误，我就下载源码来运行啦

**Comment by NEKOparapa** [comment]
谢谢反馈，看看以后还有人会遇到类似问题不，要是还有，就用一下你的解决方案

**Comment by Gavin-Lxx** [comment]
太强了，我也是一模一样的报错，以为是vpn的问题。按照你的方法成功了！感谢
