### ISSUE TITLE
Check the `response.prompt_feedback` to see if the prompt was blocked.

### ISSUE THREAD

**Issue by UNSUnicorn** [NEKOparapa/AiNiee#81]
谷歌ai翻译。翻译中频繁的出现The `response.parts` quick accessor only works for a single candidate, but none were returned. Check the `response.prompt_feedback` to see if the prompt was blocked.可以问下是什么原因吗？

**Comment by NEKOparapa** [comment]
被道德审查了，谷歌是这样的，只能用不同的号来请求，直到他松口。或者审查不通过的拿其他平台来翻译
