### ISSUE TITLE
[feature request] 支持翻译 `srt` 或 `vtt` 之类的字幕文件

### ISSUE THREAD

**Issue by shoucandanghehe** [NEKOparapa/AiNiee#82]

**Comment by NEKOparapa** [comment]
有参考文件么

**Comment by shoucandanghehe** [comment]
```srt
1
00:00:00,000 --> 00:00:02,500
这是第一条字幕的文本。

2
00:00:02,501 --> 00:00:05,000
这是第二条字幕的文本。

3
00:00:05,001 --> 00:00:10,000
或者还有多行
字幕的形式
```
行号
起始时间 --> 结束时间
字幕内容
空行

基本就这样
可能少数会有HTML标签（感觉直接原样喂ai就行）

**Comment by shoucandanghehe** [comment]
应该都有现成的库能直接薅纯文本出来）

**Comment by NEKOparapa** [comment]
这种字幕文件通常是用什么工具制作的？以及有没有具体的示例文件？我没了解过这种文件

**Comment by shoucandanghehe** [comment]
一般用的多的是[Aegisub](https://aegisub.org/)吧
或者国产的[ArcTime](https://arctime.cn/index.html)之类
具体文件我就找到这一个非NSFW的（[录制.zip](https://github.com/NEKOparapa/AiNiee/files/14212032/default.zip)

**Comment by nolandra58** [comment]
https://github.com/sh2288/transer
这个可以直接翻译srt和ass,不过目前只有测试版可以

**Comment by tisapphire** [comment]
srt不好弄，我拿自己写的脚本弄srt会丢失时间戳
转换成lrc文件倒是直接可以了

**Comment by NEKOparapa** [comment]
已支持
