### ISSUE TITLE
100.1%

### ISSUE THREAD

**Issue by snowandrain** [NEKOparapa/AiNiee#86]
![image](https://github.com/NEKOparapa/AiNiee/assets/22421823/c1ff2079-a1d4-4ccc-8578-4dad2ea1a5b4)

**Comment by snowandrain** [comment]
> 真是尴尬的bug，能描述一下出现的情况么，以及还有当时的缓存文件么

这个是我在翻译完之后看到的，缓存文件在哪里能看到？

**Comment by NEKOparapa** [comment]
缓存文件不设置自动保存或者导出是没有的。最后使用时有问题出现么？

**Comment by snowandrain** [comment]
> 缓存文件不设置自动保存或者导出是没有的。最后使用时有问题出现么？

能翻译成功，问题倒是没什么，就是有些地方翻译错位，错行检测了之后也有

**Comment by NEKOparapa** [comment]
哦，错行检测的算法现在也只能检测比较明显的错行

**Comment by NEKOparapa** [comment]
新版本已换计数写法
