### ISSUE TITLE
已翻译行数比总翻译行数还要多。

### ISSUE THREAD

**Issue by 98abwt** [NEKOparapa/AiNiee#90]
用的是gemini-pro，导出了缓存文件和已翻译文本看了下，
在还剩下十几行没翻译的情况下，显示百分百翻译，且已翻译行数比总翻译行数还要多。
![QQ截图20240217221050](https://github.com/NEKOparapa/AiNiee/assets/38781031/629393fe-f5df-4964-ac17-762fb5b5b59e)
导出的缓存文件：
[AinieeCacheData[ORCSOFT] 種付けおじさん異世界へ ～孕ませ士種蒔権蔵、エルフの里へ流れ着く編～.json](https://github.com/NEKOparapa/AiNiee/files/14321862/AinieeCacheData.ORCSOFT.json)
导出的未翻译的文本：
[[ORCSOFT] 種付けおじさん異世界へ ～孕ませ士種蒔権蔵、エルフの里へ流れ着く編～_untranslated.json](https://github.com/NEKOparapa/AiNiee/files/14321863/ORCSOFT._untranslated.json)

**Comment by NEKOparapa** [comment]
你中间有暂停翻译过么？

**Comment by NEKOparapa** [comment]
新版本已换计数写法
