### ISSUE TITLE
sakurallm的格式错误太多了

### ISSUE THREAD

**Issue by 1541820933** [NEKOparapa/AiNiee#92]
用默认的30条一多半时间都是格式错误，可不可以自己调整错误上限，让它出现错误就直接拆分呢
![b82b52d1a7e16a1c4d8b38d833d0bdd](https://github.com/NEKOparapa/AiNiee/assets/115207826/af82cf27-ac77-4ef0-8380-e7583ae3af77)

**Comment by NEKOparapa** [comment]
你先把行数调低点10行左右，然后开启保留换行符功能

**Comment by 1541820933** [comment]
sakura0.9有时候会把换行符替换的⚡翻译成闪电或bolt
![image](https://github.com/NEKOparapa/AiNiee/assets/115207826/baa7da9f-e4dd-44d9-965c-3490e91b5ebe)

**Comment by NEKOparapa** [comment]
需要问一下模型作者，哪个符号才不容易被吞

**Comment by 1541820933** [comment]
![image](https://github.com/NEKOparapa/AiNiee/assets/115207826/9d9d909d-01ef-4284-8ae0-fc692337f09a)
wohuan我换回换行符之后成功率高了很多，换行符也没有被翻译
![image](https://github.com/NEKOparapa/AiNiee/assets/115207826/6207f4bd-ca64-4688-814c-607453eedf35)

**Comment by NEKOparapa** [comment]
那就不换了，主要是如果文本中含换行符，容易因为算法按换行符切割文本行，而可能导致无限行数错误

**Comment by NEKOparapa** [comment]
可以下测试版用一下，改善了Sakura现在遇到的问题，如果还有问题请继续反馈一下
