### ISSUE TITLE
使用智谱官方api会有问题

### ISSUE THREAD

**Issue by tisapphire** [NEKOparapa/AiNiee#93]
1.是默认的0自动调节并发不好使，一直会提示该api并发过高，手动调到3左右才好使
![image](https://github.com/NEKOparapa/AiNiee/assets/85567150/fccef970-559a-4ba5-b325-7e643be20a48)

2.返回了文本但是一直提示子线程运行出现问题
![image](https://github.com/NEKOparapa/AiNiee/assets/85567150/208d6e53-cecc-45f2-87cb-0dde870fe8b0)

**Comment by NEKOparapa** [comment]
对，我问官方说，免费是3并发，冲2000，6并发

**Comment by NEKOparapa** [comment]
提示子线程运行出现问题是偶尔出现，还一直出现

**Comment by tisapphire** [comment]
> 出现

一直出现，我看跑了一会翻译进度都是0

**Comment by NEKOparapa** [comment]
那你把原文文件上传一下，我看看

**Comment by tisapphire** [comment]
[[是々非々]男子やめました.json](https://github.com/NEKOparapa/AiNiee/files/14331867/default.json)
上面是原来的文件（是web小说）
试着用智谱跑是跑不了的，但是用openai的api就正常跑完了
[[是々非々]男子やめました.用openai正常跑出来.json](https://github.com/NEKOparapa/AiNiee/files/14331879/openai.json)

**Comment by NEKOparapa** [comment]
我跑了一半，除了出现敏感词错误，没有复现你的问题。如果你下次跑还出现，你截图一下你的翻译设置，当时运行框的截图，还有你跑的文件
