### ISSUE TITLE
sak格式错误很多，但我人工比对了下，发现行数应该是没错的啊

### ISSUE THREAD

**Issue by mingxueyu** [NEKOparapa/AiNiee#99]
如图
![233](https://github.com/NEKOparapa/AiNiee/assets/63766594/9b1e72d7-2701-4fc0-b2eb-78b8248dbf50)
与原文一模一样，是程序判定问题吗？怎么解决呢？

**Comment by mingxueyu** [comment]
![22331](https://github.com/NEKOparapa/AiNiee/assets/63766594/b056be9a-18ce-4490-a782-4d07a7c662cd)
更加确定了，原文与翻译文没有任何问题，我用chatgpt翻译出来也是一样的，但是就是被认为行数错误
问题应该发生在行数的判定上

**Comment by NEKOparapa** [comment]
你把原文打包上传一下，我有空跑一下看看哪里出了问题

**Comment by mingxueyu** [comment]
> 你把原文打包上传一下，我有空跑一下看看哪里出了问题

[Uploading ManualTransFile.json…]()

**Comment by mingxueyu** [comment]
> 你把原文打包上传一下，我有空跑一下看看哪里出了问题

[ManualTransFile.json](https://github.com/NEKOparapa/AiNiee/files/14388869/ManualTransFile.json)
这是原文件，大概是到6%那

**Comment by AmeowCAT** [comment]
我发现了 使用Sakura 然后关闭保留换行符 翻译有换行符的文本就会判断行数错误

**Comment by NEKOparapa** [comment]
可以下测试版用一下，改善了Sakura现在遇到的问题，如果还有问题请继续反馈一下
